### ISSUE TITLE
chinese language is not working 

### ISSUE THREAD

**Issue by lin16303** [erew123/alltalk_tts#101]
just like the topic Russian language is not working #44

 It reads punctuation marks but not letters. English work fine.

within the Text-Generation-WebUI，put something in the "Preview Text box" that work
![QQ截图20240221080049](https://github.com/erew123/alltalk_tts/assets/130566478/e780bbe4-a6d7-4359-b68a-25c7afcc98f2)

**Comment by erew123** [comment]
Hi @lin16303 

You caught me just at the right time! I was just checking Github.

So I am not able to read or speak Chinese and the character set it quite complicated for me. As such, I have tried to do a best effort to see if I can make it work for you. I've set Text-generation-webui's filtering (only text-generation-webui at this time) to allow/pass:

\u4E00-\u9FFF Basic Chinese characters,
\u3400-\u4DBF CJK Unified Ideographs Extension A,
\u20000-\u2A6DF CJK Unified Ideographs Extension B

![image](https://github.com/erew123/alltalk_tts/assets/35898566/20cc1c1b-7af9-458c-8c0d-16823e8e74b1)

I have no clue personally if that's working correctly or incorrectly, so it may be best you perform a `git pull` to update Alltalk (or download `script.py` over the existing one) and give it a go. Also, please ensure you set "chinese" as the language its to read:

(I am sure you will have, but Im just putting this in for anyone who may read this issue in future)
![image](https://github.com/erew123/alltalk_tts/assets/35898566/3bb899eb-3b4e-4674-b32a-c9a5e7683791)

I'm assuming you are a native Chinese speaker, so you should be able to tell me if its working ok or not? 

Thanks

**Comment by erew123** [comment]
Oh, I forgot to add, I have no idea how well this will or wont work with the Narrator function. Theoretically, my brain is telling me it should work ok, but, I have no way to personally test that out.

Thanks

**Comment by ouwenxxing** [comment]
hi @erew123 First thanks for your effort. The TTS feature was great for text generation webui and i was stuck on the the chinese for altalk_tts as well. (guess i'm the second one though)
I just found you are handling the issue. Well i just use your latest code and it works for chinese word but not chinese notion
![image](https://github.com/erew123/alltalk_tts/assets/3252147/3b507c29-666c-47f5-9094-7fe38f7e86e1)
`我可以帮助您执行各种任务，包括但不限于：回答问题、提供建议、生成代码、聊天等。请问您需要什么帮助呢？`

you can see it failed to encode the chinese notition
btw it is possible to support the utf-8 input?

**Comment by ouwenxxing** [comment]
so i managed to set the full set of utf-8 instead and it works..
`cleaned_part = re.sub(r'[^a-zA-Z0-9\s\.,;:!?\-\'"\u0000-\uFFFF\u20000-\u2A6DF\$]', '', cleaned_part)`

![image](https://github.com/erew123/alltalk_tts/assets/3252147/fae06e49-110a-4355-9b2c-4a49bd376dd8)

**Comment by lin16303** [comment]
It can work now, thank you for your efforts. Moreover, enable DeepSpeed, the speed definitely increases. From 26 seconds to around 9 seconds.
![2024-02-22 (2)](https://github.com/erew123/alltalk_tts/assets/130566478/ed4f1d9d-0dcf-4dbc-aadf-2754e8c5db02)
