### ISSUE TITLE
Why did you change the original XTTS "api/speakers_list" endpoint into "api/voices" ?

### ISSUE THREAD

**Issue by illtellyoulater** [erew123/alltalk_tts#103]
Is there any reason why you modified the  default XTTS *speaker_list* endpoint from 

`http://127.0.0.1/api/speakers_list`
to 
`http://127.0.0.1/api/voices`

What's the point? 

Many good clients still come with hardcoded settings for XTTS, as for example Kobold.Cpp... Don't you think it'd be better to adhere to standards where possibile so to not fragment the situation even more?

**Comment by erew123** [comment]
Hi @illtellyoulater 

AllTalk was built from the ground up, I wasn't referencing prior code that someone else had created for an API. I was building something new. Additionally AllTalk was built primarily as an extension for Text-generation-webui to replace the Coqui-TTS extension that was coming with Text-generation-webui (This was not built or made by Coqui), everything else that occurred was organic growth either as requests from people or just as it went.

The voices portion of the API is to pull a list of the sample wav files within the the samples folder. Specifically I introduced it for SillyTavern which needs a list of the files so you can select different voices. https://raw.githubusercontent.com/erew123/screenshots/main/sillytavern.jpg

Additionally Kobold only introduced any form of XTTS support just over 1x month ago https://github.com/LostRuins/koboldcpp/releases/tag/v1.56 I was asked about making AllTalk work with their code, though Im told there was no interest in it https://github.com/erew123/alltalk_tts/issues/88 and I can find no documentation on adding it. 

Im guessing the speakers list may be the inbuilt speakers list https://docs.coqui.ai/en/latest/models/xtts.html#coqui-speakers that is built into the speakers_xtts.pth file? Do you have a documentation/reference point for the API `http://127.0.0.1/api/speakers_list`? 

If its just a case of having a secondary name for `http://127.0.0.1/api/voices` to be available as `http://127.0.0.1/api/speakers_list` its completely possible to do that.

Let me know.

Thanks

**Comment by illtellyoulater** [comment]
Hi @erew123 and thanks for your comprehensive answers and I apologize for making some wrong assumptions. 

I actually thought that `AllTalk` stemmed from https://github.com/daswer123/xtts-api-server, as this is what SillyTavern is currently using for its XTTS backend and for that reason I was seeing that project as some kind of a new de-facto XTTS API reference implementation (after Coqui's shutdown).

Regarding KoboldCpp, I could find that the recent XTTS support they added, is as well leveraging https://github.com/daswer123/xtts-api-server. For example you can see that the `speakers_list` request I initially mentoined is implemented in https://github.com/daswer123/xtts-api-server/blob/main/xtts_api_server/server.py (line 143).

However from my experience so far, `AllTalk` seems to be as a better implementation (more robust and better performing), so it'd be cool if it could also support SillyTavern & KoboldCpp other than just textgeneration-webui. 
What do you think? 

I will now close this issue. But I'll be happy to discuss these aspects further in the other thread you mentioned which specifically deals with this topic (https://github.com/erew123/alltalk_tts/issues/88).

**Comment by erew123** [comment]
Hi @illtellyoulater 

Thanks for the reply. SillyTavern is already fully supported https://docs.sillytavern.app/extras/extensions/alltalk/ 

As long as your SillyTavern is up to date (I think the release in the last month) you should have AllTalk as an option in the TTS list.

As for Danil's XTTS server, we both were developing our own instance related to the XTTS engine at the same time, so neither of our API suites are based on a standard, just what we decided at the time.

Ill reply re Kobold on the other ticket.

Thanks

**Comment by illtellyoulater** [comment]
I identified what prevented AllTalk's "/api/speakers_list" to work with KoboldCpp. The main problem is that in `@app.get("/api/voices")` you return an object like `{"voices": wav_files}`, while KoboldCpp expects a simple array like `["voice1.wav", "voice2.wav", "voice3.wav"]`. 
This simple array is also what https://github.com/daswer123/xtts-api-server returns, explaining why xtts-api-server `/api/voices/` will work, while AllTalk `/api/speakers_list` won't.

For the same reason, I suspect that AllTalk will only work in Silly Tavern when used as a text-generation-webui extension.

Anyway, after identifying this inconsistency, I added the following one-liner fix to KoboldCpp code dealing with the response from AllTalk `/api/voices`:

`if ( !data.length ) { data = data.voices;  }`

This makes KoboldCpp resilient to work with both xtts-api-server and alltalk voice-listing endpoints. 

Once I got that in place, I proceeded to implement in koboldCpp the remaining code for making TTS generation requests to Alltalk, at it ended up working flawlessly. You can read more about that in the other ticket.

**Comment by erew123** [comment]
Hi @illtellyoulater 

Fair play to you for that! I've replied on the other ticket as LostRuins contacted me/us there.

I'm not sure how they prefer Kobold handles the generated audio, does it play back the wav files through the web page or as you have set it, to play through the AllTalk server command prompt, so that may need checking over.

Also, not having seen the interface of Kobold, things like implementing the narrator may be a bit more of a complicated thing to do (if thats something they want at some point).

Re SillyTavern, its using the standard API suite that you have worked with here, but Text-generation-webui uses a separate undocumented API call. So AllTalk works fine as a full standalone with SillyTavern when installed with the Standalone method.

Anyway, I guess we will see where this goes when LostRuins responds. Maybe its best to keep conversation on the other ticket or within your PR to Kobold rather than juggle multiple areas.

Thanks!
