### ISSUE TITLE
AllTalk fails to load XTTSv2 even on a fresh install

### ISSUE THREAD

**Issue by guska84** [erew123/alltalk_tts#106]
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/14441643/diagnostics.log)
Please generate a diagnostics report and upload the "diagnostics.log".

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
After installing AllTalk TTS on either an existing, or a fresh text-generation-webui install, AllTalk TTS fails to load XTTSv2

I have tried with TTS versions 0.22.0 and uninstalling that and installing 0.21.3. Exact same result.

Running script.py directly from the python environment results in the same behaviour

**To Reproduce**
Install AllTalk TTS using Quick Setup on a fresh installation of text-generation-webui and attempt to start it

**Screenshots**
N/A

**Text/logs**
`12:18:38-712637 INFO     Loading the extension "alltalk_tts"
[AllTalk Startup] Coqui Public Model License
[AllTalk Startup] https://coqui.ai/cpml.txt
[AllTalk Startup] Old output wav file deletion is set to disabled.
[AllTalk Startup] Checking Model is Downloaded.
[AllTalk Startup] TTS version installed: 0.21.3
[AllTalk Startup] TTS version is up to date.
[AllTalk Startup] All required files are present.
[AllTalk Startup] TTS Subprocess starting
[AllTalk Startup]
[AllTalk Startup]  AllTalk Settings & Documentation: http://127.0.0.1:7851
[AllTalk Startup]
[AllTalk Startup] DeepSpeed Not Detected. See https://github.com/microsoft/DeepSpeed
[AllTalk Model] XTTSv2 Local Loading xttsv2_2.0.2 into cuda
ERROR:    Traceback (most recent call last):
  File "G:\GPT\text-generation-webui-main\installer_files\env\Lib\site-packages\starlette\routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "G:\GPT\text-generation-webui-main\installer_files\env\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\GPT\text-generation-webui-main\extensions\alltalk_tts\tts_server.py", line 131, in startup_shutdown
    await setup()
  File "G:\GPT\text-generation-webui-main\extensions\alltalk_tts\tts_server.py", line 176, in setup
    model = await xtts_manual_load_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\GPT\text-generation-webui-main\extensions\alltalk_tts\tts_server.py", line 245, in xtts_manual_load_model
    config.load_json(str(config_path))
  File "G:\GPT\text-generation-webui-main\installer_files\env\Lib\site-packages\coqpit\coqpit.py", line 728, in load_json
    dump_dict = json.loads(input_str)
                ^^^^^^^^^^^^^^^^^^^^^
  File "G:\GPT\text-generation-webui-main\installer_files\env\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\GPT\text-generation-webui-main\installer_files\env\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\GPT\text-generation-webui-main\installer_files\env\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ERROR:    Application startup failed. Exiting.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.

[AllTalk Startup] Startup timed out. Full help available here https://github.com/erew123/alltalk_tts#-help-with-problems
[AllTalk Startup] On older system you may wish to open and edit script.py with a text editor and changing the
[AllTalk Startup] startup_wait_time = 120 setting to something like startup_wait_time = 240 as this will allow
[AllTalk Startup] AllTalk more time to try load the model into your VRAM. Otherise please visit the Github for
[AllTalk Startup] a list of other possible troubleshooting options.
12:21:15-390712 ERROR    Failed to load the extension "alltalk_tts".
Traceback (most recent call last):
  File "G:\GPT\text-generation-webui-main\modules\extensions.py", line 37, in load_extensions
    extension = importlib.import_module(f"extensions.{name}.script")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\GPT\text-generation-webui-main\installer_files\env\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\GPT\text-generation-webui-main\extensions\alltalk_tts\script.py", line 324, in <module>
    sys.exit(1)
SystemExit: 1`

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date]
Custom Python environment: [yes/no give details if yes]
Text-generation-webUI was updated: [approx. date]

**Additional context**
N/A

**Comment by erew123** [comment]
Hi @guska84 

Ive had a look into this. First off let me just say that I wiped my entire text-generation-webui and reinstalled it from factory, pulled down AllTalk afresh and confirmed that I had exactly the same versions of software as yourself:

![Untitled](https://github.com/erew123/alltalk_tts/assets/35898566/c2cb4b12-b324-4b49-a1e1-3ff3c5ad0f9f)

I also confirmed Nvidia drivers and Python versions were matched. Everything worked fine, so we can discount it being a issue with the requirements file, update of some software or something like that.

The specific error you are getting is related to AllTalk trying to load the config.json data for the model from the folder `\text-generation-webui\extensions\alltalk_tts\models\xttsv2_2.0.2` The folder should look something like this:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/bfa54589-fe48-4f16-a083-c7adb23ab30b)

Are those files there? Or is there something special about your G drive on your system e.g. is it a USB drive or a Virtual drive? 

Thanks

**Comment by guska84** [comment]
hi @erew123 

I greatly appreciate your assistance and the dedication to wipe your install and version match.

G Drive is nothing more exotic or wacky than a normal SSD in my system. Checking that folder, the files are indeed there, but, all were 3KB in size, and upon checking, all HTML docs.

I manually downloaded XTTSv2 from https://huggingface.co/coqui/XTTS-v2/tree/v2.0.2 and dropped them in, and off it went.

![image](https://github.com/erew123/alltalk_tts/assets/17737429/b58e7812-6b39-4d0a-8bec-f068f20672a4)

Thank you for the poke in the right direction. I'm not sure how I missed that, to be honest.

Cheers,
guska
