### ISSUE TITLE
Solution: Better Fix for Cuda Home on Linux

### ISSUE THREAD

**Issue by RandomInternetPreson** [erew123/alltalk_tts#107]
Hello, I really want you to know how much I love this extension!!! OMG <3 Thank you so much, it is really appreciated.  

The integration of deepspeed in particular lets one pretty much talk to their models in real time.  I had been using your extension in windows using the prebuilt wheels and they were working great.

I recently switched over to ubuntu and got deepspeed working as per your instructions.  The initialization of deepspeed is a little cumbersome and I had a lot of stuff in my CMD_FLAGS.txt file that I wanted to automatically run when starting oobabooga.

I figured out that putting:

export CUDA_HOME="/usr/local/cuda"

Right above:
# setup installer env 

in the start_linux.sh file is a lot easier and let's me use the CMD_Flags.txt file once again.

I have included an image to help make it more clear:

![cudahome](https://github.com/erew123/alltalk_tts/assets/6488699/300ab7f3-33e1-4fd8-b955-0f145f2a865a)

**Comment by erew123** [comment]
Hi @RandomInternetPreson 

Thanks so much! Its always great to hear that people use it and enjoy it! If I ever put up a reviews section, Ill have have to quote you :) Seriously, thanks for the feedback, it genuinely is nice to hear!

TTS with DeepSpeed on Linux always seems faster to me (on the same machine) compared to Windows. Sufficiently fast enough to notice a difference.

Sticking the `export` in the start-up script, well, id never thought about giving that a go. But I cant see why it would be a problem. I've added it to documentation as a suggestion for Linux DeepSpeed. Thanks for the suggestion on that!

All the best!
