### ISSUE TITLE
Deepspeed: PyTorch mismatch with latest TextGen-WebUI

### ISSUE THREAD

**Issue by altoiddealer** [erew123/alltalk_tts#111]
First off, thank you so much for this excellent extension and how well you've maintained it.

After running into some issues after a textgenwebui update, I just did a fresh clean install of that.

I also did a fresh clean install of alltalk_tts, using the new installer file, first installing the nVidia requirements, followed by the deepspeed requirements (second option, which matches my environment).

I'm getting an error after activating deepspeed:
```
RuntimeError: PyTorch version mismatch! DeepSpeed ops were compiled and installed with a different version than what is being used at runtime.
Please re-install DeepSpeed or switch torch versions. Install torch version=2.1, Runtime torch version=2.2
```
Full error:
[error-log.txt](https://github.com/erew123/alltalk_tts/files/14542062/error-log.txt)

diagnostics report (I may or may not have actually uninstalled Deepspeed before generating - see screenshot):
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/14542130/diagnostics.log)

<img width="653" alt="Screenshot 2024-03-08 134803" src="https://github.com/erew123/alltalk_tts/assets/1613484/697eb8d7-ed0f-49c4-acb1-a962cb1d3645">

**Desktop (please complete the following information):**
AllTalk was updated: 3/8/2024 (fresh install)
Custom Python environment: No
Text-generation-webUI was updated: 3/8/2024 (fresh install)

**Comment by erew123** [comment]
Hi @altoiddealer 

Well, you'll be pleased to know you arent going mad or have done anything wrong. It was nice and easy to find the problem:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/81d3eea5-ea8b-48f9-840a-0cc89b03c406)

The versions of DeepSpeed that I have pre-compiled are for PyTorch 2.1.x (and they are annoyingly version specific) and Text-Gen-webui looks like its just bumped the version of Pytorch to 2.2.x https://github.com/oobabooga/text-generation-webui/commit/164ff2440d8a4b05db6671f00df22b83bb49436f

In short, it will be a case of compiling a new build of DeepSpeed to work on Pytorch 2.2.x. I don't have my system set up to do that at the moment. You have 3x choices:

1. Force a downgrade of Pytorch, but Im not sure if this will impact other things within Text-Gen-webui.. it might!
2. Compile up a copy of DeepSpeed (it can be a pain in the ass to do). https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-windows-installation
3. Wait for me to get one compiled up. To do this, I always wipe my full text-gen-webui environment and have to do all those bits, as you really need a cleaner install as possible. I should be able to do something within a couple of days. I will have to update the installer too.

If you just want to wait, you may have to uninstall deepspeed for now.

If you have any more question, let me know,

Thanks

**Comment by altoiddealer** [comment]
> Hi @altoiddealer
> 
> Well, you'll be pleased to know you arent going mad or have done anything wrong. It was nice and easy to find the problem:
> 
> ![image](https://private-user-images.githubusercontent.com/35898566/311360260-81d3eea5-ea8b-48f9-840a-0cc89b03c406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MzUzMTUsIm5iZiI6MTcwOTkzNTAxNSwicGF0aCI6Ii8zNTg5ODU2Ni8zMTEzNjAyNjAtODFkM2VlYTUtZWE4Yi00OGY5LTg0MGEtMGNjODliMDNjNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDIxNTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NjAyYjYzMDFkNGZlNGMwY2VkZWRkNmFhYzRlMDMxYjRjNTYwZmYwMTFkYjE4OWQ0OWI2NzdmMzBhMjk0ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zd04haEnD9JpwS5ye7REwO48aiGkGyEQdUPM_8FLYmM)
> 
> The versions of DeepSpeed that I have pre-compiled are for PyTorch 2.1.x (and they are annoyingly version specific) and Text-Gen-webui looks like its just bumped the version of Pytorch to 2.2.x [oobabooga/text-generation-webui@164ff24](https://github.com/oobabooga/text-generation-webui/commit/164ff2440d8a4b05db6671f00df22b83bb49436f)
> 
> In short, it will be a case of compiling a new build of DeepSpeed to work on Pytorch 2.2.x. I don't have my system set up to do that at the moment. You have 3x choices:
> 
> 1. Force a downgrade of Pytorch, but Im not sure if this will impact other things within Text-Gen-webui.. it might!
> 2. Compile up a copy of DeepSpeed (it can be a pain in the ass to do). https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-windows-installation
> 3. Wait for me to get one compiled up. To do this, I always wipe my full text-gen-webui environment and have to do all those bits, as you really need a cleaner install as possible. I should be able to do something within a couple of days. I will have to update the installer too.
> 
> If you just want to wait, you may have to uninstall deepspeed for now.
> 
> If you have any more question, let me know,
> 
> Thanks

I expected all this essentially :)

Personally, I can just hang tight for the updated precompiled Deepspeed, I'll just keep my eyes peeled for it.

Thanks!

**Comment by erew123** [comment]
Youre in luck, Ive managed to get a version sorted, but I have other versions to do, and testing and software updates..... so for anyone else reading, I wont get around to CUDA 11.8 or the automatic installers for a few days.

@altoiddealer you can follow the links+instructions here and it should be good for you https://github.com/erew123/alltalk_tts/issues/112

Thanks
