### ISSUE TITLE
Finetune Step 2 Error: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by brandonwsaw** [erew123/alltalk_tts#118]
Please generate a diagnostics report and upload the "diagnostics.log".

[diagnostics.log](https://github.com/erew123/alltalk_tts/files/14567883/diagnostics.log)

**Describe the bug**
  Getting `RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory` during Step 2 of Finetuning. 

**To Reproduce**
 Finetuning Step 2 from clean text-generation-webui-main install, Windows 10. Diagnostics Log shows Cuda 12.3, which I did have already installed, but I followed steps to install/update path to Cuda 11.8, and `nvcc --version` returns 11.8.

**Screenshots**

**Text/logs**
```[FINETUNE] Dataset Generated. Move to Step 2
[FINETUNE] Starting Step 2 - Fine-tuning the XTTS Encoder
[FINETUNE] Starting finetuning on Base Model
Traceback (most recent call last):
  File "D:\text-generation-webui-main\text-generation-webui-main\extensions\alltalk_tts\finetune.py", line 1110, in train_model
    config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=str(output_path), max_audio_length=max_audio_length)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui-main\extensions\alltalk_tts\finetune.py", line 426, in train_gpt
    model = GPTTrainer.init_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\TTS\tts\layers\xtts\trainer\gpt_trainer.py", line 500, in init_from_config
    return GPTTrainer(config)
           ^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\TTS\tts\layers\xtts\trainer\gpt_trainer.py", line 185, in __init__
    dvae_checkpoint = torch.load(self.args.dvae_checkpoint, map_location=torch.device("cpu"))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\text-generation-webui-main\text-generation-webui-main\installer_files\env\Lib\site-packages\torch\serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date] 3/11/2024
Custom Python environment: [yes/no give details if yes] No
Text-generation-webUI was updated: [approx. date] 3/11/2024

**Additional context**

**Comment by brandonwsaw** [comment]
Thanks that worked to fix that error. The existing dvae.path was only 77MB in size, so not sure how that happened.

I think unrelated, but now Training is getting stuck on Epoch 0, Step 0 (~3 mins of audio) even when I leave it overnight. I have a NVIDIA 3070, is it just insufficient for fine tuning?

``` > EPOCH: 0/10
 --> D:\text-generation-webui-main\text-generation-webui-main\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_02+46AM-1934cb61
 > Sampling by language: dict_keys(['en'])

 > TRAINING (2024-03-13 02:46:22)

   --> TIME: 2024-03-13 10:23:51 -- STEP: 0/13 -- GLOBAL_STEP: 0
     | > loss_text_ce: 0.018566636368632317  (0.018566636368632317)
     | > loss_mel_ce: 4.216745853424072  (4.216745853424072)
     | > loss: 4.235312461853027  (4.235312461853027)
     | > grad_norm: 0  (0)
     | > current_lr: 5e-06
     | > step_time: 143.8926  (143.89256048202515)
     | > loader_time: 108.0994  (108.09939193725586)```

**Comment by erew123** [comment]
Hi @brandonwsaw 

A 3070 should be fine for training. Im assuming the model.pth file isn't damaged too? (check the image in my earlier reply).

And you have 18GB of disk space free when you start training? (it needs this much for temp disk space)

Thanks

**Comment by erew123** [comment]
I don't believe disk space on the C drive would have any particular impact.

Typically I fine tune on C drive (which I know is working fine). Let me run a test on my D drive and see if theres possibly some random issue with C/D drive (pretty sure Ive tested in the past, but Ill double check)... BRB

**Comment by erew123** [comment]
Hi @brandonwsaw 

So I like for like matched your file structure/path. We've already been through checking your Python environment at the top of this ticket.

I've run through finetuning twice and both worked:

**Highlighted BLUE** - My D drive and the finetuning temp folder, you can see the model files being created here at the end of each epoch.
**Highlighted YELLOW** - I kept an eye on my C drive to see if there was any file change there. To be honest, there was, at one point I had a 3GB jump in disk space. It went up and dropped down again. But it certainly wasn't 15GB of disk space. 
**Highlighted GREEN** - You can see I have the matching file structure, the same as yourself. You training stops at `"| > loader_time: 108.0994  (108.09939193725586)` ? is that correct?

![image](https://github.com/erew123/alltalk_tts/assets/35898566/7dfe1b5f-eff4-4052-bc92-297e0a48e6b8)

The only thing I can possibly think at this moment is there could possibly be something very odd with your audio files perhaps. 

Maybe you might want to try a different file https://file.io/6GKhwUTckLfO and just see if that works (remove the other files in your "put-voice-samples-in-here" folder and delete the tmp-trn folder from within the finetune folder.

I know this audio file goes through fine as its one I use to test finetuning. On Step 2, set your Epoch's at 2, which is enough for testing.

Let me know

Thanks

**Comment by erew123** [comment]
Hi @brandonwsaw 

First off, great to prove that it works and makes it through it in some way, at least we know its processing and its not some bug in the script. However, this leads me to suspect its a resource issue somehow. I know you have a 3070 8GB, which I've had other people confirm is fine, however, I will say that there are periods within the training where it will spill over VRAM into your system RAM. So with 16GB system ram, depending on what else is running on your system, that could be causing an issue. You would have to monitor your GPU VRAM and memory in Task Manager to see what's going on there.

Also, are you running this on a mechanical hard drive? I've never tried it on one or thought about it, but there is a lot of data getting thrown around, so that would have some impact for sure.

My dev system is a Radeon 5700G, 32GB ram and SSD (for the D drive) and I am running it with a Nvidia 4070 12GB. There are spikes in my VRAM use, which sees me spill into system ram about 1GB or so. However, I'm getting an epoch every 2 minutes or so (see below "TRAINING" to the next "TRAINING").

![image](https://github.com/erew123/alltalk_tts/assets/35898566/e3522781-bd22-4ffa-aa86-5cc7af43bb76)

I don't specifically know why your 3 minute audio would take any longer than the audio I sent. At this point in time I would just pass that off as a random thing.

So Im pretty sure that one way or another its a performance issue.

1) More system RAM may probably help, but I appreciate that's a cost thing.
2) Running on an SSD or NVME drive will help.
3) Monitoring System RAM use looking at Available and Paged memory during training to see if they are full. Certainly if its using paged memory of any quantity, thats not going to be good at all for performance.
4) Generally making sure that nothing else is running/using your VRAM or System Ram (bar the base operating system).
5) If you have a Antivirus that is doing lots of scanning on those files as they are copied, generated, moved about etc, that will also take its toll.

Obviously you could have one or more of those occurring and this is my best speculation on what's going on.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/413b8b0e-bd9d-49fb-bd66-884f1dc86927)

**Comment by brandonwsaw** [comment]
Yeah my D drive is a mechanical drive, hmm, will clear up some space on my SSD/NVME and see if that helps, and see what's going on with RAM. Thanks for all the input, will report back.

**Comment by brandonwsaw** [comment]
Hmm, yeah same behavior on my C Drive that is SSD/NVME. Paged Pool doesn't go up during training, but my memory does go up to 80-90% utilization (1-2.5 GB available). Not sure if that indicates being blocked. It does that for both 2 and 10 Epochs, but 2 Epochs still works while 10 gets stuck. 

Any theories on why changing Epochs seems to help/hurt? In any case, seems like some sort of performance issue on my end, thanks for helping troubleshoot and narrow it down.

**Comment by erew123** [comment]
I couldn't give you an exact "this is the reason why" answer. Certainly you could be suffering fragmentation of the memory/model after its having to split the models layers between VRAM and System RAM, which could well degrade over time, Think of it like having a pack of cards that are in the correct order, each time you split the pack and blend them together again, the further you get away from the original state/being in the correct order.

So it might be on Epoch 1 the models layers (lets say it has 40 layers), 1-20 are contiguous in VRAM and 21-40 are contiguous in System RAM. So as you go through the 1st epoch, it would go through 1-20, then shuffle some out so it can start pushing in 21-40.

As you keep moving through, each individual layer may get split into multiple parts, spread between VRAM and System RAM, and more and more as it keeps moving on. Don't forget its also throwing the audio samples in and out the GPU too. So it may **(lots of speculation here on my part)** just end up compounding the issue, the further it goes through the epochs.

You may also be ending up with more things from ram being paged to the swapfile too, which of course, is on your disk, so double trouble there with disk performance, memory fragmentation etc.

I would imagine you have noticed **some** performance gain, being on your NVME/SSD.

If I were to place my bets, I would imagine that more System RAM would probably alleviate the issue, at least to the extent that your system is capable of performing finetuning. But, again, this is all based on my speculation (well, and 20+ years in the IT industry). Still, this is me placing a bet and NOT saying "buy more memory and I am 1000% going to tell you everything will be peachy". There could still be other factors, even down to Pytorch 2.2.1 having some funky bug in it (Text-gen-webui only introduced it a couple of weeks back and its only been released recently).

However, saying all that, if you can get it to finetune on 2-x epochs, although its a bit more of a pain in the ass, you can train a model multiple times on the same dataset. You would get to the "whats next" move the model to "trainedmodel", reload finetune.py, step 1 will take seconds (if you dont delete the training data) and then on Step 2, pick the "existing finetuned model" and do another 2-x epoch run.

I know thats not exactly ideal, but will at least give you some sort of workaround.

Of course, if something pops up at some point in the near future where I find out there was a bug in PyTorch or something, Ill let you know ASAP.

**Comment by brandonwsaw** [comment]
Amazing, thanks for all the help. I was thinking of upgrading my RAM anyways since 32GB seems like the new 16GB these days, if I do so will report back.

**Comment by erew123** [comment]
Ill close the ticket off for now and Ill get back to you on here if anything comes up bug wise that may be relevant and if you need to do something re this issue again, feel free to reply back here.

Have a good weekend!
