### ISSUE TITLE
Finetuning Step 2 does not generate best_model.pth

### ISSUE THREAD

**Issue by UserSpy** [erew123/alltalk_tts#124]
When loading the fine-tuned XTTS model in step 3, I receive :

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:/text-generation-webui/extensions/alltalk_tts/finetune/tmp-trn/training/XTTS_FT-March-13-2024_03+05AM-705f04a/best_model.pth'

![image](https://github.com/erew123/alltalk_tts/assets/100179416/57e7d5a5-0f1c-4425-b87d-9ccd298d463f)

best_model.pth, or any pth for that matter is not present in the specified training folder. I ran step 2 again twice to confirm. 

Here is the trainer log

 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 12
 | > Num. of Torch Threads: 1
 | > Torch seed: 1
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

 > Model has 517360175 parameters

[4m[1m > EPOCH: 0/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:05:27) [0m

[1m   --> TIME: 2024-03-13 03:06:44 -- STEP: 0/12 -- GLOBAL_STEP: 0[0m
     | > loss_text_ce: 0.017916124314069748  (0.017916124314069748)
     | > loss_mel_ce: 5.27035665512085  (5.27035665512085)
     | > loss: 5.288272857666016  (5.288272857666016)
     | > grad_norm: 0  (0)
     | > current_lr: 5e-06 
     | > step_time: 1.1729  (1.1728687286376953)
     | > loader_time: 75.11  (75.1099841594696)

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time: 0.029076576232910156 [0m(+0)
     | > avg_loss_text_ce: 0.018992742523550987 [0m(+0)
     | > avg_loss_mel_ce: 5.184468746185303 [0m(+0)
     | > avg_loss: 5.203461647033691 [0m(+0)

[4m[1m > EPOCH: 1/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:06:57) [0m

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[92m 0.015838146209716797 [0m(-0.01323843002319336)
     | > avg_loss_text_ce:[92m 0.018890030682086945 [0m(-0.00010271184146404266)
     | > avg_loss_mel_ce:[92m 4.65269660949707 [0m(-0.5317721366882324)
     | > avg_loss:[92m 4.671586513519287 [0m(-0.5318751335144043)

[4m[1m > EPOCH: 2/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:08:12) [0m

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[92m 0.01572895050048828 [0m(-0.00010919570922851562)
     | > avg_loss_text_ce:[92m 0.01876462809741497 [0m(-0.00012540258467197418)
     | > avg_loss_mel_ce:[92m 4.255389213562012 [0m(-0.3973073959350586)
     | > avg_loss:[92m 4.274153709411621 [0m(-0.397432804107666)

[4m[1m > EPOCH: 3/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:09:29) [0m

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[91m 0.016025304794311523 [0m(+0.0002963542938232422)
     | > avg_loss_text_ce:[92m 0.018741972744464874 [0m(-2.265535295009613e-05)
     | > avg_loss_mel_ce:[92m 4.120433807373047 [0m(-0.13495540618896484)
     | > avg_loss:[92m 4.139175891876221 [0m(-0.1349778175354004)

[4m[1m > EPOCH: 4/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:10:45) [0m

[1m   --> TIME: 2024-03-13 03:11:54 -- STEP: 2/12 -- GLOBAL_STEP: 50[0m
     | > loss_text_ce: 0.019663292914628983  (0.020105126313865185)
     | > loss_mel_ce: 3.2016401290893555  (3.4178727865219116)
     | > loss: 3.2213034629821777  (3.437977910041809)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06 
     | > step_time: 0.1589  (0.171608567237854)
     | > loader_time: 0.0041  (0.0074863433837890625)

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[91m 0.018204450607299805 [0m(+0.0021791458129882812)
     | > avg_loss_text_ce:[92m 0.018661484122276306 [0m(-8.048862218856812e-05)
     | > avg_loss_mel_ce:[92m 4.058572292327881 [0m(-0.061861515045166016)
     | > avg_loss:[92m 4.077233791351318 [0m(-0.061942100524902344)

[4m[1m > EPOCH: 5/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:12:02) [0m

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[92m 0.016020536422729492 [0m(-0.0021839141845703125)
     | > avg_loss_text_ce:[92m 0.018653130158782005 [0m(-8.353963494300842e-06)
     | > avg_loss_mel_ce:[92m 4.022769927978516 [0m(-0.035802364349365234)
     | > avg_loss:[92m 4.0414228439331055 [0m(-0.03581094741821289)

[4m[1m > EPOCH: 6/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:13:31) [0m

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[91m 0.01705169677734375 [0m(+0.0010311603546142578)
     | > avg_loss_text_ce:[92m 0.018641365692019463 [0m(-1.1764466762542725e-05)
     | > avg_loss_mel_ce:[92m 4.0036234855651855 [0m(-0.019146442413330078)
     | > avg_loss:[92m 4.0222649574279785 [0m(-0.019157886505126953)

[4m[1m > EPOCH: 7/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:14:47) [0m

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[91m 0.017148971557617188 [0m(+9.72747802734375e-05)
     | > avg_loss_text_ce:[91m 0.01864929124712944 [0m(+7.925555109977722e-06)
     | > avg_loss_mel_ce:[91m 4.031964302062988 [0m(+0.028340816497802734)
     | > avg_loss:[91m 4.0506134033203125 [0m(+0.028348445892333984)

[4m[1m > EPOCH: 8/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:16:03) [0m

[1m   --> TIME: 2024-03-13 03:17:15 -- STEP: 4/12 -- GLOBAL_STEP: 100[0m
     | > loss_text_ce: 0.01678699254989624  (0.019588160328567028)
     | > loss_mel_ce: 2.9785172939300537  (2.91434383392334)
     | > loss: 2.9953043460845947  (2.9339320063591003)
     | > grad_norm: 0  (0.0)
     | > current_lr: 5e-06 
     | > step_time: 0.229  (0.2197088599205017)
     | > loader_time: 0.005  (0.0049111247062683105)

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[92m 0.016770601272583008 [0m(-0.0003783702850341797)
     | > avg_loss_text_ce:[92m 0.018619850277900696 [0m(-2.9440969228744507e-05)
     | > avg_loss_mel_ce:[92m 4.013489246368408 [0m(-0.018475055694580078)
     | > avg_loss:[92m 4.032109260559082 [0m(-0.01850414276123047)

[4m[1m > EPOCH: 9/10[0m
 --> D:\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_03+05AM-705f04a

[1m > TRAINING (2024-03-13 03:17:22) [0m

[1m > EVALUATION [0m

  [1m--> EVAL PERFORMANCE[0m
     | > avg_loader_time:[92m 0.015027761459350586 [0m(-0.0017428398132324219)
     | > avg_loss_text_ce:[92m 0.01855466514825821 [0m(-6.518512964248657e-05)
     | > avg_loss_mel_ce:[91m 4.023611068725586 [0m(+0.010121822357177734)
     | > avg_loss:[91m 4.042165756225586 [0m(+0.010056495666503906)

**Comment by erew123** [comment]
Hi @UserSpy 

On Step 2 did you get a message saying "Model training done. Move to Step 3"?

![image](https://github.com/erew123/alltalk_tts/assets/35898566/424c1cb6-241a-4d12-b637-08a5739c9197)

I've just run through a fresh install myself (I reduced to the 1x epoch to speed things up) and its run through fine on my system here.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/16f35eb2-b4f9-4d5c-b7d4-b33e5daf12e5)

The finetuned models do use a good chunk of disk space before they are compressed down (This happens on Step 4) so I assume you have 15GB free on your D drive? (as you may note there are 2x files at this point, each 5GB in size), one is the previous epoch and the other file is the current epoch, so it needs quite a bit of working space when training.

FYI, this is what you should see at the end of Step 2.

 > EVALUATION


  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.0394665002822876 (+0)
     | > avg_loss_text_ce: 0.018014189787209034 (+0)
     | > avg_loss_mel_ce: 3.787397027015686 (+0)
     | > avg_loss: 3.805411219596863 (+0)

 **> BEST MODEL : C:\AI\text-generation-webui\extensions\alltalk_tts\finetune\tmp-trn\training\XTTS_FT-March-13-2024_10+45AM-c147093\best_model_16.pth
[FINETUNE] Model training done. Move to Step 3**

**Comment by erew123** [comment]
Just to clarify, as it moves through the Epochs, it will end up with 3x of those files

![image](https://github.com/erew123/alltalk_tts/assets/35898566/69c40c9b-e77a-4693-aef8-d85538ea366a)

One is the last one it worked on, one is the one its working on and one is a copy of the current one when it completes, before it starts work on it for the next epoch.

So you are looking closer to 18GB of free disk space (I know I said 15GB above, but I checked and its noted on the first page of the Finetuning that 18GB free is what I originally tested as being required).

You should also see in your command prompt the "best model" file name incrimenting upwards

![image](https://github.com/erew123/alltalk_tts/assets/35898566/b1fe2583-ec70-44c7-a6ca-6d7127d62e3d)

and the files are visible in the folder as its doing this.

You can set your epoch down to one and run a quick test to see if:

1) its listing the file as incrementing in the command prompt window.
2) if the files are actually being created (at the end of each epoch).

If you dont see that and you are still having issues, could you send me a diagnostics log file please? https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-how-to-make-a-diagnostics-report-file

**Comment by erew123** [comment]
Hi @UserSpy 

Did the above help at all? I have also updated Finetuning recently as today, so you may wish to try the new build.

Thanks

**Comment by UserSpy** [comment]
Apologize for the delay. Unfortunately did not seem to help. While my space is limited, I have more than 20gb available on both drives on my PC. However, I did notice that while Step 2 is running, the C drive has less space on it, despite running fine-tuning on my D drive. Might try doing a standalone install on my C drive and see how that works.

[diagnostics (finetune).log](https://github.com/erew123/alltalk_tts/files/14656697/diagnostics.finetune.log)
[diagnostics (nvidia).log](https://github.com/erew123/alltalk_tts/files/14656714/diagnostics.nvidia.log)

**Comment by erew123** [comment]
Hi @UserSpy 

I cant say if it could be an issue, but you may want to update your Nvidia driver. You have 536.67 which is July last year. I have no idea if the transformers scripts in Python *could* have an issue with older Nvidia drivers. Latest build for your card would be 551.86 https://www.nvidia.com/Download/driverResults.aspx/223498/en-us/

You may also wish to update AllTalk as the finetuning had some updates over the last few days and it now does some checks of your environment (though disk space is currently just a FYI). It can help identify if anything is amiss (though your config generally, as a cursory glance looks good to me).

https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-updating

Thanks

**Comment by UserSpy** [comment]
I did a fresh reinstall with the update, but ran into the same issue. I tried doing a standalone install on the C drive, ran into too many issues with that, so ended up installing oobabooga on my C drive and installing alltalk as the extension. Had to update my CUDA to 12.1 from 11.8 for some reason to do step 1, but step 2 is working correctly now and I'm getting best model pth files saved. 

Still not sure why I couldn't run it from my D drive, but maybe temporary files are being stored on the C drive by default and it didn't like moving large files back to the D drive? Thanks for your help and quick responses.

**Comment by erew123** [comment]
Hi @UserSpy 

I honestly cant think of a reason why it would be an issue on the D drive. Nothing I have done is hard coded to use any specific drive letter. Its not possible for me to do that as the scripts have to work across Windows, Linux and Mac file systems, so cant be that.

I also have 2x copies installed one in text-gen-webui on my C drive and one as a Standalone on my D drive (well Linux copies too, but we are looking at Windows here). I've not been able to re-create the same issue.

I suppose there could be a weird quirk introduced in a recent update to PyTorch with CUDA 11.8. I do normally test in a PyTorch CUDA 12.1 environment. Though saying that, when I look at the diagnostics you sent me before, it shows a PyTorch CUDA 12.1 Python environment (cu121 is CUDA 12.1):

![image](https://github.com/erew123/alltalk_tts/assets/35898566/998b6047-ec0d-47c7-a7ee-97c1fc107617)

So, I'm honestly not sure with what was going on there. I have started to introduce more checks on the scripts so maybe Ill see if there are a few more checks I can introduce there e.g. permissions checks etc.

There is a silver lining though, if you have updated your Nvidia driver and youre using CUDA 12.1 in your Python environment (were you not before) you should get some speed increase in Text-gen-webui when using an LLM.

Glad you have it working though.
