### ISSUE TITLE
Ja language fine tuning is not possible

### ISSUE THREAD

**Issue by rinechran** [erew123/alltalk_tts#130]
Please generate a diagnostics report and upload the "diagnostics.log".

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
Ja language fine tuning is not possible

**To Reproduce**
Ja language fine tuning is not possible

**Screenshots**
![image](https://github.com/erew123/alltalk_tts/assets/15512801/e72310a4-e663-4893-9595-6304d4029ed4)

**Text/logs**
 File "/mnt/ssd/project/alltalk_tts/finetune.py", line 1006, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(target_language=language, whisper_model=whisper_model, out_path=out_path, eval_split_number=eval_split_number, gradio_progress=progress)
  File "/mnt/ssd/project/alltalk_tts/finetune.py", line 229, in format_audio_list
    sentence = multilingual_cleaners(sentence, target_language)
  File "/mnt/ssd/project/alltalk_tts/venv-tts/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 558, in multilingual_cleaners
    text = expand_numbers_multilingual(text, lang)
  File "/mnt/ssd/project/alltalk_tts/venv-tts/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 538, in expand_numbers_multilingual
    text = re.sub(_ordinal_re[lang], lambda m: _expand_ordinal(m, lang), text)
KeyError: 'ja'
format_audio_list^C[FINETUNE] Received interrupt signal. Cleaning up and exiting...

**Desktop (please complete the following information):**
AllTalk was updated: tex
Text-generation-webUI was updated: yes

**Additional context**

**Comment by erew123** [comment]
Hi @rinechran 

When did you last update? There was a code update 5 days ago that should resolve any Japanese training issues, could you confirm you are up to date? 

**Code update**
https://github.com/erew123/alltalk_tts/commit/86c64fc9ba0f223df5844efed6e03d803bfc55d7

**How to update**
https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-updating

Thanks

**Comment by rinechran** [comment]
i've seen the issue , and i 've asho confirmed that the version i'm writeng is the one that fixed the issue

**Comment by erew123** [comment]
@rinechran Ive just literally updated the Finetuning again about 5 minutes ago. Would you like to update to that version with a `git pull` in the `alltalk_tts` directory and give it a try. 

I ran the finetuning today after your earlier message and selected Japanese and didn't have any issue with Step 2 of Finetuning. So I am puzzled what could be occurring on your system.

If you still have a failure after the update, would you be able to send me a diagnostic log file please? https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-how-to-make-a-diagnostics-report-file

**Comment by erew123** [comment]
@rinechran Just to confirm I have kicked off a "ja" Japanese Finetuning again and its processing through as it should do. So I would definitely need an diagnostics file to try figure whats going on (after you have updated and tested).

Thanks

![image](https://github.com/erew123/alltalk_tts/assets/35898566/bc482582-b9eb-4f63-9366-6059d37563ea)

**Comment by rinechran** [comment]
![image](https://github.com/erew123/alltalk_tts/assets/15512801/bc3ff93e-edfe-40c1-832c-d0f108fc18e8)
It occurred in the pre-processing process, so it doesn't go to step 2. If you need it, I can give you the wav file that I preprocessed.

**Comment by rinechran** [comment]
![image](https://github.com/erew123/alltalk_tts/assets/15512801/af51e997-2aea-4e34-a484-5541bc7300ba)

**Comment by erew123** [comment]
@rinechran Please could you send me the actual diagnostics log file as I need to look at your python environment

**Comment by rinechran** [comment]
```(venv-tts) ➜  alltalk git:(main) ✗ python diagnostics.py

Select a requirements file to check against (or press Enter for default 'requirements.txt'):

1. requirements_other.txt
2. requirements_finetune.txt
3. requirements_nvidia.txt

Enter the number of your choice: 2

OS Version: Linux #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2
OS Ver note: (Windows 11 will say build is 10.x.22xxx)
System RAM: 48.05 GB available out of 62.70 GB total
Disk:  Drive: /dev/nvme1n1p2 | Total: 937.33 GB | Used: 246.75 GB | Free: 642.90 GB | Type: ext4
Disk:  Drive: /dev/loop0 | Total: 0.00 GB | Used: 0.00 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop3 | Total: 0.06 GB | Used: 0.06 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop4 | Total: 0.06 GB | Used: 0.06 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop5 | Total: 0.07 GB | Used: 0.07 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop6 | Total: 0.07 GB | Used: 0.07 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop8 | Total: 0.26 GB | Used: 0.26 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop9 | Total: 0.34 GB | Used: 0.34 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop11 | Total: 0.49 GB | Used: 0.49 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop12 | Total: 0.09 GB | Used: 0.09 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop13 | Total: 0.01 GB | Used: 0.01 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop15 | Total: 0.04 GB | Used: 0.04 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/nvme1n1p2 | Total: 937.33 GB | Used: 246.75 GB | Free: 642.90 GB | Type: ext4
Disk:  Drive: /dev/loop16 | Total: 0.00 GB | Used: 0.00 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/nvme1n1p1 | Total: 0.50 GB | Used: 0.01 GB | Free: 0.49 GB | Type: vfat
Disk:  Drive: /dev/nvme0n1p1 | Total: 1832.70 GB | Used: 440.80 GB | Free: 1298.73 GB | Type: ext4
Disk:  Drive: /dev/loop17 | Total: 0.01 GB | Used: 0.01 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop18 | Total: 0.04 GB | Used: 0.04 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop14 | Total: 0.26 GB | Used: 0.26 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop7 | Total: 0.30 GB | Used: 0.30 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop1 | Total: 0.30 GB | Used: 0.30 GB | Free: 0.00 GB | Type: squashfs
Disk:  Drive: /dev/loop2 | Total: 0.49 GB | Used: 0.49 GB | Free: 0.00 GB | Type: squashfs

GPU Information: Sat Mar 16 12:13:42 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:09:00.0 Off |                  Off |
|  0%   57C    P2             252W / 450W |   7867MiB / 24564MiB |     97%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1323      G   /usr/lib/xorg/Xorg                            9MiB |
|    0   N/A  N/A      1403      G   /usr/bin/gnome-shell                         10MiB |
|    0   N/A  N/A   2776643      C   python3                                    7862MiB |
+---------------------------------------------------------------------------------------+

Port Status: Port 7851 is available.

CUDA Working: Success - CUDA is available and working.
CUDA_HOME: N/A
Cublas64_11 Path: Not found in any search path directories.

Torch Version: 2.2.1+cu121
Python Version: 3.10.12
Python Executable: /mnt/ssd/project/alltalk/venv-tts/bin/python
Conda Environment: N/A

Python Search Path:
  /mnt/ssd/project/alltalk
  /usr/lib/python310.zip
  /usr/lib/python3.10
  /usr/lib/python3.10/lib-dynload
  /mnt/ssd/project/alltalk/venv-tts/lib/python3.10/site-packages

Requirements file package comparison:
  gradio          Required: == 3.50.2        Installed: 3.50.2
  torch           Required: >= 2.1.0+cu118   Installed: 2.2.1
  torchaudio      Required: >= 2.1.0+cu118   Installed: 2.2.1
  TTS             Required: >= 0.22.0        Installed: 0.22.0
  faster-whisper  Required: >= 0.10.0        Installed: 1.0.1
  tqdm            Required: >= 4.66.0        Installed: 4.66.2
  pandas          Required: >= 1.5.0         Installed: 1.5.3

On Nvidia Graphics cards machines, if your Installed version of Torch and Torchaudio does
not have +cu118 (Cuda 11.8) or +cu121 (Cuda 12.1) listed after them, you do not have CUDA
installed for Torch or Torchaudio in this Python environment. This will cause you problems
with AllTalk and Finetuning. You may have to 'pip install' a new version of torch and
torchaudio, using '--upgrade --force-reinstall' with the correct version of PyTorch for
your Python environment.

Requirements file specifier meanings:
== Exact version              != Any version except          < Less than
<= Less than or equal to      >  Greater than                >= Greater than or equal to
~ Compatible release          ;  Environment marker          AND Logical AND
OR Logical OR

Diagnostic log created: diagnostics.log. A brief summary of results is displayed above on
screen. Please see the log file for more detail.

```

**Comment by rinechran** [comment]
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/14622233/diagnostics.log)

**Comment by erew123** [comment]
Hi @rinechran 

Please download tokenizer.py from here https://drive.google.com/file/d/13pg9IEJPWuW-_cHKK_T-AyKq2--ERp7q/view?usp=sharing and save it over the top of your existing tokenizer file.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/e6180290-ec45-4802-9e0f-c4a47aae17e5)

You will need to restart finetuning.py, which should resolve that base issue. 

Obviously you may have other issues to resolve and the instructions are on the menus or in the general documentation.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/4fe9347b-1467-4cc9-a9ce-2dc65a019c9a)

Thanks

**Comment by rinechran** [comment]
Step 1's problem has been resolved
But I found an error in step 2.language is: ja
Traceback (most recent call last):
  File "/mnt/ssd/project/alltalk/finetune.py", line 1348, in train_model
    config_path, original_xtts_checkpoint, vocab_file, exp_path, speaker_wav = train_gpt(language, num_epochs, batch_size, grad_acumm, train_csv, eval_csv, output_path=str(output_path), max_audio_length=max_audio_length)
  File "/mnt/ssd/project/alltalk/finetune.py", line 562, in train_gpt
    model = GPTTrainer.init_from_config(config)
  File "/mnt/ssd/project/alltalk/venv-tts/lib/python3.10/site-packages/TTS/tts/layers/xtts/trainer/gpt_trainer.py", line 504, in init_from_config
    return GPTTrainer(config)
  File "/mnt/ssd/project/alltalk/venv-tts/lib/python3.10/site-packages/TTS/tts/layers/xtts/trainer/gpt_trainer.py", line 79, in __init__
    self.xtts.tokenizer = VoiceBpeTokenizer(self.args.tokenizer_file)
  File "/mnt/ssd/project/alltalk/venv-tts/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 622, in __init__
    self.tokenizer = Tokenizer.from_file(vocab_file)
Exception: No such file or directory (os error 2)

**Comment by rinechran** [comment]
[metadata_train.csv](https://github.com/erew123/alltalk_tts/files/14622298/metadata_train.csv)
Maybe there's a problem with training tokenization

**Comment by erew123** [comment]
Hi @rinechran 

I've just tested through here and it has gone through fine:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/d42dcb05-4d5e-4227-b479-4de7c8a17d7d)

Did you resolve the issues on the Pre-flight checklist? As missing files will cause a "Exception: No such file or directory (os error 2)"

In your earlier image Cublas was not being detected and nor was the Base model. So please check you have resolved the issues on the Pre-flight check. The instructions are on the tabs as shown. Or can find instructions on the main page https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-important-requirements-cuda-118

![image](https://github.com/erew123/alltalk_tts/assets/35898566/79353d08-fb06-4f19-b4b8-671b6fa1c178)

Thanks

**Comment by erew123** [comment]
Hi @rinechran 

If you have further problems, please let me know and I will look at them if possible.

Thanks
