### ISSUE TITLE
Ja language finetune doesn't work, but En works. RecursionError and PermissionError.

### ISSUE THREAD

**Issue by Humppa124** [erew123/alltalk_tts#134]
**Describe the bug**
Japanese language finetuning doesn't work but English finetune works. I noticed there was already an issue about Ja language finetuning, but the errors and problems seem different so opened new one.

**To Reproduce**
Python finetune.py -> Step 1, whisper model small, Ja language, evaluation data 15, generate -> Step 2 -> Issue during step 2.

**Screenshots**
![kuva](https://github.com/erew123/alltalk_tts/assets/163950704/34b16e76-e538-425f-827f-f3335659b94f)
![kuva](https://github.com/erew123/alltalk_tts/assets/163950704/58fc7075-9af6-4f79-a529-c37a113b01be)

Last error in English: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

**Desktop (please complete the following information):**
AllTalk was updated: [19.3.2024]
Conda enviroment, custom install.
Windows 10

**Additional context**
Rebooted the PC to try to make sure there is no other processes that use Alltalk_tts files. To no avail. Clearing tmp-trn folder neither helps.

**Diagnostics log:**
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/14644508/diagnostics.log)

**Comment by erew123** [comment]
Hi @Humppa124 

You error message off a little early. Can you either re-run it or can you confirm to me on your dataset how many files whisper cut the audio files into?

Additionally, you say you have a custom python environment setup here? I notice you are running the files from a path that has a space in the name "c:\program files\......" I cant say how much of an issue this may be, as we are dealing with a variety of training scripts that I didnt write. What I can say, is that miniconda and conda dont like dealing with paths with a space in them.

e.g. https://www.reddit.com/r/learnpython/comments/x3h2zq/why_does_some_python_software_not_allow_white/

https://docs.anaconda.com/free/working-with-conda/reference/faq/#installing-anaconda

Would you like to test installing AllTalk in a folder path such as c:\alltalk_tts and having its environment built using the atsetup.bat utility, where the environment is installed directly below c:\alltalk_tts and see if that resolves the issue.

Thanks

**Comment by Humppa124** [comment]
Yeah apparently, doesn't like my audio files. Will open again if further issues arise. Thanks for reminding me about Conda not liking spaces in path.
