### ISSUE TITLE
my CUDA version won't show as 11.8 no matter what I do after using nvcc --version cmd.

### ISSUE THREAD

**Issue by deathtome1998** [erew123/alltalk_tts#138]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log".
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/14717195/diagnostics.log)

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
A clear and concise description of what the bug is. not sure if it's a bug so much as something being up with my system that I can't figure out

**To Reproduce**
Steps to reproduce the behaviour: you probably wouldn't be able to reproduce it but just in case I had installed CUDA 12.3 at somepoint. and after installing CUDA 11.8 and following the instructions to add it to the path variables and use nvcc --version to check the CUDA version I come back with for CUDA compilation tools. it says 12.3 still. I've tried to take my CUDA 12.3 install and put it in the recycle bin while working on finetuning, but that gave me something in the cmd line that said nvcc isn't a recognized command, bat file, and I think maybe one other thing. so after putting CUDA 12.3 back from the recycle bin it went back t saying that's the version it could find.

**Screenshots**
![image](https://github.com/erew123/alltalk_tts/assets/150640640/e4bbab44-45d5-465a-a4aa-165c10c7cfbf)

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date] I just installed alltalk today (3/21/2024) 
Custom Python environment: [yes/no give details if yes] not as far as I know. I don't think I've done anything because I wouldn't know how, but if one of my programs could customize it then maybe.
Text-generation-webUI was updated: [approx. date] is this something like sillytavern or the alltalk webpage that you connect to? if it's sillytavern, I'm on staging and the discord as far as I can tell is only announcing main branch updates, so not sure. if it's alltalk's I'd assume it's the same as when I installed it today. so (3/21/2024)

**Additional context**
I've tried to edit my environment variables multiple ways, (fingers crossed I didn't screw something up) but nothing worked. and don't ask me exactly what edits I made because I don't remember. still I come up with CUDA 12.3 everytime I run nvcc --version. hoping someone has an idea what's going on here.

**Comment by erew123** [comment]
Hi

So I can see you are running AllTalk as a standalone installation with its own Python environment (B:\local-ai-chat\alltalk_tts\alltalk_environment\env)

So the issue you have is that the Nvidia CUDA Development Toolkit 12.3 is in the Windows search path and potentially also you don't have the CUDA_HOME environment variable set. 

![image](https://github.com/erew123/alltalk_tts/assets/35898566/fee2cee6-eec6-444e-a256-fb5c439b6711)

So in this scenario, when your computer tries to find `nvcc` it is hunting through the Windows Path list of directories, in the above order. As `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin` is at the top of the list and contains `nvcc` its returning that version first.

You can either remove the listing of the `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin` or change it to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin` (temporarily if you wish) 

https://www.wikihow.com/Change-the-PATH-Environment-Variable-on-Windows

You will have to open a new command prompt for it to take the changes after you make the change.

Thanks
