### ISSUE TITLE
Cookie Blocker Causing Problems?

### ISSUE THREAD

**Issue by johnbenac** [erew123/alltalk_tts#142]
I'm training my second model. I have a cookie blocker on by default in my browser. Even though I cleared out my old training data, when I go to load the model, all I see is my nonexistent training data information, and I don't see the current data. It all has a data of a few weeks ago.

I go in and manually set the paths, and it works fine.

I think that rather than say: 

" - If you dont see multiple speaker reference files and you used more than 3 minutes of speech, try refreshing the page as it may not have loaded them correctly." 

You should say: 

" - If you dont see multiple speaker reference files and you used more than 3 minutes of speech, try refreshing the page as it may not have loaded them correctly. If that does not work, examing the contents of 'alltalk_tts\finetune\tmp-trn\training' directory and set the paths manually`."

Also, you know how lots of websites have little popups that tell you that you have a cookie blocker, and you should disable it for their site? Why don't you do that as well, if you can with Gradio, right when the user opens up the page the first time, and every step of the way. 

Also, you can probably have the program check if a cookie was set after trying to set it. 

So rather than just: 

"`setcookie(data)`"

you can do 

```
setcookie(data)
if getcookie(data)=data:
 pass 
else:
  raiseerror('your cookies aren't being set! Do you have a cookie blocker?')"
```

Or, you could just save all the information about the generated files in a file somewhere, and you access that file, instead of the cookies. Like how `alltalk_tts\finetune\tmp-trn\metadata_train.csv` is updated with information as the generation goes along. 

I'm attaching a screenshot that shows the incorrectly populating training data paths, my cookie blocker being on in the top right of the screen, the error in the terminal when it tries to load the old data (which was automatically populated by the gradio page) and the explorer and CMD window showing that the correct folder is indeed present, with the vocab.json and config.json present.

![image](https://github.com/erew123/alltalk_tts/assets/6036376/4bdda011-133f-4dbe-8775-be232f334a54)

It all worked splendidly once I set the paths manually!

**Comment by erew123** [comment]
Hi @johnbenac 

As it goes I've actually been working my way through Github documentation and next is updating various bits throughout parts of AllTalk. Your idea for listing cookie blockers sounds reasonable. The revision of Finetuning I put out the other week has a pre-flight checklist on the front page, so I could add a warning there with a bit more information for people. 

![image](https://github.com/erew123/alltalk_tts/assets/35898566/1c0ad72f-d31c-4bbf-abac-aec59ff13e00)

My intent has been to flesh out some areas of the Finetuning interface with clearer instructions/information, so Ill make a mental note to add this in.

Thanks for the suggestion
