### ISSUE TITLE
Feature request: I would like a bulk generator checkbox to also split on new lines.

### ISSUE THREAD

**Issue by Innomen** [erew123/alltalk_tts#147]
Feature request: I would like a bulk generator checkbox to also split on new lines.

Thank you :)

I'm trying to make my own audiobooks. (r/HFY)

**Comment by erew123** [comment]
Hi @Innomen 

Is this the same request as this https://github.com/erew123/alltalk_tts/discussions/140

Thanks

**Comment by Innomen** [comment]
That's a better idea than mine so long as the list includes new line or carriage return or whatever. Thanks again :)

**Comment by erew123** [comment]
Hi @Innomen 

As this request is already in the list, Im going to close this ticket. 

As a side note, Ive just updated AllTalk, so the bug with quotation marks in TTS generator is now fixed. 

Thanks
