### ISSUE TITLE
Impossible to install CUDA Toolkit - Docker

### ISSUE THREAD

**Issue by Fgabz** [erew123/alltalk_tts#148]
**Describe the bug**

Hello, I'm having issue installing CUDA 11.8 Toolkit. I'm using the docker image provided on the repo and runing it on runpod (I've tried other provider same problem). Each time I'm trying to install the the toolkit, I'm not able to install the nvidia driver 550. Does anyone got also this issue?

**Comment by erew123** [comment]
Hi @Fgabz 

I'm assuming you are installing it for Finetuning? 

I don't know Docker too well (someone else built that docker), however you may be able to run this `pip install nvidia-cublas-cu11` and then maybe restart the docker environment and it **may** work. If it does, there will be no need to install the CUDA 11.8 Toolkit. 

I'm going to be releasing a new update sometime soon and with that, attempt to get a new Docker built. 

Thanks

**Comment by Fgabz** [comment]
Yes the goal is for finetuning. I'm going to try this, I'll let you know.

**Comment by erew123** [comment]
Hi @Fgabz 

Correction, these are needed:

`pip install nvidia-cublas-cu11 nvidia-cudnn-cu11`

`export LD_LIBRARY_PATH=`python3 -c 'import os; import nvidia.cublas.lib; import nvidia.cudnn.lib; print(os.path.dirname(nvidia.cublas.lib.__file__) + ":" + os.path.dirname(nvidia.cudnn.lib.__file__))'`

**Comment by Fgabz** [comment]
All good @erew123 now it works ! thanks !
