### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by Innomen** [erew123/alltalk_tts#149]
[AllTalk Startup] DeepSpeed Detected
[AllTalk Startup] Activate DeepSpeed in AllTalk settings
[AllTalk Model] XTTSv2 Local Loading xttsv2_2.0.2 into cpu
ERROR:    Traceback (most recent call last):
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\starlette\routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "E:\alltalk_tts\alltalk_environment\env\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\alltalk_tts\tts_server.py", line 132, in startup_shutdown
    await setup()
  File "E:\alltalk_tts\tts_server.py", line 177, in setup
    model = await xtts_manual_load_model()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\alltalk_tts\tts_server.py", line 248, in xtts_manual_load_model
    model.load_checkpoint(
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\TTS\tts\models\xtts.py", line 771, in load_checkpoint
    checkpoint = self.get_compatible_checkpoint_state_dict(model_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\TTS\tts\models\xtts.py", line 714, in get_compatible_checkpoint_state_dict
    checkpoint = load_fsspec(model_path, map_location=torch.device("cpu"))["model"]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\TTS\utils\io.py", line 54, in load_fsspec
    return torch.load(f, map_location=map_location, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\torch\serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\alltalk_tts\alltalk_environment\env\Lib\site-packages\torch\serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

ERROR:    Application startup failed. Exiting.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.

**Comment by erew123** [comment]
Hi @Innomen 

Youve not given me much to go on as to how you got to this point. e.g. have you updated? did you git pull? Did you re-run the requirements with atsetup (Standalone > Option 1)?

Either way, "PytorchStreamReader failed reading zip archive: failed finding central directory" suggests your model files in your models folder is corrupted in some way. 

You may wish to re-name the `xttsv2_2.0.2" folder to a `xttsv2_2.0.2.old` and let it download a fresh copy of the model files and confirm it works at that.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/ef9aec21-2f22-4f6f-a548-fed939ed26f6)

You should have the following files and they should be the sizes shown:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/b6b43caf-16d1-4114-ad9b-da28eae6e3e4)

Thanks

**Comment by Innomen** [comment]
I couldn't make update work at all so I started from scratch. This is the behavior of a fresh install.

**Comment by Innomen** [comment]
You were right about file sizes. The model.pth was 22 megs, I copied the 1gb one from my old install folder, and now it will launch. 

I couldn't ever generate a diagnostics file until after I copied over the model file:

   8) Generate a diagnostics file

   9) Exit/Quit

Enter your choice: 8
The input line is too long.

E:\alltalk_tts>

Also I'm using the zip, not git clone.
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/14797668/diagnostics.log)

Seems like it's working now.

I think for some reason it wasn't downloading the model file? If I encounter any other issues I'll pester you. Thanks for pushing the update.

**Comment by erew123** [comment]
Hi @Innomen 

Great glad its sorted. The only other time I've seen this behaviour is when Huggingface, where the model is downloaded from, has outages or problems. So its likely to be related somehow to internet connectivity type behaviour. Its a rare occurrence, but probably something I should add an entry in the help section for.

Thanks
