### ISSUE TITLE
Folder path with space in it doesnt handle error well

### ISSUE THREAD

**Issue by johnbenac** [erew123/alltalk_tts#159]
If I try to run atsetup.bat by clicking on it, and it is in a parent folder (or one of it's folders in the path has a space in it) and try to install it from the menus that are presented when running atsetup.bat,  then it quits out immediately without showing the user what the error is. Only when I run atsetup.bat from the cmd window do I see the error where it tells me that there is a problem with conda running in paths with spaces in the folder names. 

Is there some way to make it so that it shows the user what the error is when they click on atsetup.bat? as opposed to users who run atsetup.bat from a cmd window?

**Comment by erew123** [comment]
Hi @johnbenac 

I had already made reference to this in the Quick setup instructions:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/c424bc38-fbaa-4c06-945d-b262d8bcc566)

and also in the help section:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/d69d7534-0ac4-4592-8dfb-8eadc1cb5f1e)

Although it was difficult to code/test, both atsetups will now fail to start/run if there is a space in the path and give the user a clear error message:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/5a46b65f-1801-498e-ad16-da9645684685)

Hopefully that will clear this up for people in future.

Thanks

**Comment by johnbenac** [comment]
hey great! Docs are great, and I should read them more than I do. Although
sometimes, some people... don't read the instructions!

I hope that this little change increases adoption and reduces friction for
some so that more people enjoy this great product.
