### ISSUE TITLE
Add torch in PATH for docker environment

### ISSUE THREAD

**Issue by Fgabz** [erew123/alltalk_tts#161]
Just a quick note for people like me using docker environment (typically when you use service such as runpod/jarvislabs)

While trying to finetune the model, I encountered this error:

`Could not load library libcudnn_ops_infer.so.8` 

To fix it, you need to add torch to the PATH like this:

in my case 
`export LD_LIBRARY_PATH=/home/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/lib:$LD_LIBRARY_PATH`

and the finetuning in step 1 should work!

ref => https://github.com/SYSTRAN/faster-whisper/issues/516

**Comment by Fgabz** [comment]
Yes I'm using it with text-web-ui and it's IN ADDITION of what's already in the documentation you've made

**Comment by erew123** [comment]
@Fgabz Great! Thanks for letting me know. Ill look to add this to the instructions at some point. 

Ill close the ticket for now. 

Thanks
