### ISSUE TITLE
Can you do an inference demo on Huggingface?

### ISSUE THREAD

**Issue by Excurl** [erew123/alltalk_tts#162]
As s standalone..

**Comment by erew123** [comment]
Hi @Excurl 

Its not really a singular interface, its a collection of interfaces, some based on gradio, some based on HTML and and more than anything else its the built in API with the integration to other existing things (text-gen-webui, sillytavern, kobold etc). OR the flexibility to use the API with anything you personally want to, so its not really something that would fit or more specifically, work on Huggingface.

On the flip side of that, if its something you will just want to explore in a more simple way, I'm trying to get a google colab up and running. So when that is working, that would give people a simpler opportunity to take a look around it and trial without any install.

Thanks
