### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by bkutasi** [erew123/alltalk_tts#168]
I don't have any issues with this amazing piece of software, so I just wanted to say thank you. I love how you take the more traditional “manual” approach and put actually useful things in the readme, write down everything in detail, it clearly shows that you're not just duck taping everything together on the fly.
The installation was also seamless, which is quite unique with small projects in my experience. The standalone edition runs very smoothly on my 10+ year old laptop(frontend), while usually gradio based projects have troubles with performance.
Good job!

**Comment by erew123** [comment]
Hi @bkutasi 

Thanks that really kind! I'm not sure about the duck taping, maybe I just have a LOT of duck tape haha! I guess I have a mantra to **try** make things simple and if there's an issue/problem either code around it or document it. Much easier than writing the same response 20x to 20x people or telling people to go look through a 50+ entry thread to try find an answer.

All the best!
