### ISSUE TITLE
finetuning name wrong: voice.json -> vocab.json

### ISSUE THREAD

**Issue by rktvr** [erew123/alltalk_tts#17]
Just completed my first finetuned model and found this.
In the finetuning UI, in the "What to do next" tab it says:
`In the folder /finetune/tmp-trn/training/XTTS_FT(date here)/ you will find your best_model.pth, config.json and voice.json (also the last epoch training best_model_xxx.pth)`

"voice.json" is wrong, it should be "vocab.json".

super minor but someone might think they did something wrong if they can't find it.

**Comment by erew123** [comment]
Pfffff... 6 hours writing documentation between the application, the github and the built in documentation... checking it through, making sure it works correctly, formatting it nicely, spelling mistakes.... 

I was bound to miss one! haha

Thanks for letting me know, Ill sort it. I think I missed another one on the front page too!

**Comment by erew123** [comment]
Corrected now! Thanks. Hope you're enjoying it/finding it generally works well! Have a good Christmas! (or however you celebrate the holidays)
