### ISSUE TITLE
Config page provides no way to load a fine-tuned model

### ISSUE THREAD

**Issue by Artem-B** [erew123/alltalk_tts#171]
https://github.com/erew123/alltalk_tts/blob/fff01107c89cea9e7f0405e247da0f39637dc957/system/at_admin/at_settings.html#L249

Similarly there's no way to select finetuned model via SillyTavern extension.

If there's an existing way to load finetuned model and make it available in SillyTavern, I didn't manage to find it. Updating documentation would be helpful.

**Comment by erew123** [comment]
Hi @Artem-B 

I've had a quick look and it must be something that has changed. I know the way variables are saved changed in ST so maybe its related. Certainly AT is sending over to ST that a Finetuned model is available:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/66db51df-f5d9-4da6-9784-f001eea03f49)

Its just not opening the option in ST now. As I say Ill have to take a deeper dive on this one and try see what's occurring with that.

As a temporary workaround for you, as long as you have the Finetuned model stored it the `trainedmodel` folder, it should be detected on AllTalk startup:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/b40cf211-a3dd-4d90-aa97-a3b73ed60543)

In a command prompt/terminal, you can manually force a load of the model with:

`curl -X POST "http://127.0.0.1:7851/api/reload?tts_method=XTTSv2%20FT"`

That would at least get you 80% of the way there. 

As I say, Ill have to take a look at what ST is or isnt doing that stopping it presenting the option on the dropdown list.

Thanks

**Comment by erew123** [comment]
Hi @Artem-B 

I managed to figure what it was and have fixed it:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/21165a70-f46a-440b-ac72-890c03e57ba1)

If you go here: https://github.com/erew123/alltalk_tts/blob/main/system/st_files/alltalk.js and click the download button:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/d3b574e3-1f8e-4613-871c-ce46d58f1ffa)

And you will need to save that file over the top of `\SillyTavern\public\scripts\extensions\tts`

![image](https://github.com/erew123/alltalk_tts/assets/35898566/22f4097c-b852-482a-970b-6edd3370e8fe)

All should be working! Ill have to send a PR over to ST to get it updated there at some point.

Thanks

**Comment by Artem-B** [comment]
https://github.com/erew123/alltalk_tts/blob/fff01107c89cea9e7f0405e247da0f39637dc957/system/st_files/alltalk.js#L284

Looks like we're comparing with a string 'true' instead of a boolean true here.

**Comment by Artem-B** [comment]
I can confirm that `XTTSv2 FT` is now visible in ST, and that finetuned model gets loaded when it's selected.
