### ISSUE TITLE
Feature request: Compatiblity with Home Assistant using Wyoming protocol

### ISSUE THREAD

**Issue by rvsh2** [erew123/alltalk_tts#175]
Hi,

Adding wyoming protocol:
https://github.com/rhasspy/rhasspy3/blob/master/docs/wyoming.md

would give this project real world usage.

This will expand user base a lot. Many people use Home Assistant but for now the only way to use TTS is Piper which is limited for many languages due to lack of trained models.

If you could make it work with Home Assistant that would be great feature.

Best regards

**Comment by erew123** [comment]
Hi @rvsh2 

Ill take a note of it and see where I get to. I have quite a long list of things Im on with at the moment (not just the features request list). That aside I have been asked for HA integration already and I am intending on adding a potential OpenAI TTS API to AllTalk, which would make it compatible with a HA addin  https://github.com/erew123/alltalk_tts/discussions/152

Ill note this in the [features request list](https://github.com/erew123/alltalk_tts/discussions/74) however.

Thanks.
