### ISSUE TITLE
Documentation refers to ./start_finetuning.sh but this file does not exist

### ISSUE THREAD

**Issue by Xyem** [erew123/alltalk_tts#177]
Looking to try out finetuning the model on Linux and the documentation refers to `./start_finetuning.sh` but this file does not exist.

**Comment by erew123** [comment]
Hi @Xyem 

Are you running this as a standalone installation or part of text-gen-webui? And if its a standalone, did you run the `atsetup.sh` as that's what creates the `start_finetuning.sh` file.

Thanks

**Comment by Xyem** [comment]
Standalone and I manually created the environment (I think there is a specific reason I didn't use `atsetup.sh` but I can't recall what that was at the moment). Thanks for explaining why it is missing.

I did manually start the finetune (via `python finetune.py`) but then found out it starts a webui that you can't access remotely. I modified the script so I could.. and then found out finetuning requires 14GB of VRAM and I only have 12GB, so I can't finetune anyway. Might be worth adding a note about the 14GB requirement to the documentation? It's not mentioned in the "you will need" list.

**Comment by erew123** [comment]
Hi @Xyem 

Yes unfortunately Linux doesn't expand the memory over into system ram, unlike windows. 

Re-documentation, I understand what you are saying. There are just so many places to try notify/document these things. I am working on a different version of AllTalk, so will look to have all the additional things in the documentation then. Ill add a quick note into the current readme though.

Thanks
