### ISSUE TITLE
How to add support for hindi language 

### ISSUE THREAD

**Issue by iamjamilkhan** [erew123/alltalk_tts#178]
Hey xttsv2 officially support hindi but not alltalktts is there any way to make it support hindi as well ?

**Comment by erew123** [comment]
Hi @iamjamilkhan 

I didn't see any official listing for Hindi https://docs.coqui.ai/en/latest/models/xtts.html#languages and Coqui have made no official listing of Hindi that I can find.

I have however hunted a bit further, I can see it mentioned here https://huggingface.co/coqui/XTTS-v2

It looks like Hindi is a late & undocumented addition to the XTTSv2 **2.0.3** model (AllTalk as standard downloads the 2.0.2 model, which doesn't have Hindi Support).

So, I have added Hindi in the relevant places throughout AllTalk and tested with the 2.0.3 model. There are problems however, Coqui have **not** updated all their scripts to support Hindi (based on my testing).

![image](https://github.com/erew123/alltalk_tts/assets/35898566/9e721f6d-4092-4b87-9e82-7223670a4235)

The **XTTS Local** method will not work with Hindi. As such, if you want to use Hindi to generate TTS, you would have to:

1) Download the XTTS v2.0.3 model over the top of the v2.0.2 model. https://huggingface.co/coqui/XTTS-v2/tree/v2.0.3 (all files)
2) When AllTalk has loaded you would have to switch the endpoint to use API TTS or set it in the settings area: 
- `curl -X POST "http://127.0.0.1:7851/api/reload?tts_method=API%20TTS"`

![image](https://github.com/erew123/alltalk_tts/assets/35898566/f40146ab-fef8-4ca1-abfa-9850997b6903)
**restart required on changing the setting here**

I have no idea what limitations or issues there are or could be with Hindi support. I've done my best to set AllTalk to pass Devanagari script, but again, I have no idea what Coqui's scripts are/aren't doing with this.

You are welcome to update and give it a try, but please note the above requirements and limitations.

Thanks

**Comment by iamjamilkhan** [comment]
Thanks for a quick update brother i have downloaded 2.03 model and palaced in model folder however while starting app its automatically select the version 2.02 is there any way to change Path of folder

**Comment by iamjamilkhan** [comment]
![IMG_5254](https://github.com/erew123/alltalk_tts/assets/56718338/7753970c-022b-4099-b5c9-5aeb52101325)
After changing path to new folder it’s won’t start and encountering a error should i reinstall alltalktts with new model path ?

**Comment by iamjamilkhan** [comment]
Okay its worked after reinstalling it but still there is no hindi option to choose is there I’m missing any steps ? 
![IMG_5255](https://github.com/erew123/alltalk_tts/assets/56718338/8b8328ae-eb08-4f7f-a551-ab1d5f2313a7)

**Comment by iamjamilkhan** [comment]
![IMG_5256](https://github.com/erew123/alltalk_tts/assets/56718338/ee9c982d-1c38-4ab2-b9cb-578887f738a2)

**Comment by iamjamilkhan** [comment]
I have tried without default English input it’s converting tts but acent is still English is there any way to change language or select hindi maybe its work perfectly. I have tried with xttsv2 officials hugging demo its works without any issue

**Comment by iamjamilkhan** [comment]
![Uploading IMG_5257.png…]()

**Comment by erew123** [comment]
Hi @iamjamilkhan 

Did you update AllTalk with a git pull? https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-updating

![image](https://github.com/erew123/alltalk_tts/assets/35898566/49f54dfa-642f-48fc-880c-18091f3f6e92)

**Comment by iamjamilkhan** [comment]
Ohh i have installed using zip let’s me reinstall it

**Comment by iamjamilkhan** [comment]
After updating to latest version the hindi option appear but its won’t generating anything even with another language i have tried with all model api local,local xtts and api tts seem sometimes broken please check your side

**Comment by iamjamilkhan** [comment]
Uploading RPReplay_Final1713588799.mp4…

**Comment by erew123** [comment]
Hi @iamjamilkhan 

No probs, looked like I introduced a bug. Ive resolved that now so just perform another git pull and all should be good. Just make sure to ensure you:

1) have the 2.0.3 model
2) use API TTS mode.

Regarding the TTS generator, I don't personally read or write Devanagari script. The TTS generator splits on a period/full stop to delimit the sentences. My best guess is that in Devanagari script you don't use a period/full stop to delimit sentences. As such I doubt the TTS generator will split correctly, if at all. 

If you can provide me a simple, This is the character that Hindi uses to split sentences, then I can attempt to introduce it, however, remember I have no understanding of Hindi and Devanagari script. so testing is also hard for me to confirm if things work correctly as/when it would split.

Thanks

**Comment by iamjamilkhan** [comment]
thanks alot for such supporting you are great brother have a wonderful day and will gonna donate for it sure ❤️❤️❤️❤️and will let’s you know if found anything doubtful

**Comment by batya86** [comment]
How can I help you to add Azerbaijani language? I don't understand codes but I want Azerbaijani language in the software. If there is anything I can do, please tell me.
