### ISSUE TITLE
talk conten "" **

### ISSUE THREAD

**Issue by kalle07** [erew123/alltalk_tts#184]
(extension in text-web-ui)
is it possible to avoid talking content
in "..." and in *...* 
sometims is ok, but mostly cost time and its better i read it (that are most thoughts of the character) and better i only have the voice thats speaks to me  :)

**Comment by erew123** [comment]
Hi @kalle07 

The only delimiter I know of to split the narrated vs spoken is asterisk `*`. Please see here for an explanation https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-a-note-on-character-cards--greeting-messages

I can probably set content between asterisks to be dropped. Would suffice? Ive not seen anything that is starting/ending with `...` before.

**Comment by kalle07** [comment]
oh i meant
* ... *   
i wrote it without a space between the * and the ...  than its deleted (automatic coded here on git)   ;)

yes that would be fine

**Comment by erew123** [comment]
Hi @kalle07 

No probs. I've checked and this is already in the [features request list](https://github.com/erew123/alltalk_tts/discussions/74) as **Silent narrator option (don't speak anything detected as narrator)**

Ill be looking at it for the next larger release soon.

Thanks
