### ISSUE TITLE
Install scripts uses >= and currently installs pytorch 2.3.0 breaking compatibility with DeepSpeed

### ISSUE THREAD

**Issue by kaminoer** [erew123/alltalk_tts#185]
**Describe the bug**
atsetup.bat has the following line `pip install torch>=2.2.1+cu121 torchaudio>=2.2.1+cu121 --upgrade --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu121` 
This installs torch 2.3.0 and breaks compatibility with DeepSpeed which requires torch 2.2.1

**To Reproduce**
Run atsetup.bat and perform a fresh standalone install.

**Desktop (please complete the following information):**
AllTalk was updated: 24.04.2024
Custom Python environment: no
Text-generation-webUI was updated: not using

**Additional context**
https://github.com/erew123/alltalk_tts/blob/efeb2e67e0ae8fb5c3afb70f3f89d75cdaa4b478/atsetup.bat#L397

**Comment by erew123** [comment]
Hi @kaminoer 

Damn, they are really firing new point revisions of PyTorch out at the moment. Annoying as each revision requires a whole new compilation of DeepSpeed which is a 30-60 minute job (plus changing over the code in AllTalk).

For now I will lock down the version to 2.2.2 of Pytorch which should maintain compatibility.

If you specifically want to force a downgrade to that version, you can git pull the update to AllTalk and re run the setup.

or you can manually run this in the Python environment:

```
pip install torch==2.2.2+cu121 torchaudio>=2.2.2+cu121 --upgrade --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu121
```

Thanks for the info
