### ISSUE TITLE
Streaming TTS in SillyTavern/Ollama

### ISSUE THREAD

**Issue by baconsplit** [erew123/alltalk_tts#186]
**Describe the request**
I am looking for a way to have AllTalk generate a streaming TTS voice while my LLM in SillyTavern is still generating the output text. Is that possible?
It would reduce the complete generation time of text generation and TTS. Right now AllTalk waits for my LLM/SillyTavern to finish generating text, and then first begins to generate a voice.

**To Reproduce**
Have SillyTavern with local LLM via Ollama and local AllTalk setup, hit "generate" and watch how the text generation is output in a stream but the TTS begins generation first after the text gen stream is done.

**Desktop (please complete the following information):**
AllTalk was updated: 25.04.24
Custom Python environment: default installation on windows
Text-generation-webUI was updated: using Ollama

**Additional context**
Sorry if this is the wrong place to ask for help.

**Comment by baconsplit** [comment]
Alright understood. I already suspected a limitation by ST itself, because under the AllTalk option there is no way to enable streaming. But I thought asking here might not hurt.

I will rather watch the development of ST then, AllTalk is working here as expected. Its pretty good btw :)

**Comment by erew123** [comment]
No harm in asking! :)

If I had no coding to do myself, then I might take a look at the ST code, but its not code I know in any way and I am deep deep in a lot of code currently for v2 of AllTalk, so Im not looking at anything else for a long long time.

Thanks
