### ISSUE TITLE
Setting application to 0.0.0.0 to allow application to work behind NAT

### ISSUE THREAD

**Issue by caseygoodrich** [erew123/alltalk_tts#187]
Is your feature request related to a problem? Please describe.
The application currently returns URLs with 0.0.0.0 as the hostname

Describe the solution you'd like
I would like the application to provide URLs with a more explicit and predictable hostname or IP address without hardcoding the IP address, making it clear how users can access the application. This could involve configuring the application to use a specific hostname or IP address rather than 0.0.0.0 by default.

Describe alternatives you've considered
An alternative solution could be to update the application's documentation to clarify the default hostname usage and provide instructions for users on how to access the application. However, this may not fully address the confusion and issues caused by the default hostname.

If you are behind a NAT setting the real IP will not work.  Can the application just use the IP you are coming from and append.

http://0.0.0.0:7851/audio/api_preview_voice.wav?t=1714050681957

vs 

http://192.168.1.10:7851/audio/api_preview_voice.wav?t=1714050681957

**Comment by erew123** [comment]
Hi @caseygoodrich 

You may wish to see the Breaking Changes for the next major AllTalk revision https://github.com/erew123/alltalk_tts/issues/166

I think this should answer your question.

Thanks
