### ISSUE TITLE
Small bug -> Grad accumulation can't be set lower than 2

### ISSUE THREAD

**Issue by RenNagasaki** [erew123/alltalk_tts#191]
**Describe the bug**
If you change Grad accumulation, you can't change it back to 1 minimum of the slider seems to be 2.

**To Reproduce**
Move the slider to more than 1

**Screenshots**
![image](https://github.com/erew123/alltalk_tts/assets/10595885/c4c6734d-2924-4624-988f-cd445d986eda)

Kind regards.

**Comment by erew123** [comment]
Hi @RenNagasaki 

No probs. That's been fixed, you can git pull if you need.

Thanks
