### ISSUE TITLE
Does ALLtalk autoupdates itself ? 

### ISSUE THREAD

**Issue by Talhavaival1** [erew123/alltalk_tts#196]
**Describe the bug**
I was using the Docker container you provided recently for Nivida GPUs  on 20th April which was working , however now when I run ALL talk tts it does not run properly, it says Github updated 28 April, I wanted to ask does the ALL talk auto updates even if it is currently running in a Docker container of image I built on 20th April.

**Comment by erew123** [comment]
Hi @Talhavaival1 

I'm mid-process updating AT to a new version which **should** have fully tested docker support and google colab support, however thats quite a way down the line as there's a lot of new code with other things Im doing. So Im just stating that to say from the word go that, whats currently on the github for docker, Im not exactly supporting as a docker (there's a statement on the main page of github about that).

That aside and to answer your question, no AllTalk will not pull any updates automatically. The message on the boot screen is purely an informational check that is there to let people know if there have been any updates to the commits list https://github.com/erew123/alltalk_tts/commits/main/

Hope that clarifies.

Thanks

**Comment by Talhavaival1** [comment]
Thanks Appreciate the help  @erew123 .
