### ISSUE TITLE
Numpy version lock breaks install

### ISSUE THREAD

**Issue by sammcj** [erew123/alltalk_tts#2]
Just tried out the extension (great work!), and found that the locked version on numpy broke the dependency tree:

```
INFO: pip is looking at multiple versions of tts to determine which version is compatible with other requirements. This could take a while.
Collecting TTS>=0.21.3 (from -r requirements_nvidia.txt (line 4))
  Downloading https://pip/index/tts/TTS-0.21.3-cp310-cp310-manylinux1_x86_64.whl (942 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 942.6/942.6 kB 696.6 MB/s eta 0:00:00
ERROR: Cannot install -r requirements_nvidia.txt (line 4) and numpy>=1.24.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy>=1.24.4
    tts 0.22.0 depends on numpy==1.22.0; python_version <= "3.10"
    The user requested numpy>=1.24.4
    tts 0.21.3 depends on numpy==1.22.0; python_version <= "3.10"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

Removing the >=1.24.4 from the requirements_nvidia.txt however fixed the issue:

```
(venv) root@textgen:/app/extensions/alltalk_tts# sed -i 's/numpy>=1.24.4/numpy/g' requirements_nvidia.txt

(venv) root@textgen:/app/extensions/alltalk_tts# pip install -r requirements_nvidia.txt
WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: https://pip/index/
Requirement already satisfied: numpy in /app/venv/lib/python3.10/site-packages (from -r requirements_nvidia.txt (line 1)) (1.22.0)
....
Installing collected packages: zipp, pandas, importlib-metadata, TTS
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
  Attempting uninstall: TTS
    Found existing installation: TTS 0.20.6
    Uninstalling TTS-0.20.6:
      Successfully uninstalled TTS-0.20.6
Successfully installed TTS-0.22.0 importlib-metadata-7.0.0 pandas-1.5.3 zipp-3.17.0
```

**Comment by erew123** [comment]
Ahh I see, you're on a python 3.10 version. I just went with what a brand new/fresh install of text-gen gave me. But I cant see dropping the numpty version down if that's all TTS is requesting on that version! So I've changed it!

Thanks for the heads up :)

I've got a few more small updates to make to it sometime with the narration option, just to clear up how it decides what's narrator/character when the AI decides not to use quotes or asterisks... so there may be that update in a few days.

If you find anything else, drop me a message back! Thanks!

**Comment by sammcj** [comment]
Yeah Python 3.10 is really old and not ideal but it's what the official textgen container image uses unfortunately.

Thanks again 😄

**Comment by erew123** [comment]
Fyi, the latest version is up! The whole text filtering engine and narration/character code is rebuilt, working in what looks like a really crazy way, but, as far as I have tested, it works much better and its resulting in cleaner TTS output as there are no strange characters slipping through that it tries to vocalise (at least as far as I've found in around 150 ish text generations). So you may want to update.

**Comment by sammcj** [comment]
Nice work! Thanks for letting me know, I'll have to give it a go.
