### ISSUE TITLE
chat with character

### ISSUE THREAD

**Issue by kalle07** [erew123/alltalk_tts#204]
is it possible to avoid that ...

ok i try to explane

if ich choose a character, i pic one and instantly the last chat is loaded or the new chat is loadet and if somewhat is there to talk it starts to talk ... so i must wait 1min to choose the next character ^^

give it a possibilitiy if a text is loooong and it talks a lot to break that, not only stop(II)

thx

**Comment by erew123** [comment]
@kalle07 

The next version of AllTalk will have a stop function to break current TTS generation. However, I cannot stop applications like Text-generation-webui, SillyTavern or Kobold sending text off for TTS generation. This is a function of those applications, not AllTalk. AllTalk just generates whatever is sent to it and that is controlled by the main applications.

Thanks
