### ISSUE TITLE
ImportError: cannot import name 'field_validator' from 'pydantic

### ISSUE THREAD

**Issue by TheLocalLab** [erew123/alltalk_tts#21]
Please generate a diagnostics report and upload the "diagnostics.log".

**Describe the bug**
Apparently, the "field_validator" has been removed in Pydantic V2 and couldn't be imported in the tts_server.py file.

**To Reproduce**
Fresh install of the AllTalk extension, while loading the extension

**Screenshots**
![Line 650](https://github.com/erew123/alltalk_tts/assets/142870531/1231c569-21a3-4621-8bc5-7d6b599359b1)
![Line 25](https://github.com/erew123/alltalk_tts/assets/142870531/e51b691e-3e58-4970-9d78-05a26db84049)

**Text/logs**
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Closing server running on port: 7860
2023-12-24 17:31:30 INFO:Loading the extension "gallery"...
2023-12-24 17:31:30 INFO:Loading the extension "alltalk_tts"...
[AllTalk Startup] Coqui Public Model License
[AllTalk Startup] https://coqui.ai/cpml.txt
[AllTalk Startup] Old output wav file deletion is set to disabled.
[AllTalk Startup] Checking Model is Downloaded.
[AllTalk Startup] TTS version installed: 0.21.3
[AllTalk Startup] TTS version is up to date.
[AllTalk Startup] All required files are present.
[AllTalk Startup] TTS Subprocess starting
[AllTalk Startup] Readme available here: http://127.0.0.1:7851
Traceback (most recent call last):
  File "C:\Programs\text-generation-webui\extensions\alltalk_tts\tts_server.py", line 25, in <module>
    from pydantic import field_validator
ImportError: cannot import name 'field_validator' from 'pydantic' (C:\programs\text-generation-webui\installer_files\env\Lib\site-packages\pydantic\__init__.cp311-win_amd64.pyd)
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Startup] Warning TTS Subprocess has NOT started up yet, Will keep trying for 120 seconds maximum. Please wait.
[AllTalk Shutdown] Received Ctrl+C, terminating subprocess
2023-12-24 17:33:51 ERROR:Failed to load the extension "alltalk_tts".
[AllTalk Shutdown] Received Ctrl+C, terminating subprocess
[AllTalk Shutdown] Received Ctrl+C, terminating subprocess

**Desktop (please complete the following information):**
AllTalk was updated: 12/24/23
Custom Python environment: Python version = 3.10.9
Text-generation-webUI was updated:

**Additional context**
Was able to solve the issue by going into the tts_server.py file in the alltalk_tts extension folder and change "field_validator"
on lines 25 and 650 to "validator". Save the file and restarted Ooba and the extension. Alltalk loaded successfully.

FYI: Not sure if it this is relevant but when I initially ran "pip install -r requirements_nvidia.txt", it installed pydantic version 2.5.1. I uninstalled it and installed the 2.5.0 version instead, then applied the solution above.

**Comment by erew123** [comment]
I'm going to guess you are running DeepSpeed v11.1 too? 

11.2 has a fix in it for pydantic.

https://github.com/erew123/alltalk_tts/releases/tag/deepspeed

Though I have to admit, I've used 2.50. and 2.5.3 and not 2.5.1, so Ill have to check that.

Have a good Christmas.

**Comment by erew123** [comment]
I've managed to drop a bit of the code without affecting it. So it will now work with Pydantic 1.10.3 and Ive changed the requirements file, but Im not forcing it to downgrade. If for any reason you get other issues with pydantic, you can downgrade it with `pip install pydantic==1.10.13`

You would need to update AllTalk again https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-updating
