### ISSUE TITLE
AllTalk Standalone does not start

### ISSUE THREAD

**Issue by PopHorn** [erew123/alltalk_tts#210]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
Standalone Install in Windows 10 - start_{youros}.bat opens and closes instantly and AllTalk doesnt start

**To Reproduce**
Install and start any start_{youros}.bat

**Screenshots**
N/A

**Text/logs**
N/A

**Desktop (please complete the following information):**
AllTalk was updated: 9 May 2024
Custom Python environment: No idea what is that :(
Text-generation-webUI was updated: 9 May 2024

**Additional context**
I tried the fix from FAQ (removing spaces in the path) - did not work

**[SOLVED]**
File **svml_dispmd.dll** was missed in system32 windows 10 folder

**Comment by erew123** [comment]
Hi @PopHorn 

Im guessing you ran it from the command line and could see the error. Ive seen that kind of issue before, not with AllTalk specifically, but with batch files.

The SVML is "SVML Library for Intel(r) Compilers (thread-safe)" and something to do with the intel chipset on a system. I have no idea why it causes the issue with batch files, Ive never really looked into it. As long as you have it solved though, Ill close the ticket.

Thanks
