### ISSUE TITLE
Prune emojis from promt

### ISSUE THREAD

**Issue by bobcate** [erew123/alltalk_tts#224]
I'm using AllTalk as an extension for SillyTavern. When a character uses emojis in the response, the emojis are also sent to AllTalk and this messes up the voice generation, it tries to vocalize the emojis, failing miserably.

Please implement a solution to prune emojis from the prompt before processing the text.

Only thing about this subject I could find was in [this reddit post](https://www.reddit.com/r/LocalLLaMA/comments/18jwbkf/amica_02_released_now_has_binaries_for_windows/). It lists "Prune emojis from TTS" under bug fixes, so it should be possible to achive this.

**Comment by erew123** [comment]
Hi @bobcate 

You may want to try this and let me know if it solves it for you.

In your SillyTavern folder, go to the folder `\SillyTavern\public\scripts\extensions\tts` and open the file `alltalk.js` in a text editor of your choice. (take a copy of the file first if you just want a easy restore should something go funny. You can delete it after).

Go to line 769 at the bottom of the script:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/c6639d23-f28b-4808-9bf3-94ad1faa152f)

Change the word `standard` to `html`:

`'text_filtering': "standard",`

to

`'text_filtering': "html",`

Save the file and re-load SillyTavern.

That should strip them out.

Let me know if that works/has issues.

Thanks

**Comment by erew123** [comment]
Actually, it wont do it on Narrated text... give me a couple of minutes and Ill pop an update up. Though you will still need to change the setting in the SillyTavern alltalk.js file. Give me 10 ish minutes and Ill post an update to AllTalk.

**Comment by bobcate** [comment]
Thank you, that fixed it.
I guess, since that file belongs to SillyTavern, this is option that should be added by them.

**Comment by erew123** [comment]
Oh great! as long as that's sorted for you!

As for the alltalk.js file, its managed by myself. Ill be updating it at some point, more likely when I push out v2 of AllTalk in the next couple of weeks.

Thanks
