### ISSUE TITLE
Some SillyTavern TTS options are ignored

### ISSUE THREAD

**Issue by bobcate** [erew123/alltalk_tts#225]
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/15307532/diagnostics.log)

Some checkbox settings in "SillyTavern > Extensions > TTS" are ignored

Steps to reproduce:
1. Set up SillyTavern and AllTalk to work together
2. Go to "SillyTavern > Extensions > TTS", enable AllTalk
3. Check `Ignore *text, even "quotes", inside asterisks*` or `Skip codeblocks`
4. Promt character to respond with the formatting as above
5. Observe AllTalk as it ignores the checked boxes and still generates voice

Narrator voice is on. `Text Not Inside * or " is` setting doesn't matter, generates voice on both options.
Restarting everything after checking the boxes has no effect.

AllTalk installed, fresh: 14/05/2024
Custom Python environment: Just ran the setup.
Using standalone AllTalk.

**Comment by erew123** [comment]
Hi @bobcate 

![image](https://github.com/erew123/alltalk_tts/assets/35898566/dfbc7adc-b585-450f-a4a1-5d246c9e6722)
(This is how I have mine configured currently)

These settings actually managed/created by SillyTavern and decide what is or isn't passed to any TTS engine extensions, they are not specifically part of AllTalk.

The only one that is specifically used by AllTalk is "Pass Asterisks to TTS Engine".

For AllTalks narrator to function, it requires text to be sent over to it with with double quotes `"` for character spoken text, inside asterisks `*` for narrated portions, then any text that falls outside of those 2 options would be something you can choose with `Text Not Inside * or " is`

If those other functions are filtering out the double quotes or asterisks, then the AllTalk narrator wont be able to pick out the relevant parts.

`Text not inside` works in the following way:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/876e4c9c-d646-44dc-bae3-7b9a7ce3a39e)

So this is an example of a working configuration:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/eed30bca-6714-4f16-a66a-cd7e25836c43)

In later versions of AllTalk I will be adding an option for a silent narrator, but its not available yet.

As for what SillyTaverns other options do/dont strip out, I cannot say. You would have to look in the console `F12` and you can see TTS messages there. e.g. here is a TTS message in the console that is sent over AllTalk, As you can see SillyTavern sends it over with asterisks, which will define it as Narrated speech.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/c05bf464-9429-4876-be2a-117f70d8fd03)

![image](https://github.com/erew123/alltalk_tts/assets/35898566/9e9dc389-a2ee-445c-a920-410b0377313f)

Not sure if that answers your question or not?

Thanks

**Comment by bobcate** [comment]
Thank you for the detailed explanation.
Checking the browser console, regardless of the settings, SillyTavern still passes the kind of texts I mentioned in the first message.
I'll report this on SillyTavern's page.

**Comment by erew123** [comment]
@bobcate You're welcome to reference this ticket if there is something relevant that they need me to do in AllTalk later down the line and they can respond here.

Thanks
