### ISSUE TITLE
Containerized Docker Build Hits a Stopping Point

### ISSUE THREAD

**Issue by rodycaymond** [erew123/alltalk_tts#234]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
When trying to create a containerized build using the Standalone quick setup method, the server setup will hang indefinitely on an if statement in the script.py file at line 305-308

**To Reproduce**
Create a docker container that runs through the standalone quick setup instructions. I used a compose file with a Dockerfile for the build, and entrypoint.sh to execute the ./atsetup.sh and subsequently the ./start_alltalk.sh scripts.
I was able to circumvent this issue by commenting out lines 305-308 in the script.py script, and moving the remainder of the else blocks contents left to satisfy python's whitespace requirements. After doing this, the remainder of the server setup occurs and I am finally able to hit the server endpoints.

**Screenshots**

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: ~
Custom Python environment: no
Text-generation-webUI was updated: ~

**Additional context**
I would suggest just taking a look at the script.py file to ensure that lines 305-308 are executing their intentions. It seems like the only thing that if block does is print to the console and then skip the rest of the setup in the else blocks below.

**Comment by erew123** [comment]
Hi @rodycaymond 

Docker has been a pain in the butt and per the statement on the front page of Github, I didnt set that up. Needless to say that AllTalk 2 is on the way and it will operate in a somewhat different way, so Docker and Google colab should work fine with it. 

Will be hopefully within the week that I have a beta out, though I probably wont have tested it with docker or colab at that point. Hopefully will get a chance to not long after though and closer to release.

Thanks
