### ISSUE TITLE
Please help i can't make this tool work.

### ISSUE THREAD

**Issue by MadeaccountforTTS** [erew123/alltalk_tts#236]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
i can't launch the tool or make it work after installation , even after installing the requirements this is what i get in the image below.

**To Reproduce**
-

**Screenshots**
![TTS](https://github.com/erew123/alltalk_tts/assets/171390244/e4094186-a112-4d63-ac09-4fac7fcc7be9)

**Text/logs**
all visible in the picture above

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date]
Custom Python environment: [yes/no give details if yes]
Text-generation-webUI was updated: [approx. date]

**Additional context**
-

**Comment by erew123** [comment]
Hi

You havnt given me any details about how its installed or a diagnostics file. However Im guessing from the "E:\alltalk_tts" path that you have installed it as a standalone? And you used the atsetup.bat file to setup the AllTalk Python environment? And you are using start_alltalk.bat to start it?

Thanks

**Comment by erew123** [comment]
As shown in this video https://www.youtube.com/watch?v=AQYCccDRbaY

**Comment by MadeaccountforTTS** [comment]
> As shown in this video https://www.youtube.com/watch?v=AQYCccDRbaY

yes sir exactly like that

**Comment by erew123** [comment]
Im not sure how much you know about Python environments, but there is a quick explainer here "Understanding Python environments" https://github.com/erew123/alltalk_tts?#-help-with-problems

I would suggest that you first of all at the command prompt, in the alltalk folder, run `start_environment.bat` and see if that changes the command prompt as shown in  the above guide:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/bb385a78-deb4-4dac-b68c-ce4e7249ed81)

If so, please run `python diagnostics.py` for me and upload the `diagnostics.txt` file it generates, then we can look at your python environment and see if everything is installed correctly.

Its possible that your internet connect/the servers at Python went funny and it didnt download something it should have, so worst case, you can always run `atsetup.bat` and in the standalone menu,`Delete AllTalk's custom Python environment` and then `Purge the PIP cache` to make sure any corrupted files are removed from your pip cache, then finally run the `Install AllTalk as a Standalone Application` as that would pull everything fresh and re-set everything up.

**Comment by MadeaccountforTTS** [comment]
its my first time ever installing python in my computer so i don't think i have a custom environement that conflicts . also when i run the start_environment.bat nothing happens cmd auto closes..

**Comment by erew123** [comment]
Great! Ill assume you are sorted and Ill close the ticket.

Thanks
