### ISSUE TITLE
MaryTTS Support

### ISSUE THREAD

**Issue by Subcode** [erew123/alltalk_tts#238]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add MaryTTS support so we can use this in HomeAssistant?

**Additional context**
https://www.home-assistant.io/integrations/marytts/
https://docs.coqui.ai/en/latest/marytts.html

**Comment by erew123** [comment]
Hi @Subcode 

This is already in the [Features Request list](https://github.com/erew123/alltalk_tts/discussions/74) well, at least as far as Home Assistant being able to use AllTalk.

Although I have not made any direct integrations with Home Assistant, nor tested this far, AllTalk v2, beyond its own API suite, has a OpenAI Speech compatible endpoint. 

Which means in theory.... it should mean you can use [OpenAI TTS Custom Component for Home Assistant](https://github.com/sfortis/openai_tts) 

That aside, Im not opposed to adding a MaryTTS endpoint, however I was considering writing a full AllTalk integration for Home Assistant, which I assume would be preferable?

Thanks
