### ISSUE TITLE
Feature request: model switching

### ISSUE THREAD

**Issue by rktvr** [erew123/alltalk_tts#24]
with finetuning now a possibility, would it be possible to hot-reload a model/select one without needing to restart ooba?
something like a dropdown, to select one of our finetuned models

**Comment by erew123** [comment]
What do you think it is... Christmas? 😄 Was finetuning not enough? haha

Multiple additional models might be complicated, the loader situation may get messy. Its not impossible, but Ill think around it. There are quire a few complexities to the loaders in the "multiple other models" scenario.

It would be relatively easy to do a "detect an extra model in this location and make an extra gradio radio box appear for that 1x model"... I think. But I am talking for 1x extra model in 1x location. Though still, Id need to think around that one. 

Would 1x extra model work? or are you looking at literally 2 to ??? extra models?

**Comment by rktvr** [comment]
Initially I thought it'd be like a model selector in Auto1111's stable diffusion webui I suppose.

> Would you train the same model over and over (different voices), so just need that 1x model.

Is that possible? So I can train a model with one voice, then use that finetuned model again with a different voice? If that's the case then I suppose a model selector may not be needed, depending on how much other voices effect the previous finetuning.

**Comment by erew123** [comment]
Ive just updated finetuning to not only compact your model, but also deal with all the model moving. Its creating a folder in the /models/ folder called `trainedmodel`, now that its standardised in some way, I should be able to do something with the gradio interface that looks for a model existing in that folder and if so, gives you an extra loader option. But Ive just spent my day on a load of other bits and Im sure Ive got something else to do. So Ill get there.. but give me time :)

If you do want to compact your existing model https://github.com/erew123/alltalk_tts/issues/28

**Comment by erew123** [comment]
![image](https://github.com/erew123/alltalk_tts/assets/35898566/fd3fa5a4-f779-42ab-9a85-8dbb78bc6a87)

The model has to be stored in /models/trainedmodel/

This is the default location that finetuning now moves models to after training. 

If a model is detected there when AllTalk **starts up**, it will add the additional loader type into the Gradio interface.
