### ISSUE TITLE
Can i use MMS models?

### ISSUE THREAD

**Issue by FacundoMartinezCampos** [erew123/alltalk_tts#246]
I need to finetune a Catalan TTS Model, if i add the functions to handle abreviations and numbers to letters to include catalan, would i be able to finetune and inference the MMS model?

**Comment by erew123** [comment]
Hi @FacundoMartinezCampos 

Last I can Coqui did not make support for Catalan within the model https://github.com/coqui-ai/TTS/issues/3250

In theory you can add Catalan to a model as a new language. There are some discussions/examples on how to do this, along with some people sharing their training Data/setup on Coqui's site e.g. https://github.com/coqui-ai/TTS/discussions/604 https://gist.github.com/exotikh3/740324a9b36f41f1f816260d252d6b58

Those are the sorts of instructions/documents you will need to research. I sort of loosely remember someone saying you need 1000 epochs to train a new language, but I would take that with a pinch of salt. 

You will need very high quality data for sure.

Im not personally an expert on finetuning to the level you need, but hopefully that points you in the correct direction.

Thanks
