### ISSUE TITLE
Standalone Install Error

### ISSUE THREAD

**Issue by Quidam2k** [erew123/alltalk_tts#247]
**Describe the bug**
Followed the "QUICK SETUP - Standalone Installation" steps. Ran start_alltalk.bat and got an error.

Ran the setup batch file again and told it to go through the dependencies, but it didn't change anything.

**Text/logs**
Traceback (most recent call last):
  File "B:\ai_art\alltalk_tts_standalone\alltalk_tts\script.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Desktop (please complete the following information):**
AllTalk was updated: fresh install
Custom Python environment: nope, the one that came with the install
Text-generation-webUI was updated: standalone

**Comment by erew123** [comment]
Hi @Quidam2k 

Is this AllTalk v1.9 or the beta of v2?

I see you have it on a B drive, so I would assume this is a virtual drive of some kind, I'm not certain if that will create any issues.

That aside, if its saying module not found, then 1 of 2 things is going on:

1) The Python virtual environment isnt starting up. Please can you try `start_environment.bat` and see if the AllTalk Python environment starts. (Please see Understanding Python Environments Simplified to explain what you should see) https://github.com/erew123/alltalk_tts?tab=readme-ov-file#installation-and-setup-issues

If that does start, you should be able to run `python diagnostics.py` to check if things are correctly installed in the Python Environment. 

If on the flip side the Python virtual environment doesnt start, it may be related to the virtual drive element of things. You would have to look inside one of those batch files to see where its pointing to to start up the Python environment.

##OR

2) The Python virtual environment never got built at all, which can happen if your system is unable to reach the Pytorch and PIP websites (internet issues or similar). Obviously the question here is did you see it downloading/installing things.

Let me know where you get to with option 1. 

If you can get the environment started, you can start alltalk with typing "python script.py" and you would also be able to force reinstall the requirements with `pip install -r system\requirements\requirements_standalone.txt`

Thanks

**Comment by erew123** [comment]
Hi @Quidam2k 

Not heard back from you. If you need more help, let me know.

Thanks
