### ISSUE TITLE
atsetup.bat automatically closes after mini conda install

### ISSUE THREAD

**Issue by JackOutside** [erew123/alltalk_tts#256]
🔴so i am trying to install it but cmd automatically closes after it installs mini conda

![mini conda](https://github.com/erew123/alltalk_tts/assets/173696651/c5475bf0-ef34-42da-8539-71ebbf665ce6)

🔴 i cannot create diagnostics report because it gives me this error shown below

![diagnoes](https://github.com/erew123/alltalk_tts/assets/173696651/97139bf5-8583-4bdf-88b8-0afb919021d5)

**To Reproduce**

Steps to reproduce the behaviour: I used this [video](https://www.youtube.com/watch?v=16iSL05_XAU) to install the alltalk and selected all windows 10 visual studio code rather than windows 11 as i use windows 10 

**Desktop (please complete the following information):**

AllTalk was updated: Used 3rd May zip file
Custom Python environment: no

**Comment by erew123** [comment]
Hi @JackOutside 

Ive no specific Idea why it would close, however, if you are clicking on the atsetup.bat file, rather than running it from a command prompt, it certainly wont give an error if it crashes out.

What I would propose is following the Standalone Installation process from here https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-quick-setup-text-generation-webui--standalone-installation

Specifically on Step 2 "Start AllTalk Setup:" run the `atsetup.bat` from a command prompt, rather than double clicking `atsetup.bat` and try going through the process that way. If it errors/exits at that point, you should see an error message which we can try figure out what is going on.

Let me know.

Thanks

**Comment by JackOutside** [comment]
Heyy @erew123 

Thanks for the reply, I tried to run atsetup.bat from a command prompt and i got this error

![frombat](https://github.com/erew123/alltalk_tts/assets/173696651/489dbc98-3f05-459d-a20d-a200f93d2284)

**Comment by erew123** [comment]
Hi @JackOutside 

Must have been an old bugged version of the batch file in that zip. So, go to this link https://github.com/erew123/alltalk_tts/blob/1.9c/atsetup.bat

Then click the download button and save it over the top of your existing `atsetup.bat` file and give it another go. 

![image](https://github.com/erew123/alltalk_tts/assets/35898566/d34af336-7498-4299-8a39-170ef5065cc4)

It should be good from there.

Thanks

**Comment by JackOutside** [comment]
hello @erew123 

i replaced the at.setup.bat file and now i am getting this error 

![moreerroes](https://github.com/erew123/alltalk_tts/assets/173696651/aae4d8d0-9dd5-44e6-ba58-eb17be1e02c4)


Thanks

**Comment by erew123** [comment]
Hi @JackOutside 

This is a recent new thing on that version of conda. Not sure if the environment was part created before you ran the new setup. Please check you have deleted the 'alltalk_environment' folder and try again. You can do that manually or option 4.

Let me know.

Thanks

**Comment by JackOutside** [comment]
hi @erew123 

yes, i am getting that error after deleting the "alltalk_environment" folder using the option 4 and manual method.

Thanks

**Comment by erew123** [comment]
Do you know if you have Conda/Anaconda for Windows installed separately? This software https://docs.conda.io/projects/conda/en/latest/index.html

In theory you can test by opening a new command prompt and typing `conda --version` which will either give you an error message or not-found type message. They had a bug/issue in one of their versions where this error was rampant.... I can only suggest a few things to try 

### If you DO have conda on your system

`conda config --set channel_priority false` should set to the classic solver.

You can try updating the conda install to see if that fixes it:

https://docs.anaconda.com/anaconda/install/update-version/

I would assume these:

```
# Update the conda package manager to the latest version in your base environment
conda update -n base conda
# Use conda to update Anaconda to the latest version in your base environment
conda update -n base anaconda
```
and if your conda version is later than version 23.x you can use this command:

`conda config --set solver classic`

### If you DONT have conda on your system

I would suggest delete the alltalk_tts folder, I assume you have git installed https://git-scm.com/download/win

Then at a command prompt in your "AI" folder, run `git clone https://github.com/erew123/alltalk_tts`

Then go into that folder and try the `atsetup.bat`

The reason I am suggesting this, is that conda can store hidden files that set the conda solver to use and there are about 30 of them and I would have no idea which one would need to be removed/changed. It would just be quicker/easier for you to go this route to clean the setup.

Thanks

**Comment by JackOutside** [comment]
hey @erew123 

So, I checked with the command line and i got "not found error" and i was still getting the same error after deleting and reinstalling alltalk from scratch.

Then i downloaded anaconda from the website you mentioned and applied this **conda config --set solver classic**  command in the anaconda prompt.

and it worked !!!

i guess probably when i did a reset my PC, some files of anaconda got left in my system??? idk.... but finally its working now.

Thank you so much for all help, hope you have a great day. bye

**Comment by erew123** [comment]
Hi @JackOutside 

Glad you have it sorted. Anaconda can be a funny sod when it goes wrong and you may have had this legacy bug thing, which plagued a lot of people. Not sure to be honest, but glad its resolved.

Thanks
