### ISSUE TITLE
Fine-tuning: Library cublas64_11.dll is not found or cannot be loaded

### ISSUE THREAD

**Issue by ShaunCassidyPoster** [erew123/alltalk_tts#26]
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/13783224/diagnostics.log)
Hi! (fluecured, btw) I have attached a "diagnostics.log" for fine-tuning.

**Describe the bug**
After installing requirements_finetune.txt and CUDA 11.8 Toolkit as explained, updating the Windows "Path" variable, and ensuring "nvcc --version" returned the proper version globally and in the "cmd_windows.bat" text-generation-webui environment, I commenced training with a 22:10 sample. The requisite training file(s) downloaded, and step 1 began.

After some time processing a temp wav file, the process stopped with "RuntimeError: Library cublas64_11.dll is not found or cannot be loaded". Searching the system, I located one "cublas64.dll", but it is a part of the stable-diffusion-webui default installation in a separate environment. (I was surprised the dll was not in the Toolkit files since I remember selecting "CUBLAS" in the NVIDIA installer.)

**To Reproduce**
This may be an error of configuration, requirements, or understanding, and reproducing it might might be as easy as temporarily removing that dll.

**Text/logs**
```
[FINETUNE] Current working file: F:\text-generation-webui\extensions\alltalk_tts\finetune\put-voice-samples-in-here\Voice Sample.wav
[FINETUNE] Processing audio with duration 22:10.801
[FINETUNE] VAD filter removed 00:00.000 of audio
Traceback (most recent call last):
  File "F:\text-generation-webui\extensions\alltalk_tts\finetune.py", line 731, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(target_language=language, whisper_model=whisper_model ,out_path=out_path, gradio_progress=progress)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\extensions\alltalk_tts\finetune.py", line 180, in format_audio_list
    segments = list(segments)
               ^^^^^^^^^^^^^^
  File "F:\text-generation-webui\installer_files\env\Lib\site-packages\faster_whisper\transcribe.py", line 941, in restore_speech_timestamps
    for segment in segments:
  File "F:\text-generation-webui\installer_files\env\Lib\site-packages\faster_whisper\transcribe.py", line 445, in generate_segments
    encoder_output = self.encode(segment)
                     ^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\installer_files\env\Lib\site-packages\faster_whisper\transcribe.py", line 629, in encode
    return self.model.encode(features, to_cpu=to_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Library cublas64_11.dll is not found or cannot be loaded
```

**Desktop (please complete the following information):**
AllTalk was updated: 12-25-2023
Custom Python environment: Using text-generation-webui one-click installer environment
Text-generation-webUI was updated: 12-24-2023

**Additional context**
Thanks, and happy holidays!

Edit: I do see a "F:\text-generation-webui\installer_files\env\Lib\site-packages\torch\lib\cublas64_12.dll" in the Oobabooga files. Could the recent update have moved ahead by a version?

**Comment by erew123** [comment]
Happy holidays to you too!

Assuming you installed the Nvidia Cuda 11.8 Toolkit, and I am assuming onto your C drive:, with these instructions https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-important-requirements-cuda-118

You should have a folder in the following path, with the files inside, that looks like this...???

![image](https://github.com/erew123/alltalk_tts/assets/35898566/b0819be4-3180-4177-96d8-4da99bf3ebb1)

**Comment by erew123** [comment]
You're welcome to git pull the latest update. https://github.com/erew123/alltalk_tts#-updating
I've just updated the diagnostics file to also pull your search paths for your OS, so I can have a look there (if you are still struggling with it).

**Comment by ShaunCassidyPoster** [comment]
Hmm, My install did not include those cublas dlls. Also, the nvblas64 one isn't there either. My installed bin looks like so:
![NVIDIA GPU Computing Toolkit_CUDA_v11 8_bin Capture](https://github.com/erew123/alltalk_tts/assets/61352459/6718d2f6-3d42-486d-a004-dc07d8e34124).

The only dll installed by the installer is "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\nvvm\bin\nvvm64_40_0.dll\". (I use the search program "Everything" to locate files.) I will run the updated diagnostic script shortly to see if that reveals anything further. Thanks!

**Comment by erew123** [comment]
Humm... strange. Its these things you select here that should make it install it:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/53702cbd-9adf-4b07-8f63-6ef0a5e24226)

You can either uninstall the Nvidia Toolkit and try the install again, see if that solves it.

OR, I've uploaded the one from my machine to here https://file.io/2s8aoi07NRZ3

I believe it just needs the actual file and there are no other associated files or settings, so just dumping these files in the correct location *should* work... in theory at least. 

You would need to extract out the files first and then copy them over to that folder and Windows will ask you for Admin permission as copying files in to a folder below "program files" is a protected permission on Windows 8+. Also, if you ever uninstall the Toolkit, you would probably have to manually delete out those 3x files, as the installer would have no history of them having been installed in the first place.

**Comment by rbruels** [comment]
@ShaunCassidyPoster As @erew123 said above, this is almost certainly because you need to select

`CUDA` > `Development` > `Compiler` > `Libraries` > `CUBLAS`
**and**
`CUDA` > `Runtime` > `Libraries` > `CUBLAS`

in addition to `nvcc`. You likely only selected the first. You can run the installer again to select that entry if you need to.

This is easy to miss, and it doesn't help that the CUBLAS entries are ordered differently in their respective sub-trees.

**Comment by ShaunCassidyPoster** [comment]
@erew123 @rbruels Thank you both, I have them now (and feel silly because I read the instructions so carefully!). Thanks a lot and happy New Year!

**Comment by erew123** [comment]
@ShaunCassidyPoster No probs! Glad you got it sorted :) 

FYI.. Ive just updated finetune about 20 minutes ago, so you may want to update as it makes the final stages easier AND compacts your models down. https://github.com/erew123/alltalk_tts?#-updating

As you say, Happy New year (when it gets here)
