### ISSUE TITLE
LLVM ERROR: Symbol not found: __svml_cosf8_ha (start_alltalk.bat - standalone)

### ISSUE THREAD

**Issue by AntonTrapp** [erew123/alltalk_tts#264]
**Describe the bug**
Installing and starting the standalone leads to `LLVM ERROR: Symbol not found: __svml_cosf8_ha` and an exit.

**To Reproduce**
- follow download procedure in the README for standalone installation for Windows.,

**Text/logs**
[diagnostics.log](https://github.com/user-attachments/files/16114962/diagnostics.log)

**Desktop (please complete the following information):**
AllTalk was updated: 6.7.2024 - fresh installation
Custom Python environment: no, anaconda on system but used installer, env set to alltalk_tts evnironment and miniconda is used hardcoded in .bat files.
Text-generation-webUI was updated: standalone

**Additional context**
I guess it's one of the svml_dispmd.dll / numba issues. Setting `NUMBA_DISABLE_INTEL_SVML=1` does not help, I removed the dll from the search path (for testing), did not help either. It's used by UltiMaker Cura, VSTs (music making plugins) from Waves Audio, Asus Amoury, Luminar, ...

**Comment by erew123** [comment]
Hi @AntonTrapp 

This `__svml_cosf8_ha` is the Intel **Short Vector Math Library** (SVML) that is missing from your system [Intel link/reference here](https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-8/intrinsics-for-short-vector-math-library-ops.html), and specifically its related to the Intel® C++ Compiler (made by Intel of course).

I **believe** this comes as part of Visual Studio 2019 onwards, so you may want to check what version of Visual Studio you are using and possibly upgrade it. The Visual Studio 2022 edition would be fine https://visualstudio.microsoft.com/downloads/ 

![image](https://github.com/erew123/alltalk_tts/assets/35898566/057209cd-a7ef-4442-9d6c-17ec69a1c5c1)

Reference here, that says SVML is part of Visual Studio 2019 onwards https://devblogs.microsoft.com/cppblog/msvc-backend-updates-in-visual-studio-2019-preview-2/

I think it also comes as a part of the Intel Distribution for Python https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html#python

You can also (supposedly) just look to download `svml_dispmd.dll` as a standalone file and copy that into your `/windows/system32/` folder, though I would highly recommend one of the above routes over doing this,

Obviously your system will/should need a reboot to activate this after installation.

Thanks

**Comment by erew123** [comment]
Just to add, I think Intel have updated the C++ compiler to be part of the `oneAPI DPC++/C++ Compiler` https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler.html so for that, standalone versions are here https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler-download.html though Visual Studio 2019 or later would still be the best option.
