### ISSUE TITLE
Can't disable setting "Pass Asterisks to TTS Engine"

### ISSUE THREAD

**Issue by uberubert** [erew123/alltalk_tts#270]
**Problem:** Every time I load the interface, it re-enables the setting for "Pass Asterisks to TTS Engine".

![bilde](https://github.com/erew123/alltalk_tts/assets/2908847/8ab84e71-3e13-4beb-af54-2f0d4b115a82)

**Expected behaviour:** I want the setting to stay disabled after I disabled it, even after reloading the SillyTavern webapp.

**What I tried**:

I snooped around in the code, found that it clicks the checkbox and override its setting based on some other setting. This happens during website init/loading. I found this happens on two separate places in the code:

- alltalk.js line 240 (ish)
- alltalk.js line 585 (ish)

By removing these if statements completely, the setting seems to stay disabled, even after reloading the SillyTavern webapp. I can't really tell if this will have any bad effects, but my desire to avoid having asterisk text spoken by the tts is now fulfilled, if only temporarily.

![bilde](https://github.com/erew123/alltalk_tts/assets/2908847/8dc5a55e-d7c6-4214-ae9a-b075d7cbe2db)

**Comment by erew123** [comment]
Hi @uberubert

Please see https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-a-note-on-character-cards--greeting-messages to explain why asterisks are passed over to AllTalk. As such, enabling the Narrator will be what switches on/off the "Pass Asterisks" and they would not be pronounced as the word asterisk, but used to delineate Character or Narrator spoken text. 

Hope that helps clarify.

Thanks

**Comment by erew123** [comment]
Just FYI, you can test this behaviour out with the provided CURL commands in the API section (replacing the settings with those that match your chosen voices and the current TTS engine).

https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-example-command-lines-standard-generation

**Comment by erew123** [comment]
Filtering is applied at the point where the chart turns red, as the TTS is generated and before being processed by RVC etc

![AllTalk API Process](https://github.com/erew123/alltalk_tts/assets/35898566/b5e72c95-8b4f-4738-84f2-982403e56c8e)

**Comment by uberubert** [comment]
I think this issue is more related to UX than how the plugin works technically.

My narrator setting was disabled, I expected only the quoted "character speaking" text to be voiced. To my surprise, the entire thing was voiced even when it was in asterisks. It was voiced because the option was re-enabled automatically upon my reloading the webapp.

So it seems I have to keep the narrator enabled in order to avoid asterisk-text to be spoken. But then there's no way to reduce spoken voice to just the quoted "character speaking" text, unless I manually go over the settings every time I load the app.

To me this makes little sense, as it only serves to override my ability to manipulate options given to me. If this option absolutely must be set to a specific value, then would it not make more sense to remove this option? As a user, I would expect this option to stay the way I put it, or not be there at all.

Also, should I really switch to V2? I always prefer stable over beta, which is why I stick with V1 for now. (Oh, and I don't mean to come across as critical here, I'm loving the generated voice lines!)

**Comment by erew123** [comment]
Hi @uberubert 

In v2 there is "Enabled Silent" options for narrator and text not inside. Its detailed in the Gradio interface documentation, however, here is a partial snippet:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/f3162fa3-5b7c-4433-9662-544b525e5d48)

With SillyTavern, it does require the updated extension be updated to the v2 extension (instructions here) https://github.com/erew123/alltalk_tts/tree/alltalkbeta/system/SillyTavern%20Extension/For%20AllTalk%20V2

As for v2, the core codebase is pretty solid and Ive had little issue with that. There is mainly 40-60 hours of documentation improvement/writing to do, finish google colab, create a docker build for people who use docker and I may yet add other features listed here https://github.com/erew123/alltalk_tts/discussions/74

Its purely your choice.

Thanks
