### ISSUE TITLE
Gradio Off

### ISSUE THREAD

**Issue by Abdulhanan535** [erew123/alltalk_tts#273]
Any way to turn off gradio and only use ST api? (kaggle hates gradio and crashes) Kaggle is like google colab. (remaining things works fine in kaggle)

**Comment by erew123** [comment]
Hi @Abdulhanan535 

Yes in the Gradio interface in the Settings:

![image](https://github.com/user-attachments/assets/852755bb-8210-4146-bb93-bbc960a2483f)

Of you can edit the confignew.json and change `true` to `false`

![image](https://github.com/user-attachments/assets/197ba782-0164-4fa0-be94-c0cc425bbdc5)

Thanks

**Comment by Abdulhanan535** [comment]
Thanks alot i'm so glad
