### ISSUE TITLE
On error not closing logs

### ISSUE THREAD

**Issue by RenNagasaki** [erew123/alltalk_tts#275]
AllTalk v1 and v2 don't close the logs of an failed finetuning try.
![grafik](https://github.com/user-attachments/assets/f40aa0d7-0f5f-49e2-a81a-bd4d1ee8a640)
I failed three times but all 3 folders can;t be deleted because the logs are kept open.

Not a big issue but still one nonetheless.

**Comment by erew123** [comment]
@RenNagasaki 

Yes, I know about this one. Its something in Coqui's scripts that just wont let go of the log files until the Python session is killed. It's one of those minor annoyances, that maybe Ill take a look at Coqui's scripts in future and submit a PR over to Eginhard if I can figure out what the deal is.

Thanks
