### ISSUE TITLE
Support for MARS models

### ISSUE THREAD

**Issue by lofcz** [erew123/alltalk_tts#285]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
To my knowledge, MARS5 and the upcoming MARS6 are the sota English TTS models with open weights available - https://github.com/Camb-ai/MARS5-TTS
Given that AllTalk TTS already supports multiple models, I'd like to know whether the maintainer would be interested in adding support for MARS in v2.

**Describe alternatives you've considered**
Do nothing :/

**Comment by erew123** [comment]
Hi @lofcz 

Pretty much any TTS engine can be added in and there is a new engine template folder with instructions in the code base https://github.com/erew123/alltalk_tts/tree/alltalkbeta/system/tts_engines/template-tts-engine

And throughout all the template files, they are documented with instruction e.g.
https://github.com/erew123/alltalk_tts/blob/alltalkbeta/system/tts_engines/template-tts-engine/model_engine.py

The only considerations are that something installed by one engine could over-lap/over-write other engine's requirements, but thats not an issue if you DONT want to use both engines (should there be a conflict).

The instructions for the TTS engine you list one seem pretty easy and are documented on the main page of it, so it should be easy to add in Id think.

I can take a look at it some time, or youre welcome to have a go yourself.

Thanks

**Comment by lofcz** [comment]
Thanks for the quick reply. Adding MARS is something we want to do, I've checked the instructions and they seem clear to me, however, I have no knowledge of the codebase, and implementation on our side would probably be something hacky, to just get it working for our use case. Hence the inquiry on whether we should go ahead, or if this is something you would be open to adding.

**Comment by erew123** [comment]
@lofcz Sure, no problems. I have a few TTS engines to add in at some point, so ill take a look soon.
