### ISSUE TITLE
Finetuning: Processed sentence clips are truncated sometimes

### ISSUE THREAD

**Issue by rbruels** [erew123/alltalk_tts#29]
This is not a terribly helpful issue yet, but I wanted to open it for input/tracking.

When running `finetune.py`, the script processes the sound clips through Whisper to get the text transcript and timecodes of the words within them. It then separates the sentences out (by punctuation) and then saves the individual sentences as separate audio clips. 

This generally works (and is rather magical), but I'm noticing that a lot of those clips are truncated, and almost always at the *end* of the clip. It's usually the last syllable or so of the audio clip (though the transcription of the clip in `metadata_eval.csv` is full and correct). 

In my first totally unscientific experiment, I think this is affecting my final output (a lot of my TTS sentences seem to get weirdly truncated) but I haven't completely verified that.

I have read a number of filed issues saying that Whisper can be inaccurate with its timestamps (especially at the sub-second level), so it's possible that the times for the word start and word end aren't accurate, which would then propagate to this clipping functionality: https://github.com/erew123/alltalk_tts/blob/993d065368385c2a03c06a1359fdb6a4b0227689/finetune.py#L225

Will add more to this issue as I discover more.

**Comment by erew123** [comment]
Yes it can do that and I cant say I know the absolute end impact of that, as in how much it affects the final result. I also cannot say if Whisper model 2 or 3 is better (out of the choices), I haven't had opportunity to test that far. If you are playing about with finetune, you may want to update as I've literally just updated the code. The final page now has buttons (always a bonus) and a compaction routine to get the model back down from 5GB to 1.8GB 

There's also a separate compact script for any pre-existing models. Instructions here https://github.com/erew123/alltalk_tts/issues/28

![image](https://github.com/erew123/alltalk_tts/assets/35898566/16e0b1b8-c7a8-47ec-8abd-f734bb59ecc9)

If you do find out more, Id be dead interested! Again, thanks for helping out. Its really appreciated!

**Comment by erew123** [comment]
Not certain on this and would need more research but as faster-whisper uses Silero VAD https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#vad-filter it looks like it *may* have a min_silence_duration setting https://github.com/snakers4/silero-vad/wiki/FAQ#how-to-tune-the-hyper-parameters which perhaps adjusting this setting could(?) force the voice samples to be a bit less likely to be cut. Would need more research and understanding, but Im just putting this here as a note for now.

**Comment by rbruels** [comment]
fwiw (and totally unscientific), either the code changes you made today or using the whisper2 model actually seemed to improve things dramatically. I'll eliminate a variable tomorrow, but the results of my latest fine-tuning with the same dataset are pretty astounding.

**Comment by erew123** [comment]
I believe that each time you slice up the audio with it, you will more than likely get different slicing, or potentially different training wav's (I guess depending on how long your input audio is). Also the Speaker Reference wav you use at the end also varies the quality of the TTS output...

But if Whisper2 is actually slicing the wav files up better.... then that would be a definite boost to the whole process!

**Comment by erew123** [comment]
Hi @rbruels. Hope you are keeping well. Not heard back from you for a while. Im going to mark this closed for now, just to clear up the Issues section on the github.
