### ISSUE TITLE
Support for metavoice-1B

### ISSUE THREAD

**Issue by manneschui** [erew123/alltalk_tts#300]
Hi, 
with the granted and restricted Coqui licence issue AllTalk is not and will not be available for commercial use. 

Is there any way to get 
https://github.com/metavoiceio/metavoice-src 
https://huggingface.co/metavoiceio/metavoice-1B-v0.1 
support up and running for usage with AllTalk as replacement API TTS model?

Thank you!
Kind Regards

**Comment by erew123** [comment]
Hi @manneschui 

I will add it as a potential engine to the Features Request list https://github.com/erew123/alltalk_tts/discussions/74

Instructions for adding in a new TTS engine are also there if you know a bit of coding.

Thanks
