### ISSUE TITLE
Are you going to add latest Parler TTS large v1 and mini V1 models?

### ISSUE THREAD

**Issue by maxbizz** [erew123/alltalk_tts#302]
Parler TTS just released Parler TTS Large v1 and Mini V1 model. They produce high quality TTS compared to previous model and also woth speaker consistency.
When can we see the new models added to alltalktts?

**Comment by erew123** [comment]
Hi @maxbizz 

Already done https://github.com/erew123/alltalk_tts/commits/alltalkbeta

Thanks

**Comment by erew123** [comment]
Hi @maxbizz 

I noted this in the help section of the TTS engine.

![image](https://github.com/user-attachments/assets/d7ac20ef-caa5-4458-b1d8-dc3b626b220c)

And I found a few people on Reddit and other areas commenting about such issues e.g.

![image](https://github.com/user-attachments/assets/5044819f-9c2b-4a98-93e3-2815c8f4906f)

![image](https://github.com/user-attachments/assets/e5c231ab-2620-412a-814d-ba9c07416255)

All I can say at this point in time is the implementation of Parler is as recommended by Parler themselves, there is nothing new, special or clever that AllTalk does that is not Parler's suggested implementation https://github.com/huggingface/parler-tts?tab=readme-ov-file#-using-a-specific-speaker

As/when/if Parler update their code to improve/resolve any issues like this, you can update AllTalk/Parler with:

1) Running the `start_environemnt` script at a command prompt/terminal.
2) Once the Python environment has started, you can run `pip install -U git+https://github.com/huggingface/parler-tts.git` to update the Parler codebase on your system.

There is obviously nothing I can personally do to resolve either issues with Parler's codebase/AI model and I would watch/report issues to the Parler team on Reddit or Github.

Thanks
