### ISSUE TITLE
Loading Parlor at 16-bit

### ISSUE THREAD

**Issue by LaaZa** [erew123/alltalk_tts#303]
**Is your feature request related to a problem? Please describe.**
With Parlor-large being well... rather large, it would be nice to have the option to load it in (b)float16 instead of float32.

**Describe the solution you'd like**
Add an option in Parlor settings to choose dtype: float32, float16, bfloat16.

**Describe alternatives you've considered**
Actual quantization for even better memory savings. I don't know if any of them work right now though.

**Additional context**
Effect on quality is difficult to determine due to the model's inherent variability, but I did not notice anything significant. I think the option to save 50% on memory is more significant than any minor quality loss. This is easy to implement, only dtype on the model loading needs to be changed.

**Comment by erew123** [comment]
Hi @LaaZa Ill get onto this at some point in time. Ill note it in the feature requests. https://github.com/erew123/alltalk_tts/discussions/74

Thanks
