### ISSUE TITLE
Add an option to send a voice (file not name) with the streaming/generation request.

### ISSUE THREAD

**Issue by RenNagasaki** [erew123/alltalk_tts#306]
Add an option to send a voice (file not name) with the streaming/generation request, so that the service doesn't need to hold all voices beforehand but can get spoonfed per request.

What I mean with that is. 
At the moment you need to have the voices inside the voices folder. I'd like it if I could send the currently needed voicefile for that generation with the request, so that my voices folder can stay empty and I can place them client side. (Easier for clients to manage)

**Comment by erew123** [comment]
Hi @RenNagasaki 

Ill note it in the feature requests as Im getting a bit behind on code now.

Thanks
