### ISSUE TITLE
Torch error on text-generation-webui 'Apply requirements' while running at_setup.bat

### ISSUE THREAD

**Issue by Nelmynce** [erew123/alltalk_tts#313]
Off the top, my apologies if this is something really basic and I'm just not understanding it but I've checked everything I can think of and I'm not sure why I'm getting the following error.

I'm trying to install alltalk as an extension in text-generation-webui.  Installing the former package went off without a hitch.  Once that was done I started up the environment by running cmd_windows.bat in the text-generation webui folder via the command console:

![image](https://github.com/user-attachments/assets/05a53281-8e14-4cfc-8482-79ddd0f697c8)

When I run at_setup.bat from within extensions/alltalk_tts with the environment running, it runs just fine.  I pick the first option to Apply/re-apply the requirements for text-generation-webui and then I get the following error:

ERROR: Invalid requirement: 'torch>=2.1.0+cu118': Local version label can only be used with `==` or `!=` operators
    torch>=2.1.0+cu118
         ~~~~~~~^ (from line 6 of system\requirements\requirements_textgen.txt)

![image](https://github.com/user-attachments/assets/9e059a44-7350-438a-9bc7-525f8017e250)

I generated a diagnostics report from within at_setup which tells me I'm running torch 2.2.2+cu121 which should satisfy this requirement; however if I'm understanding the error correctly it actually looks like it's spitting out some sort of syntax error and that it won't accept a '>=' operator.  Looking into the requirements_texgen.txt file there are several lines before this one that use that same operator and it's not throwing an error, so I'm stumped.

Here's the log file I generated:
[diagnostics.log](https://github.com/user-attachments/files/16620417/diagnostics.log)

I ran an update on all the requirements for text-generation-webui as well as the repository itself even though it was a fresh install just to be sure, but that didn't make any difference.  Both text-generation-webui and alltalk were installed for the first time today; however I did try to install the standalone version of alltalk first before realizing that I wanted the webui, so maybe that caused some conflicts when I deleted the install.

Any help would be appreciated!

**Comment by erew123** [comment]
Hi @Nelmynce 

Annoyingly they have recently changed PIP (the Python package installer) and how it handles the version control. I've been knowing this day would come when TGWUI bumps to using the newer version of PIP. 

Thankfully its been a pretty easy fix this time! 

All you will need to do it go into the `alltalk_tts` folder and `git pull` to get the changes. After that, go through the install as you were doing and it should process through fine (I tested the whole process myself and had no issues).

Thanks
