### ISSUE TITLE
The "start_alltalk" batch file, but that pops up really briefly and then just disappears again. 

### ISSUE THREAD

**Issue by Yaffa16** [erew123/alltalk_tts#317]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Screenshots**

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date]
Custom Python environment: [yes/no give details if yes]
Text-generation-webUI was updated: [approx. date]

**Additional context**

**Comment by erew123** [comment]
Open up your command prompt from the Windows start menu. Move into the alltalk_tts folder and run the batch file. You will then be able to see whatever error message there is, rather than it closing the command prompt before you can read/see the error message or reason that its not running.

**Comment by Yaffa16** [comment]
Thanks, I was able to get it running
