### ISSUE TITLE
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

### ISSUE THREAD

**Issue by ChooChoo38** [erew123/alltalk_tts#319]
I'm having a number of issues installing AllTalk v2 Standalone. I've followed all the instructions and I've installed the [Windows & Python requirements for compiling packages](https://github.com/erew123/alltalk_tts#-help-with-problems).

This is the installation log from atsetup.bat: [install_log.txt](https://github.com/user-attachments/files/16735158/install_log.txt). The only obvious error I can see is when installing nvidia-cudnn-cu116. 

Once atsetup.bat has finished installing all the requirements, I get this message when trying to run start_alltalk.bat.

![Screenshot 2024-08-24 133519](https://github.com/user-attachments/assets/e47bb4c0-13bb-4e23-8745-7b35deb19352)

start_diagnostics.bat also has an issue on my computer given one of my hard drives belongs to the company I work for and is usually encrypted, so it gives me this error:

![Screenshot 2024-08-24 133731](https://github.com/user-attachments/assets/375627c0-b5f4-49a8-9907-e5029db8b231)

I have to edit diagnostics.py and remove the lines that check each drive for space, then it works. This is the output: [diagnostics.log](https://github.com/user-attachments/files/16735162/diagnostics.log). To add to that, I have plenty of free space on every drive.

Going back to the error I get when I try to run start_alltalk.bat, I found [this discussion](https://github.com/erew123/alltalk_tts/discussions/245#discussioncomment-9847083). Following that advice gets me the following: 

![Screenshot 2024-08-24 134908](https://github.com/user-attachments/assets/e58a1433-3392-4b87-acdc-0c52660990e0)

It would seem a number of the requirements weren't installed correctly for whatever reason. At this point, I started atsetup.bat again, chose standalone and did Re-Apply/Update the requirement file, but the end result was the same, claiming I was missing various modules. I ran atsetup, deleted AllTalk's custom Python environment, tried to install again, same issues.

My next step was to run atsetup.bat, install, manually install pillow, then I tried to manually pip install the contents of requirements_standalone.txt. This worked. I could run AllTalk with no issues after that, and all the models work correctly.

![Screenshot 2024-08-24 144632](https://github.com/user-attachments/assets/e3ffcc6d-673b-4357-9883-278c756f6a84)

So even though I solved the issue, I'm still posting this as I have no idea what went wrong, and this also might help anyone encountering the same issue.

Also, the last problem I'm having that I have yet to solve is that start_finetune.bat does not work. I get the following error:

![Screenshot 2024-08-24 135944](https://github.com/user-attachments/assets/e38138bb-982f-450e-9e52-c78a431f1a91)

I even tried following the [Legacy manual instructions for installing Nvidia CUDA Development Toolkit 11.8](https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-can-i-finetune-a-model-more-than-once-on-more-than-one-voice), including adding the correct PATHs and such.

**Comment by erew123** [comment]
Hi @ChooChoo38 

Ive seen this a few times and Im not sure if its internet related somehow, but sometimes when Python's installer (PIP) loses connection to the downloads, it doesnt always pull the files down and just skips installation of bits, though saying that, there have also been many changes to PIP which is impacting other packages requirements, leaving a situation where its a constant gave of keep-up trying to make the requirements files work.

You can re-apply the requirements on option 3 of atsetup, which will just skip through anything thats already installed.

![image](https://github.com/user-attachments/assets/f1a7a52f-b619-44fa-b643-3581ae8f0fd4)

The trainer analytics can be installed with `pip install trainer`. 

Ive updated the diagnostics to work around locked/encrypted drives.

Id suggest performing a `git pull` and re-apply the requirements.

Thanks
