### ISSUE TITLE
Connection between SillyTavern & Alltalk works, but Error 500 occured: Model file not found.

### ISSUE THREAD

**Issue by therky04** [erew123/alltalk_tts#321]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file
[diagnostics.log](https://github.com/user-attachments/files/16740503/diagnostics.log)

**Describe the bug**

Thank you very much for your efforts, I really enjoy playing with the TTS.
I have setup Alltalk as standalone using the script provided and through the webgui I can make use of Piper as the engine. I have connected it to SillyTavern and it works, but SillyTavern gives me an Error 500, as it is not able to access the model:

**To Reproduce**
Steps to reproduce the behaviour: Setup Alltalk, have it connect to SillyTavern, click on "Available voices" and try a playback of the default voice.

**Screenshots**
![2024-08-25 16_00_53-SillyTavern – Mozilla Firefox](https://github.com/user-attachments/assets/8c2918ff-3ac2-4f7d-8929-9933a912d6cb)
![2024-08-25 16_03_06-Termius - 215  pott ollama](https://github.com/user-attachments/assets/00faa0be-ebf5-4de6-a251-deb93ff173e3)

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date] 25.08.2024
Custom Python environment: [yes/no give details if yes] no
Text-generation-webUI was updated: [approx. date] SillyTavern, Standalone

**Additional context**
One other thing, how can I change the engine to xtts? I've tried and failed.

**Comment by therky04** [comment]
[diagnostics.log](https://github.com/user-attachments/files/16740526/diagnostics.log)

**Comment by erew123** [comment]
Hi @therky04 

Have you update the extension for SillyTavern as listed in the Documentation:

![image](https://github.com/user-attachments/assets/29814b81-547e-4f95-be97-816282a1668f)

You can swap TTS engines with the Swap TTS engine button. 

![image](https://github.com/user-attachments/assets/748baec8-3bfd-4852-9216-3667f7f6ed1c)

Obviously, ensure you have downloaded a model for XTTS:

![image](https://github.com/user-attachments/assets/f9b2970d-b311-4834-99f4-0f299f3aa180)

Thanks

**Comment by therky04** [comment]
I’m very sorry, I must have missed these steps. I will try that again and give feedback by tomorrow. Thanks for your quick reply.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: erew123 ***@***.***>
Gesendet: Sunday, August 25, 2024 5:33:58 PM
An: erew123/alltalk_tts ***@***.***>
Cc: Sebastian Lanfermann ***@***.***>; Mention ***@***.***>
Betreff: Re: [erew123/alltalk_tts] Connection between SillyTavern & Alltalk works, but Error 500 occured: Model file not found. (Issue #321)


Closed #321<https://github.com/erew123/alltalk_tts/issues/321> as completed.

**Comment by therky04** [comment]
It works, thank you very much! Brilliant work :)
