### ISSUE TITLE
DeepSpeed N/A in Gradio Alltalk_v2

### ISSUE THREAD

**Issue by SuperMaximus1984** [erew123/alltalk_tts#322]
I've been using AllTalk_1.9c for a while with DeepSpeed enabled, but after I got V2 installed I see this in Gradio:
![image](https://github.com/user-attachments/assets/d96c84ed-1e82-44bc-beb6-65a0cf0f3cc0)
And CLI outputs as if everything is installed as it should:
![image](https://github.com/user-attachments/assets/1f76a91a-dec6-4eb1-8ceb-92b5405257de)

What can be wrong with DeepSpeed and other configuration functions that are N/A?
Just in case - requirements.txt for Standalone installation are up-to-date, PyTorch either, as you may see.

**Comment by erew123** [comment]
Hi @SuperMaximus1984 Features that are not available for a specific TTS engine will not be selectable.

![image](https://github.com/user-attachments/assets/73b6e9a9-eadf-4649-97a9-a9d21b097b40)

On the engine information tab, you can find details of each TTS engines capabilities. Piper does not support DeepSpeed:

![image](https://github.com/user-attachments/assets/b3343186-4e5b-447d-8091-dce0b280bc5a)

Xtts does:

![image](https://github.com/user-attachments/assets/7a5b229f-de43-45c3-9b24-cde0663c5977)

Thanks
