### ISSUE TITLE
Just wanted to say Alltalkbeta (v2) is absolutely amazing. I love it. Espescially with piperTTS! Comfyui Custom Node?

### ISSUE THREAD

**Issue by FemBoxbrawl** [erew123/alltalk_tts#326]
I was just asking if you could possible create a custom node for comfyUI, which connects to the Alltalk address. (I am trying to get not only images but also text to speech, LLMs + much more all within comfyui, for custom AI workflows without having to constantly switch tabs, etc.

also, if you do add this, It would be cool to have different nodes that can conneect to the main node, such as an input text, as well as a text generated from an LLM, etc.? (not necessary even if nothing works)

**Comment by erew123** [comment]
Hi @FemBoxbrawl 

I did have a brief glance at ComfyUI's dev guide. Its certainly possible to do, though, it may be a decent bit of work. I've certainly never touched ComfyUI before as far as coding goes, so not sure how easy it would be to impliment.

What level of integration are you looking for? Just basic send text/use X voice? or more in depth?

**Comment by erew123** [comment]
Hi @FemBoxbrawl 

Sorry for the late reply, but I have very limited time at the moment. Im trying to crack through as many feature requests as possible, along with dealing with support etc, as well as balancing family matters.

I've added this to the Feature Requests [here](https://github.com/erew123/alltalk_tts/discussions/74) under the General heading. It will be one of those, when I get time, things. Its in the list though.

Thanks
