### ISSUE TITLE
support RVC voices in TTS Generator

### ISSUE THREAD

**Issue by rktvr** [erew123/alltalk_tts#328]
having xtts voices run through RVC voices is nothing short of magical. please add that feature into the tts generator!

thank you for your continued work on Alltalk.

**Comment by beeblebrox** [comment]
This is already available, make sure you have enabled rvc in the global settings area.

**Comment by beeblebrox** [comment]
I just doubled check, and yes you need to enable RVC first in global settings and then after reloading and refreshing you can see all the RVC option in the TTS generator API.

**Comment by rktvr** [comment]
> I just doubled check, and yes you need to enable RVC first in global settings and then after reloading and refreshing you can see all the RVC option in the TTS generator API.

I mean on this page, it would be nice to have the same RVC options as on the generate TTS gradio page. 
![image](https://github.com/user-attachments/assets/5ffb45db-501b-4919-86dd-0b16d326f996)

**Comment by beeblebrox** [comment]
Agreed.  It isn't intuitive that the global settings will apply the default
RVC settings. The preview of the voice does not use the full pipeline even
though it is used when you generate on this page. This further confused the
usage expectation.

**Comment by erew123** [comment]
Hi

I've noted this in the Feature Requests here https://github.com/erew123/alltalk_tts/discussions/74

I am delayed/behind on work on AllTalk at the moment, due to caring for a family member, so it will be an if/as/when I can get around to it.

Thanks

**Comment by erew123** [comment]
RVC Voice+Pitch in TTS Generator - Completed https://github.com/erew123/alltalk_tts/commit/e534cedc62e577bed68d6da030a021648512e50d

![image](https://github.com/user-attachments/assets/c71ca8ce-f2c2-4deb-ab2c-242914ec8679)
