### ISSUE TITLE
[alltalkbeta] Windows standalone installer breaks if conda exists

### ISSUE THREAD

**Issue by DaniDipp** [erew123/alltalk_tts#330]
**Describe the bug**
I'm trying to upgrade my installation to the beta branch. I switched branches in git, pulled any changes, and ran `atsetup.bat`. I selected Standalone and let it re-apply/update the requirements. Then I selected "Install AllTalk as a Standalone Application" which terminated with the error
```
The system cannot find the batch label specified - RunScript
```
This refers to this `goto` statement which does not have a target in this script
https://github.com/erew123/alltalk_tts/blob/341984315d1d6862d4e1dd88782f1bb5a1a0aa77/atsetup.bat#L380

**To Reproduce**
Steps to reproduce the behaviour:
1. Install AllTalk
2. Switch to beta branch
3. With conda already installed, run `alltalk.bat` and start the Standalone installation

**Screenshots**
![2024-09-07T01-32-18](https://github.com/user-attachments/assets/91600f2d-4914-4973-acc9-96ae1c293cd8)

**Text/logs**
If applicable, copy/paste in your logs here from the console.
[diagnostics.log](https://github.com/user-attachments/files/16913680/diagnostics.log)

**Desktop (please complete the following information):**
AllTalk was updated: Installed on main branch on 2024-06-09
Custom Python environment: idk, I installed python 3.11.9 via pyenv
Text-generation-webUI was updated: n.a.

**Additional context**
-

**Comment by ldavis9000aws** [comment]
Just clone the repo using **--branch alltalkbeta** into a separate directory, do the standalone install, then copy over the models & speaker voices from the previous installation. I wouldn't attempt to do an in-place upgrade of a beta version that may potentially screw up my existing install. You're just asking for trouble.
