### ISSUE TITLE
Multiple voices in generator

### ISSUE THREAD

**Issue by ErnieV** [erew123/alltalk_tts#334]
Did you consider doing multiple voices in TTS Generator? You could let it read a whole book and do a different voice for all of the characters.

We’d need some kind of markup for each character like <nar> This is the narrator <\nar>
<hp> This is Harry Potter <\hp>

And a way to link each markup to a voice.

Just a thought. Love the thing as is tho!

**Comment by erew123** [comment]
Hi @ErnieV

This has kind of been requested in the API suite already. Its in the Feature requests https://github.com/erew123/alltalk_tts/discussions/74

Its possible, as everything is in code, but quite complicated too and obviously a question of time to write something to handle it. So as/when/if I get time to do it, it will be there.

Thanks
