### ISSUE TITLE
alltalk_tts seem to not want to install properly

### ISSUE THREAD

**Issue by phenix60** [erew123/alltalk_tts#351]
🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

Le fichier de diagnostic:
[diagnostics.log](https://github.com/user-attachments/files/17116720/diagnostics.log)

**Describe the bug**
I can't launch start_alltalk.bat after installation, when i double click it it close itself instant.
I think it's due to some step he couldn't finish properly during installation i took some screenshot of red error that i think could be the culprit, even if i don't know how to solve it

**To Reproduce**
Steps to reproduce the behaviour:
i was trying to install alltalk_tts,  so i download the zip on the github page, extract it to a folder i wanted that i named alltalk, and launch the atsetup.bat.
Followed the setup and at the and it say close and launch start_alltalk.bat, but when i do nothing happen, a window pop for like no even a second and close immediatly.

**Screenshots**
![Capture d’écran 2024-09-24 143946](https://github.com/user-attachments/assets/8f6f1212-c1fc-42fd-a469-508cd09b6278)
![Capture d’écran 2024-09-24 144016](https://github.com/user-attachments/assets/354e12bf-7901-4809-96b1-fcbf01fe20bd)
the 2 error i see when running the atsetup.bat
the 1 st one said i need visual c++14 or higher and use microsoft c++ build tool to get it, thing i had previously installed as the screenshot show
![image](https://github.com/user-attachments/assets/eb3057cd-8ea4-476a-a5ca-76146590b717)
( it's 17.11.4, so it should be good as it's above 14, but the installer seem to not detect it or idk what.

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: freshly installed today 24/08/24 around 14h gmt+2
Custom Python environment: [yes/no give details if yes]: not sure but i don't think i have a custom environnement, as i just unzip the archive i got from the github and launch the atsetup.bat
Text-generation-webUI was updated: [approx. date]

**Additional context**
not sure what i could add
some log i got when creating the diagnostic file maybe 
![image](https://github.com/user-attachments/assets/b3893f51-124d-4921-acd6-b4fb3f0d1674)
![image](https://github.com/user-attachments/assets/d8136d1a-af97-44c9-a174-9ee9837ac4b3)
i tried to install it as a standalone when i did the install.
if you need other info tell me, i hope you could help me figure out why this happen

**Comment by erew123** [comment]
You may not have the specific modules installed within Visual studio, as such it cannot compile Python wheel files.

Please see `Windows & Python requirements for compiling packages (ERROR: Could not build wheels for TTS)` https://github.com/erew123/alltalk_tts?tab=readme-ov-file#installation-and-setup-issues

If you check that, install any missing requirements and try the installation afterwards, it should work.

Thanks
