### ISSUE TITLE
Missing components after install (ffmpeg.asyncio/sounddevice/Cublas64_11/Visual Studio).

### ISSUE THREAD

**Issue by Jidis83** [erew123/alltalk_tts#353]
Hi again @erew123 ,

(this is continued from the discussion here regarding some missing components:  https://github.com/erew123/alltalk_tts/discussions/245#discussioncomment-10783830 )

I had done a git pull last night and was up to date, but just got the newest batch (9-28-24) with the updated Build Tools/SDK section in the diagnostics. I do indeed get this:

Windows C++ Build tools & Windows SDK:
 Windows Version: Windows 10
 **No Visual C++ Build Tools or Visual Studio found.**

though initiating a "modify" in the Visual Studio installer shows the requirements as being present (screenshot attached).

As mentioned in the discussion, "python-ffmpeg" (to obtain ffmpeg.asyncio) and "sounddevice" were installed afterward to correct errors. If the requirements and setup are the same as before, I'd imagine I'll still get those errors on a fresh install.

I also still haven't corrected that Cublas64 error line under Network Port in the diagnostics if it's of any consequence:

NETWORK PORT:
 Port Status : Port 7851 is available.
 **Cublas64_11 Path: Not found in any search path directories.**

Aside from those two spots, I'm not currently showing anything as missing or incorrect versions in the diagnostics, but I can post the full file if you need it.

The most recent install was done line by line, using the "manual installation" instructions for the standalone version to make sure each step went through. The environment is all standard, per those instructions. I did still get my "coqui-tts not found" error during the requirements install and am looking into the wheel building components for that now.

Thanks! 
![Newest Visual Studio](https://github.com/user-attachments/assets/860dc5b7-bd57-4cd3-bca4-a870de13e743)

**Comment by erew123** [comment]
Hi @Jidis83 

I've updated the diagnostics again, which should capture other versions of the C++ build tools.

**Please could you provide me a copy of your diagnostics.log fille?**

The CUBLAS issue, which I suspect goes along with your other issues, is that your Python cannot access the C++ build tools for compiling wheel files.

Things like Coqui-TTS and CUBLAS are downloaded from Python as WHL wheel files. The are files that are the instructions to build/compile the software for your specific system build. This is the base way Python works, so its not anything unusual, its certainly nothing specific to AllTalk. I suspect this is also the issue with the ffmpeg.asynco issue.

So, on Windows, if the C++ build tools and the Windows SDK aren't available/accessible for some reason, Python will download the WHL file for whatever, but it will fail to compile them.

Here is what I have done and what I am about to do:

1) I have used a Windows 11 virtual machine that had the build tools installed. I installed AllTalk V2 and that went through fine. 

2) I am resetting that Windows 11 virtual machine, so it will be as if it was a fresh installation. Its currently mid-process right now.

![image](https://github.com/user-attachments/assets/b7f93337-9801-4074-8bd0-08bf14e8c13e)
 
3) Once it is reset to a factory fresh build of Windows, I am going to:

- Install Git
- Git clone AllTalk V2

At this stage, you will note I am NOT installing the C++ Tools and SDK. I will test the install of AllTalk, which I know will therefore fail, but I want to sift through any error messages and also I have written a script to test wheel files, so I want to see exactly the errors that generates.

Once I know that has failed, I will wipe the AllTalk installation and git clone it again. However, this time I will install Visual Studio Community edition 2022 and confirm the selection choices required to have the C++ build tools and SDK.

If that fails, I will be working on the error/issue. If it works, ill feed back.

As you can imagine this takes X hours to test and go through, so I will reply back when I reply back.

Thanks

**Comment by MoeMonsuta** [comment]
Alltalk wouldn't install the wheels for me without the SDK and MSVC both installed. Kept getting the coqui wheel build error. I also had to installed transformers 4.40.0 to resolve dependency errors with coqui.

**Comment by Jidis83** [comment]
@erew123 -

Sorry for taking a bit to get back on this (and that I've split this discussion into two places).

I posted yesterday in the discussion section that I had gotten it to work, and that I suspected a messy Visual Studio install was involved somehow. I did get to dump my Windows 10 base partition image back on there last night and check things out by starting from scratch, and there was indeed a bunch of redundant C++ Redistributable junk already in my add-remove panel. That partition image was made before any specific VS, Python, or TTS related software was put on there, but there were a few audio and graphics applications installed, so I'm not sure if it came in with Windows. Either way, uninstalling all of them and installing _only_ what you instructed, then starting the Alltalk install seemed to do the trick. I'll include a picture of the original (pre-VS install) components I already had.

I also _did_ do the transformers downgrade Moe mentioned on the past couple runs. My install procedure was fairly simple after removing the old VS entries: 1. Visual Studio stuff 2. ESpeak 3. Git 2.46.2 64bit (at default install settings). I then did the command line procedure for the Alltalk standalone install and made my .bat files. I think I must have done the ESpeak install from one of my saved Alltalk folders, since I guess the installer won't actually come in until you pull in the whole Alltalk bundle. It might also be worth pointing out in the instructions that Alltalk itself will setup all that Python/Torch/CUDA stuff for you. On my first few installs, after seeing that separately listed in the main requirements, I was going out to find it and install it all on my own before I started the Alltalk setup, which probably didn't help. Whatever NVidia components were already on here were the standard drivers and stuff that Windows 10 put on.

I'll include the two diagnostic logs from before and after it was fixed, but it seemed like just those two items (VS and Cublas) were troublemakers for me.

Thanks Again! 

PS (regarding that wheel error) - I thought it did a bunch of successful wheel installs during the Alltalk setup and just complained about building the one for Coqui. It also reported a version when I checked, and looked as if the actual wheel package was on here and functioning.

![add-remove](https://github.com/user-attachments/assets/1241c688-ade0-4004-8670-931a9243bfc4)
[bad diagnostics.log](https://github.com/user-attachments/files/17180987/bad.diagnostics.log)
[good diagnostics.log](https://github.com/user-attachments/files/17180988/good.diagnostics.log)

**Comment by erew123** [comment]
@Jidis83 Thanks for the files. Yes the bad diagnostics has a lot of things missing. It does mainly look like Python PIP had an issue building wheel files.

Glad its resolved. Ill close the ticket.

Missing in Comparison (present in Base):
aiohappyeyeballs: 2.4.2
aiohttp: 3.10.6
aiosignal: 1.3.1
antlr4-python3-runtime: 4.9.3
anyascii: 0.3.2
av: 12.3.0
babel: 2.16.0
bitarray: 2.9.2
blis: 0.7.11
catalogue: 2.0.10
cloudpathlib: 0.19.0
coloredlogs: 15.0.1
confection: 0.1.5
coqpit: 0.0.17
coqui-tts-trainer: 0.1.5
coqui-tts: 0.24.1
ctranslate2: 4.4.0
cutlet: 0.4.0
cymem: 2.0.8
cython: 3.0.11
dateparser: 1.1.8
docopt: 0.6.2
encodec: 0.1.1
fairseq: 0.12.4
faster-whisper: 1.0.3
flatbuffers: 24.3.25
frozenlist: 1.4.1
fugashi: 1.3.1
fuzzywuzzy: 0.18.0
gruut-ipa: 0.13.0
gruut: 2.2.3
gruut_lang_de: 2.0.1
gruut_lang_en: 2.0.1
gruut_lang_es: 2.0.1
gruut_lang_fr: 2.0.2
hangul-romanize: 0.1.0
humanfriendly: 10.0
hydra-core: 1.3.2
inflect: 7.4.0
inputimeout: 1.0.4
jaconv: 0.4.0
jsonlines: 1.2.0
langcodes: 3.4.1
language_data: 1.2.0
levenshtein: 0.26.0
local-attention: 1.9.15
lxml: 5.3.0
marisa-trie: 1.2.0
mojimoji: 0.0.13
more-itertools: 10.5.0
multidict: 6.1.0
murmurhash: 1.0.10
num2words: 0.5.13
nvidia-cublas-cu11: 11.11.3.6
nvidia-cuda-nvrtc-cu11: 11.8.89
nvidia-cudnn-cu11: 9.4.0.58
omegaconf: 2.3.0
onnxruntime-gpu: 1.19.2
onnxruntime: 1.19.2
portalocker: 2.10.1
praat-parselmouth: 0.4.4
preshed: 3.0.9
pynndescent: 0.5.13
pypinyin: 0.53.0
pyreadline3: 3.5.4
pysbd: 0.3.4
python-crfsuite: 0.9.10
python-levenshtein: 0.26.0
pywin32: 306
pyworld: 0.3.4
rapidfuzz: 3.10.0
resampy: 0.4.3
rotary-embedding-torch: 0.8.3
sacrebleu: 2.4.3
smart-open: 7.0.4
spacy-legacy: 3.0.12
spacy-loggers: 1.0.5
spacy: 3.7.6
srsly: 2.4.8
sudachidict-core: 20240716
sudachipy: 0.6.8
tabulate: 0.9.0
thinc: 8.2.5
torchcrepe: 0.0.23
typeguard: 4.3.0
tzlocal: 5.2
umap-learn: 0.5.6
unidic-lite: 1.0.8
wasabi: 1.1.3
weasel: 0.4.1
word2number: 1.1
wrapt: 1.16.0
yarl: 1.13.1

Different Versions:
fastapi: 0.112.2 (Base) vs 0.115.0 (Compare)
networkx: 2.8.8 (Base) vs 3.2.1 (Compare)
pillow: 10.3.0 (Base) vs 10.4.0 (Compare)
transformers: 4.40.2 (Base) vs 4.43.3 (Compare)

Matching Versions:
absl-py: 2.1.0
aiofiles: 23.2.1
altair: 5.4.1
annotated-types: 0.7.0
anyio: 4.6.0
argbind: 0.3.9
asttokens: 2.4.1
attrs: 24.2.0
audioread: 3.0.1
brotli: 1.0.9
certifi: 2024.8.30
cffi: 1.17.1
charset-normalizer: 3.3.2
click: 8.1.7
colorama: 0.4.6
contourpy: 1.3.0
cycler: 0.12.1
decorator: 5.1.1
deepspeed: 0.14.0+ce78a63
descript-audio-codec: 1.0.0
descript-audiotools: 0.7.2
docstring_parser: 0.16
einops: 0.8.0
executing: 2.1.0
faiss: 1.8.0
ffmpy: 0.4.0
filelock: 3.13.1
fire: 0.6.0
flatten-dict: 0.4.2
fonttools: 4.54.1
fsspec: 2024.9.0
future: 1.0.0
gmpy2: 2.1.2
gradio: 4.32.2
gradio_client: 0.17.0
grpcio: 1.66.1
h11: 0.14.0
hjson: 3.1.0
httpcore: 1.0.5
httpx: 0.27.2
huggingface-hub: 0.25.1
idna: 3.7
importlib_metadata: 8.5.0
importlib_resources: 6.4.5
ipython: 8.27.0
jedi: 0.19.1
jinja2: 3.1.4
joblib: 1.4.2
jsonschema-specifications: 2023.12.1
jsonschema: 4.23.0
julius: 0.2.7
kiwisolver: 1.4.7
lazy_loader: 0.4
librosa: 0.10.2.post1
llvmlite: 0.43.0
markdown-it-py: 3.0.0
markdown2: 2.5.0
markdown: 3.7
markupsafe: 2.1.3
matplotlib-inline: 0.1.7
matplotlib: 3.9.2
mdurl: 0.1.2
mkl-service: 2.4.0
mkl_fft: 1.3.10
mkl_random: 1.2.7
mpmath: 1.3.0
msgpack: 1.1.0
narwhals: 1.8.4
ninja: 1.11.1.1
numba: 0.60.0
numpy: 1.26.4
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.3
parler_tts: 0.2
parso: 0.8.4
pip: 24.2
platformdirs: 4.3.6
pooch: 1.8.2
prompt_toolkit: 3.0.48
protobuf: 3.19.6
psutil: 6.0.0
pure_eval: 0.2.3
py-cpuinfo: 9.0.0
pycparser: 2.22
pydantic: 2.9.2
pydantic_core: 2.23.4
pydub: 0.25.1
pyee: 12.0.0
pygments: 2.18.0
pyloudnorm: 0.1.1
pynvml: 11.5.3
pyparsing: 3.1.4
pyqt6-qt6: 6.7.2
pyqt6: 6.7.1
pyqt6_sip: 13.8.0
pysocks: 1.7.1
pystoi: 0.4.1
python-dateutil: 2.9.0.post0
python-ffmpeg: 2.0.12
python-multipart: 0.0.10
pytz: 2024.2
pyyaml: 6.0.1
randomname: 0.2.1
referencing: 0.35.1
regex: 2024.9.11
requests: 2.32.3
rich: 13.8.1
rpds-py: 0.20.0
ruff: 0.6.8
safetensors: 0.4.5
scikit-learn: 1.5.2
scipy: 1.14.1
semantic-version: 2.10.0
sentencepiece: 0.2.0
setuptools: 75.1.0
shellingham: 1.5.4
six: 1.16.0
sniffio: 1.3.1
sounddevice: 0.5.0
soundfile: 0.12.1
soxr: 0.5.0.post1
stack-data: 0.6.3
starlette: 0.38.6
sympy: 1.13.2
tensorboard-data-server: 0.7.2
tensorboard: 2.18.0
termcolor: 2.4.0
threadpoolctl: 3.5.0
tokenizers: 0.19.1
tomlkit: 0.12.0
torch-stoi: 0.2.2
torch: 2.2.1
torchaudio: 2.2.1
torchvision: 0.17.1
tqdm: 4.66.5
traitlets: 5.14.3
typer: 0.12.5
typing_extensions: 4.12.2
tzdata: 2024.2
urllib3: 2.2.2
uvicorn: 0.31.0
wcwidth: 0.2.13
websockets: 11.0.3
werkzeug: 3.0.4
wheel: 0.44.0
win-inet-pton: 1.1.0
zipp: 3.20.2

Additional in Comparison (not in Base):
ffmpeg-python: 0.2.0
ffmpeg: 1.4
