### ISSUE TITLE
start_diagnostics.sh fails on Linux due to winreg import

### ISSUE THREAD

**Issue by Paladinium** [erew123/alltalk_tts#358]
**Version**
Using `alltalk_beta`.

**Describe the bug**
Running `start_diagnostics.sh` fails with
```
> ./start_diagnostics.sh 
Traceback (most recent call last):
  File "/alltalk/diagnostics.py", line 17, in <module>
    import winreg
```

**To Reproduce**
Run `start_diagnostics.sh` under Linux.

**Comment by erew123** [comment]
Hi @Paladinium 

Please `git pull` an update. Should be fixed now. Commit https://github.com/erew123/alltalk_tts/commit/0c5e1c44c883cbe9e41c1de7ea0d6f79f5082c29

Thanks

**Comment by Paladinium** [comment]
Thanks, this worked, but now there is another error. I'll create another issue for this.
