### ISSUE TITLE
I have a bunch of .pth files which are RVC finetunes that I want to use with alltalk

### ISSUE THREAD

**Issue by left1000** [erew123/alltalk_tts#360]
I have a bunch of .pth files which are RVC finetunes that I want to use with alltalk

Is this possible? I was thinking they'd be similar to alltalk finetunes? yes? maybe? no? Maybe they're already compatible? and I just don't know what folder to put them in in order to have them be recognized?

No matter where I put the RVC trained .pth files they don't load anywhere? 

<img width="1278" alt="image" src="https://github.com/user-attachments/assets/a6cf39ec-d69b-46cc-a28a-83b5819f0e94">

**Comment by erew123** [comment]
Hi @left1000 

I am away travelling atm, so limited access to reply etc. I believe the WIKI will cover the information you need though https://github.com/erew123/alltalk_tts/wiki/RVC-(Retrieval%E2%80%90based-Voice-Conversion)

Thanks

**Comment by left1000** [comment]
not a single mention of RVC here 
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/54bfaf18-0ae2-4eba-8ef0-845e5d077df4">


So there is some sort of initial foundational step I am unaware of :(

**Comment by erew123** [comment]
Yes, that is AllTalk version 1 and you need version 2 https://github.com/erew123/alltalk_tts/tree/alltalkbeta

**Comment by left1000** [comment]
I have installed alltalk2 and I have it "working"

But I have no idea what the RVC files are doing...

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/538374ec-d259-45f4-8434-66572e38eb66">



in RVC webui you take sample voice, then train, then create the .pth RVC file then use that file to convert bland TTS into great ai voice....

in alltalk2? you still need the sample voice AND the .pth RVC file? both? somehow? that doesn't make sense to me

**Comment by left1000** [comment]
okay my new main problem with alltalk2 is this 
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/1eb63714-340b-4f2a-85e9-39944dea48ab">

I can only download one model once ever, switching models doesn't seem to work reliably, and the alltalk start bat file only gives this choice once, every other time it launches it uses the previously chosen model option even if that model doesn't work and the bat hangs as a result :(
