### ISSUE TITLE
I cannot get parler to work on windows10 with alltalk2

### ISSUE THREAD

**Issue by left1000** [erew123/alltalk_tts#361]
In that I cannot get it to even attempt to start at all. With the downgraded transformers OR without the downgraded transformers, either way the result is.

![image](https://github.com/user-attachments/assets/13f3fde4-069a-4c66-900b-2ddc4a037ba3)

https://github.com/huggingface/parler-tts?tab=readme-ov-file#installation

Strangely it doesn't tell me on their github or your github what files I need to put in the models folder for parler? Sorry for such a n00b question.

**Comment by left1000** [comment]
There is a script for parler to download these files https://huggingface.co/parler-tts/parler-tts-mini-v1/tree/main so that's what I did manually.

**Comment by left1000** [comment]
I've uninstalled and reinstalled alltalk2 several times but I think I'll just live using xtts instead of parler for now.

**Comment by left1000** [comment]
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/a1c8f3f4-24d8-4f98-9dfd-5b262a423e05">


leads to 

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/f30da5b8-a176-4fa6-ad1a-86d8ea42db8d">

**Comment by left1000** [comment]
manually rename the folder to try to fit what it wants from me

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/495b4597-e304-4a7a-a875-a2ddbdfad07c">


<img width="1277" alt="image" src="https://github.com/user-attachments/assets/371da101-7ced-4781-8d4e-42ee1206363b">


I think it's not just my own idiocy but this isn't explained well...

**Comment by left1000** [comment]
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/d21c8f3b-ed95-432e-b2b1-ddb4542061e6">


<img width="1280" alt="image" src="https://github.com/user-attachments/assets/6411b684-7075-4db1-9771-dc67252fb37b">

**Comment by left1000** [comment]
underscores is correct 

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/f87e0cbc-017c-4c9e-8f3d-2677975f3734">


<img width="1047" alt="image" src="https://github.com/user-attachments/assets/170fe78b-a5aa-470e-a213-43ba96fbe2e2">


but the software generates the hypens instead, and the reason it didn't fix the first time I tried is that I bet I had to restart everything after swapping all the hypens into underscores

**Comment by left1000** [comment]
actually nevermind on closing this... it's likely a typo in the code someone should fix? possibly the typo is in the download functionality? but my personal problem is gone.

**Comment by erew123** [comment]
Hi @left1000 Please see here https://github.com/erew123/alltalk_tts/issues/331#issuecomment-2395211991
