### ISSUE TITLE
How is the BPE tokenizer training supposed to work?

### ISSUE THREAD

**Issue by Mixomo** [erew123/alltalk_tts#362]
Hi, it's me again, I know you are very busy so no need for an immediate response. Your work is appreciated :)

My question is not about how it works per se, but to know if indeed all talk uses the BPE tokenizer that has been trained in the inference, or embeds it somehow in the vocab.json or in the weights?

Since from what I was seeing, at the time of fine-tuning, all talk always uses the vocab.json of the base model (original or custom), and if then in the inference I manually point to the path of the vocab bpe custom, it gives me a missmatch error. 
I don't even know if the reasoning I am trying to apply is correct. 

Thank you very much in advance.

`    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Xtts:
        size mismatch for gpt.text_embedding.weight: copying a param with shape torch.Size([6681, 1024]) from checkpoint, the shape in current model is torch.Size([1431, 1024]).
        size mismatch for gpt.text_head.weight: copying a param with shape torch.Size([6681, 1024]) from checkpoint, the shape in current model is torch.Size([1431, 1024]).
        size mismatch for gpt.text_head.bias: copying a param with shape torch.Size([6681]) from checkpoint, the shape in current model is torch.Size([1431]).`

![image](https://github.com/user-attachments/assets/5409d7f8-ffed-4276-9a23-f9e699f3d824)

The trained tokenizer:
[bpe_tokenizer-vocab.json](https://github.com/user-attachments/files/17267955/bpe_tokenizer-vocab.json)

The used tokenizer:
[vocab.json](https://github.com/user-attachments/files/17267950/vocab.json)

P.S: 
And it is not because of the file names: bpe_tokenizer-vocab.json or renaming it to vocab.json gives the same error.

**Comment by erew123** [comment]
HI @Mixomo The code for it wasnt written by myself and the re-work that I am yet to pull in has been done by someone else. The whole converastion chain on that is here https://github.com/erew123/alltalk_tts/issues/276 and then in the PR https://github.com/erew123/alltalk_tts/pull/288 maybe that will help answer some questions.

The nutshell summay though is IEleven11 didnt feel the BPE tokeizer was working correcty and has re-worked it, so they will be the best person to ask questions to and outside of that, in their PR they have linked a video that goes into a deepr understanding of it.

**Comment by Mixomo** [comment]
All right, moving my question to that conversation. thanks
