### ISSUE TITLE
Install scripts fails on Linux while attempting to install parler requirements

### ISSUE THREAD

**Issue by Calajese** [erew123/alltalk_tts#365]
**Describe the bug**
Attempting to install or re-apply the requirements throws an error that the file "systemrequirementsrequirements_parler.txt" doesn't exist. Only standalone install tested.

**To Reproduce**
Run the script and choose either install or re-apply requirements.

**Desktop (please complete the following information):**
AllTalk was updated: 10/10/2024
Custom Python environment: no
Text-generation-webUI was updated: None, standalone install

**Additional context**
I've taken a look at the script and the lines 399 and 582 are using the wrong slash, accidentally escaping the next character rather than accessing the folder, changing the backslash to a forward slash fixes the issue

**Comment by Calajese** [comment]
Forgot to mention but this is on Version 2

**Comment by erew123** [comment]
Will close this post your PR. Again, thanks for the PR
