### ISSUE TITLE
add tortoise TTS?

### ISSUE THREAD

**Issue by lijackcoder** [erew123/alltalk_tts#367]
I was wondering if you could add Tortoise TTS? (specifically from https://github.com/JarodMica/ai-voice-cloning )  (I tested it out, and WOW.. it reminds me of the TTS of character.ai (when you do the voicecall option.) ( specifically the ultrafast mode with only 2 steps)

I think there is an old extension to sillytavern, but not sure if it stil works, nor  do I think it's optimal. With alltalk(beta) i think it is perfect to be able to switch engines and just use different TTS. (like you did with parler and SoVits and Piper)
(would be cool if you could somehow implement it. (I'm sorry I don't know how to really code. I started learning python a day ago lol. still got a long way to go.)

No pressure though.

**Comment by erew123** [comment]
Hi @lijackcoder I 60% did write the code for this, however, had a situation that has impacted my work currently, please see here for details https://github.com/erew123/alltalk_tts/issues/377

I have made sure this is clearly listed in the Feature Requests however, please see here https://github.com/erew123/alltalk_tts/issues/367

**Comment by lijackcoder** [comment]
all good. I hope everything is well.
