### ISSUE TITLE
Are you adding the New SOTA F5-TTS. This is really impressive

### ISSUE THREAD

**Issue by maxbizz** [erew123/alltalk_tts#371]
Github: https://github.com/SWivid/F5-TTS
Paper: [F5-TTS: A Fairytaler that Fakes Fluent and Faithful Speech with Flow Matching](https://arxiv.org/abs/2410.06885)
Demonstrations: https://swivid.github.io/F5-TTS/

Model Weights: https://huggingface.co/SWivid/F5-TTS

Im really impressed with this model. Its better than Xttx -v2 in my opinion.
Are you considering adding it to your awesome repo?

**Comment by aziib** [comment]
i need this too, i hope the dev will consider this.

**Comment by erew123** [comment]
Hi @maxbizz @aziib 

I have seen this and would like to take a shot at adding it at some point. However, it will be a little while away, reasons are explained [here](https://github.com/erew123/alltalk_tts/issues/377). 

I have added this to the feature request list https://github.com/erew123/alltalk_tts/discussions/74

Thanks
