### ISSUE TITLE
Alltalk TTS beta webui oobabooga on fresh install

### ISSUE THREAD

**Issue by spike4379** [erew123/alltalk_tts#372]
I thought I would move to a straight subject on the extension itself so I can clearly explain whats going on.

Installed oobabooga, ran it, closed. Ran cmd_windows and did a pip --version so the environment had some usage. Closed it.
extracted alltalk to extensions/alltalk_tts
Ran the atsetup, selected that I am using the webui, went to select re/apply requirements for text-gen and it pops up with

Enter your choice: 1
'pip' is not recognized as an internal or external command,
operable program or batch file.
'pip' is not recognized as an internal or external command,
operable program or batch file.
'pip' is not recognized as an internal or external command,
operable program or batch file.
** Faiss **
The system cannot find the path specified.
** FFmpeg **
The system cannot find the path specified.

   There was an error installing the requirements.
   Have you started your Text-gen-webui Python environment
   with cmd_{yourOS} before running atsetup.bat?
   Press any key to return to the menu.

I know this is wrong because I rand the cmd AND oobabooga itself to test that it works.

Moving on I manually installed the requirements from system/requirements/requirements_textgen.txt in cmd windows with pip install -r

(F:\ChatGPT\ooba4\installer_files\env) F:\ChatGPT\ooba4>pip install -r F:\ChatGPT\ooba4\extensions\alltalk_tts-alltalkbeta\system\requirements\requirements_textgen.txt
WARNING: Requirement './system/config/fairseq-0.12.4-cp311-cp311-win_amd64.whl' looks like a filename, but the file does not exist
WARNING: Requirement './system/config/fairseq-0.12.3.1-cp311-cp311-linux_x86_64.whl' looks like a filename, but the file does not exist
Processing f:\chatgpt\ooba4\system\config\fairseq-0.12.4-cp311-cp311-win_amd64.whl (from -r F:\ChatGPT\ooba4\extensions\alltalk_tts-alltalkbeta\system\requirements\requirements_textgen.txt (line 30))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'F:\\ChatGPT\\ooba4\\system\\config\\fairseq-0.12.4-cp311-cp311-win_amd64.whl'

Moving on I downloaded fairseq and put it in the place you labelled it as oobabooga/system/config

And reran it, worked fine. 

Next I went back to atsetup and chose option 6

6) Install DeepSpeed v14.0 for CUDA 12.1 and Python-3.11.x and PyTorch 2.2.x.

   DeepSpeed wheel file downloaded successfully.
   Installing DeepSpeed...
'pip' is not recognized as an internal or external command,
operable program or batch file.

   Failed to install DeepSpeed.
   Please check if the wheel file is compatible with your system.
   Press any key to return to the menu.

so I manually installed it with pip and alltalk still ran fine. however it wont enable deepspeed despite it being installed

running pip show --version deepspeed shows

(F:\ChatGPT\ooba4\installer_files\env) F:\ChatGPT\ooba4>pip show --version deepspeed
Name: deepspeed
Version: 0.14.0+ce78a63
Summary: DeepSpeed library
Home-page: http://deepspeed.ai
Author: DeepSpeed Team
Author-email: deepspeed-info@microsoft.com
License: Apache Software License 2.0
Location: F:\ChatGPT\ooba4\installer_files\env\Lib\site-packages
Requires: hjson, ninja, numpy, packaging, psutil, py-cpuinfo, pydantic, pynvml, torch, tqdm

It does generate audio as it did with the old version of alltalk its just no deepspeed is listed as active. And yes I had the mode set to xtts :)

I just want to also say that I love alltalk and the work you do on it. If there is anything I can try to do even though you have a wealth of knowledge above me I can test things to make this easier to use for new users.

These results were replicated again on a fresh install of windows 11 virtual machine.

I was unable to generate a log because it wont access the envs cmd

EDIT AFTER TESTING IN OOBA.

So as I mentioned earlier I got it working in ooba, in the page it also sets aside for itself localhost:7861 I can make it output audio fine.

In ooba itself however. I loaded a character and spoke to it, it generated a reply no problem, i enabled alltalk with the checkbox to activate [Enable TGWUI TTS] and when generating it errors with.

Llama.generate: 2244 prefix-match hit, remaining 1 prompt tokens to eval
llama_perf_context_print:        load time =     194.17 ms
llama_perf_context_print: prompt eval time =       0.00 ms /     1 tokens (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:        eval time =       0.00 ms /   136 runs   (    0.00 ms per token,      inf tokens per second)
llama_perf_context_print:       total time =    2310.73 ms /   137 tokens
Output generated in 2.84 seconds (47.60 tokens/s, 135 tokens, context 2245, seed 804840758)
[AllTalk API] Error with API request: output_file_name: output_file_name needs to be the name without any special characters or file extension, e.g., 'filename'.
[AllTalk TTS] Warning Error occurred during the API request: Status code:
400 Client Error: Bad Request for url: http://127.0.0.1:7851/api/tts-generate
[AllTalk Server] Warning Audio generation failed.  Status code:
Error occurred during the API request
Traceback (most recent call last):
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\gradio\queueing.py", line 566, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\gradio\blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\gradio\utils.py", line 583, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\gradio\utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\gradio\utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\site-packages\gradio\utils.py", line 742, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\modules\chat.py", line 437, in generate_chat_reply_wrapper
    yield chat_html_wrapper(history, state['name1'], state['name2'], state['mode'], state['chat_style'], state['character_menu']), history
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\modules\html_generator.py", line 326, in chat_html_wrapper
    return generate_cai_chat_html(history['visible'], name1, name2, style, character, reset_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\modules\html_generator.py", line 250, in generate_cai_chat_html
    row = [convert_to_markdown_wrapped(entry, use_cache=i != len(history) - 1) for entry in _row]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\modules\html_generator.py", line 250, in <listcomp>
    row = [convert_to_markdown_wrapped(entry, use_cache=i != len(history) - 1) for entry in _row]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\modules\html_generator.py", line 172, in convert_to_markdown_wrapped
    return convert_to_markdown.__wrapped__(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\modules\html_generator.py", line 78, in convert_to_markdown
    string = re.sub(pattern, replacement, string, flags=re.MULTILINE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ChatGPT\Ooba3\installer_files\env\Lib\re\__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

It doesnt matter if I am in chat-instruct or chat, it refuses to generate audio.

**Comment by erew123** [comment]
Hi @spike4379 

Please read [this here](https://github.com/erew123/alltalk_tts/issues/377). Apologies for your install problems, but I hope that may give you a way forward. If it does and you are happy with that resolution, please close the ticket for now. If not, feel free to leave it open and I will return to it when I can.

Thanks

**Comment by erew123** [comment]
Hi @spike4379 I assume that helped at least get you working for now. The requirements to update alltalk and make it work directly within the TGWUI Python environment are quite complicated this time and so will take me a while due to having to re-validate everything and also deal with various potential requirements issues (such as XTTS forcing a downgrade of transformers lower than the level TGWUI uses, which may possibly affect LLM loading/performance).

Using alltalk as a standalone and the TGWUI remote extension will be the best way forward for now.

Thanks
