### ISSUE TITLE
bug: alltalk dont start with textgen-web-ui

### ISSUE THREAD

**Issue by kalle07** [erew123/alltalk_tts#373]
i have updated textgen-webui ui, all runnign fine (btw older alltalk works fine 6 months ago)

install new alltalk today with activated enverionment (no errors while install)
DEEPSPEED FOR PyTorch 2.2.x (March 2024 builds of Text-gen-webui and later)
   6) Install DeepSpeed v14.0 for CUDA 12.1 and Python-3.11.x and PyTorch 2.2.x.

(i have an NVMD SSD and 4GHZ 16core and wait for 2min)
and i dont have any 1-2 GB model inside alltalk directory, should it download it automaticaly ?
and while the time i wait, no SSD, CPU or GPU usage.

e:\text-generation-webui>start_windows.bat
09:55:12-101059 INFO Starting Text generation web UI
09:55:12-104068 INFO Loading settings from "settings.yaml"
09:55:12-111059 INFO Loading the extension "gallery"
09:55:12-111059 INFO Loading the extension "alltalk_tts"
[AllTalk TTS] _ _ _ _____ _ _ _____ _____ ____
[AllTalk TTS] / \ | | |_ | | | | __ | | / |
[AllTalk TTS] / _ \ | | | | |/ ` | | |/ / | | | | _
[AllTalk TTS] / ___ | | | | | (| | | < | | | | ) |
[AllTalk TTS] // __|| ||_,|||_\ || || |____/
[AllTalk TTS]
[AllTalk TTS] Config file update: No Updates required
[AllTalk TTS] Start-up Mode : Text-gen-webui mode
Traceback (most recent call last):
File "E:\text-generation-webui\extensions\alltalk_tts\system\config\firstrun_tgwui.py", line 8, in
from inputimeout import inputimeout, TimeoutOccurred
ModuleNotFoundError: No module named 'inputimeout'
Error occurred while running the script: Command '['e:\text-generation-webui\installer_files\env\python.exe', 'E:\text-generation-webui\extensions\alltalk_tts\system\config\firstrun_tgwui.py']' returned non-zero exit status 1.
[AllTalk TTS] WAV file deletion : Disabled
[AllTalk TTS] Github updated : 5th October 2024 at 22:34
Traceback (most recent call last):
File "E:\text-generation-webui\extensions\alltalk_tts\tts_server.py", line 149, in
from ffmpeg.asyncio import FFmpeg
ModuleNotFoundError: No module named 'ffmpeg.asyncio'
[AllTalk TTS]
[AllTalk TTS] Startup timed out. Full help available here https://github.com/erew123/alltalk_tts#-help-with-problems
[AllTalk TTS] On older systems, you may wish to open and edit script.py with a text editor and change the
[AllTalk TTS] startup_wait_time = 240 setting to something like startup_wait_time = 460 as this will allow
[AllTalk TTS] AllTalk more time (6 mins) to try load the model into your VRAM. Otherwise, please visit the GitHub for
[AllTalk TTS] a list of other possible troubleshooting options.
09:55:48-374315 ERROR Failed to load the extension "alltalk_tts".
Traceback (most recent call last):
File "e:\text-generation-webui\modules\extensions.py", line 37, in load_extensions
extension = importlib.import_module(f"extensions.{name}.script")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "e:\text-generation-webui\installer_files\env\Lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1147, in _find_and_load_unlocked
File "", line 690, in _load_unlocked
File "", line 940, in exec_module
File "", line 241, in _call_with_frames_removed
File "e:\text-generation-webui\extensions\alltalk_tts\script.py", line 482, in
sys.exit(1)
SystemExit: 1
09:55:48-374315 INFO Loading the extension "whisper_stt"

Running on local URL: http://127.0.0.1:7860/

**Comment by kalle07** [comment]
[diagnostics.log](https://github.com/user-attachments/files/17354921/diagnostics.log)

**Comment by erew123** [comment]
Hi @kalle07 

Please read [this here](https://github.com/erew123/alltalk_tts/issues/377). Apologies for your install problems, but I hope that may give you a way forward. If it does and you are happy with that resolution, please close the ticket for now. If not, feel free to leave it open and I will return to it when I can.

Thanks

**Comment by kalle07** [comment]
i can wait  ;)

**Comment by erew123** [comment]
@kalle07 This is still in process and will be for a while. TGWUI's requirements have jumped quite a way. As such, other requirements have shifted such as the minimum DeepSpeed version is now v15.0. Unfortunately no-one (not Micorosoft, nor anyone else) had clear instructions/understanding of how to get DeepSpeed 15.0 building/working properly on Windows, so, Ive had to figure that out & build a tool to do that https://github.com/erew123/deepspeedpatcher

There is a large re-validation process to go through, as the whole system needs to be moved from PyTorch 2.2.1 to 2.4.x to work within TGWUI's own Python environment. (Standalone installation with the TGWUI Remote extension, which offers exactly the same features can be installed now without issue and will work fine). Re-validation will take ??? hours as that has to be performed across 2x platforms (Windows & Linux), every feature has to be tested and every TTS engine. So this will take me quite a while. Obviously I need to write documentation about caveats/issues that will occur, such as the fact that the XTTS coqui engine will downgrade transformers from the latest version, to 4.42, which may well have impacts on TGWUI's LLM loaders etc, again, this is all part of the validation process.

As I am currently away (130 miles from home) taking care of one of my last remaining family members whom is critically ill (mentioned here https://github.com/erew123/alltalk_tts/issues/377), my opportunities to work on this are limited, as I am only sporadically getting the opportunity to travel home, and of course, when I do, I am also dealing with other support issues etc.

At this time I would still suggest to install AllTalk as a Standalone and use the TGWUI remote extension.

Standalone install https://github.com/erew123/alltalk_tts/wiki/Install-%E2%80%90-Standalone-Installation
TGWUI remote extension https://github.com/erew123/alltalk_tts/wiki/Text%E2%80%90generation%E2%80%90webui-Remote-Extension

Thanks

**Comment by kalle07** [comment]
all fine ... Private matters come first!
