### ISSUE TITLE
Installing Deepseek on Windows

### ISSUE THREAD

**Issue by maglore9900** [erew123/alltalk_tts#375]
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
I want to try Deepseek. I see the readme in the local gui as well as the one here on github. Both say that atsetup.bat can be used to install the simple way, however I dont see it as an option when I run atsetup.bat. I am looking at the next alternative where I can use the precompiled wheels but I also dont see where I can get those for python 3.12. 

In the offchance that it was already installed, I attempted to enable deepseek, see second screenshot. But it doesnt seem to apply. see third screen shot.

**To Reproduce**
Review Docs, confirm atsetup.bat does in fact include deepseek install instructions.

**Screenshots**
![image](https://github.com/user-attachments/assets/1b6b821a-5151-43a3-a5e6-b2f9810fea7a)

![image](https://github.com/user-attachments/assets/5cdccfe2-8869-4df9-80ab-1db2971a3f55)

![image](https://github.com/user-attachments/assets/c00353e4-ea73-4822-be06-0757ecb28b5e)

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date] - I use the built in launcher, I restarted today and was marked as up to date. 
Custom Python environment: [yes/no give details if yes]
Text-generation-webUI was updated: [approx. date]

**Additional context**

**Comment by maglore9900** [comment]
and I found it. I installed it as a standalone tool. So I was choosing that in atsetup.bat.
choosing the other option showed me the deepseek install info I was looking for.

maybe note that in the docs?

**Comment by erew123** [comment]
Hi @maglore9900 Its mostly automated and clearer in AllTalk version 2 (I belive you are installing V1 from your above screenshot). Im not really updating V1 anymore. Well, I was hoping to push v2 fully live and out of BETA, but [this occured](https://github.com/erew123/alltalk_tts/issues/377)

**Comment by maglore9900** [comment]
Roger! good to know. Thanks. v1 has been such a blast I wasnt paying attention to v2. But I did get it working. Again, thanks for your quick responses.
