### ISSUE TITLE
Support requests availability & issues

### ISSUE THREAD

**Issue by erew123** [erew123/alltalk_tts#377]
## Current Support availability & coding/resolving issues.

Please scroll down for Coqui TTS, XTTS, Streaming & Text generation webui info. 

As of the 13th October 2024, I am still away travelling, taking care of an critically unwell family member. I have no access to code and fully test any changes. During the time I have been away, there have been updates to 

1) the Coqui TTS engine, which has 
- altered the versions of **some** other packages that are/need to be installed e.g. transformers.
- potentially altered how the Coqui XTTS engine performs streaming audio (not standard TTS generation).
2) Text-generation-webui has updated to a later version of Pytorch, which is core to many TTS engines like Coqui XTTS.

As such, some things may not be fully working, have issues, or partially work. As I dont have my main computer with me, just a very basic laptop, I cannot fully code and test changes, update all the requirements to ensure everything is 100% perfect etc. Though I will do this sometime in future, but my schedule as to when I can do this is unknown. I hope people can understand and I apologise for this, but my family has to come first. I am trying to reply to people on Github when I can find time and energy to do so, though of course, I am limited to provide some solutions at this time.

## Coqui TTS - Going back to the older version 0.24.1 (current/new build is 0.24.2)
Going back should drop the transformers requirements back to previous and Streaming with the Coqui XTTS engine should be back to pre-october changes. To change back you would:

Windows: `start_environment.bat` in the alltalk_tts folder.
Linux: `./start_environment.sh` in the alltalk_tts folder.

Once the Python environment has started:

`pip install --force-reinstall package_name==coqui-tts=0.24.1`

You WILL get a message about PIP not being able to confirm all version are correct and it may say there COULD be issues with other packages (the PIP depencency resolver will report this, typically in RED text).

## Text-generation-webui users
I would suggest that installing AllTalk as a [standalone installation](https://github.com/erew123/alltalk_tts/wiki/Install-%E2%80%90-Standalone-Installation) and using the [TGWUI Remote Extension](https://github.com/erew123/alltalk_tts/wiki/Text%E2%80%90generation%E2%80%90webui-Remote-Extension) will be your best bet. There is little difference in the actual operation, its just that AllTalk will be installed in its own Python environment and therefore use some extra disk space. 

## General other support issues
While I have been away, I have at least put a lot of effort trying to write the WIKI. Please read the:

- [General FAQ on AllTalk v2 use](https://github.com/erew123/alltalk_tts/wiki/FAQ,-Quirks-&-General-Questions)
- [Known errors and fixes](https://github.com/erew123/alltalk_tts/wiki/Error-Messages-List)
- [AllTalk Diagnostics](https://github.com/erew123/alltalk_tts/wiki/AllTalk-Diagnostics-Tool) which you can use to version match all Python packages with a known working set-up (Dont use this a TGWUI integrated installation). The procedure to version match is detailed on this linked page.

Thanks

**Comment by madey83** [comment]
Please expand F5-TTS with this F5 finetuned models: https://huggingface.co/Gregniuki/F5-tts_English_German_Polish/tree/main
