### ISSUE TITLE
I can't get Deepspeed installed, or cuda being detected....

### ISSUE THREAD

**Issue by phenix60** [erew123/alltalk_tts#386]
i spend a lot of time trying various thing to try getting alltalk installed with all it's feature but i can have deepspeed to be noticed even if i think it got installed or cuda to be detected on my nvidia gpu.

i'll try to resume shortly what i did: 
1- atsetup.bat or atsetup.sh never finish a correct install for me to just being able to launch alltalk, not sure why, but the .bat stop and close itself automatically at some point, and if i try the option 3 on the atsetup, it try to resume but close almost immediatly again and so i don't have the bat a the end to try to launch it, the atsetup.sh seem to finish it's install but when i try to launch the start alltalk.sh it close itself immediately, maybe missing file or idk.

2-Then i decided to try the manual install, by choosing a folder, and applying what wrote on the guide on the main page of the github
![image](https://github.com/user-attachments/assets/d737c968-c895-4e5a-82e7-bc58d1ce2ce6)

first time i did this it worked, i finally could launch Alltalk for the first time, but it didn't detected the cuda and i didn't pay attention at first to the missing install of deepspeed, i did it with the command "pip install {deep-speed-wheel-file-name-here}"  and not really sure about the version i should choose i made the install with th cuda 11.8 from the screenshoot below
![image](https://github.com/user-attachments/assets/e0f43821-b416-4056-b5d2-611110186a95)

but when i relaunch still nothing, no cuda detected no deepspeed detected either.
Then i saw a post in the faq about the pip package might not be be installed with their cuda version du to the pip cache file, i deleted all my pip cache, and do the manual installation again... where he downloaded fresh new pip package without using any cache one, since i deleted them all, here the result of this install in the screenchot below
![Capture d’écran 2024-10-22 195655](https://github.com/user-attachments/assets/86ea67e4-a96d-4efc-9078-339dc3368977)
 as you can see i make a redline under what i think be the install for cuda and for deepspeed, but you can see on the botom of the screen cuda and deepspeed doesn't by detected, and so the model loading in the cpu, and not the gpu like we can see on that screenshot
 ![image](https://github.com/user-attachments/assets/334bedb5-101a-4733-813a-d2aa085d2767)
 So now i'm a little lost on how to make deepspeed installation being detected or making alltalk detect the cuda...
 and can't use the atsetup to generate a diagnostic because the manual install, from following the guide setup the environement, not where the atsetup.bat is looking at. and don't really know how to do a manual install to make the envrionnement come to where the atsetup would look, because like i said i can't get the atsetup.bat or .sh to finish an install correctly ( by that i mean being able just to launch alltalk)

**Comment by erew123** [comment]
Hi @phenix60 

I see you are using AllTalk version 1, so the instructions below are for version 1.

#### atsetup.bat or atsetup.sh never finish 
Did you just double click on the file to run it **or** did you open a command prompt and run atsetup.bat? Double clicking on a batch file, from within windows and not at a command prompt, it will just exit when the script is completed and you **wont** see any resulting error messages.

#### Assuming you HAVE performed a manual install
From the command prompt window you would need to activate the alltalk conda environment.

`conda activate alltalkenv`

Once inside the environment, you would need to force Python to be installed with CUDA. I would suggest the following actions:

```
pip cache purge
```
to ensure the pip cache is clear, otherwise pip can **sometimes** not download a new version of PyTorch. Then you would run the following:

```
pip install torch==2.2.2+cu121 torchaudio>=2.2.2+cu121 --upgrade --force-reinstall --extra-index-url https://download.pytorch.org/whl/cu121
``` 

to force an installation of PyTorch 2.2.2 with CUDA 12.1

Obviously, watch out for any error messages.

It is possible you **may** have to reinstall the requirements file.

You can download a matching DeepSpeed wheel for PyTorch 2.2.2 with CUDA 12.1 here https://github.com/erew123/alltalk_tts/releases/download/DeepSpeed-14.0/deepspeed-0.14.0+ce78a63-cp311-cp311-win_amd64.whl

save that into the folder you are working in and **after** you have performed the PyTorch installation and while still in the alltalk conda Python environment, you can install it with 

```
pip install deepspeed-0.14.0+ce78a63-cp311-cp311-win_amd64.whl
```

And that should be it working. 

Though in fairness, can you perform all the above steps within atsetup:

On the Standalone menu, you would:

`5) Purge the PIP cache`

then

`4) Delete AllTalk's custom Python environment`

then 

`1) Install AllTalk as a Standalone Application`

Thanks

**Comment by phenix60** [comment]
i am using version 1 like what i shown you ? how should i do the above install you tell me, for installing the version 2 ? because i read on what you wrote on github it's must be much better  and is the version 2 compatible with an integration in sillytavern because that why i tried to install alltalk in the first place.

As for atsetup.bat and atsetup.sh, like i said i got different result the bat don't finish yes, but the sh seem to finish ( by that i mean on ce he's done i see the start_alltalk.sh th finetune  and env one, but launch the start one for exemple don't launch alltalk and just close immediatly, for the .bat, is close before finishing i presume, because when he do, i don't have the start_alltalk.bat and other file like that.
For both i was launching them with a double click, not by a command prompt

And thx really for answering me so quickly.

**Comment by erew123** [comment]
Hi @phenix60 

Version 2 is available on the link from the Github main page that redirects here: https://github.com/erew123/alltalk_tts/tree/alltalkbeta

You would more than likely be doing the Standalone installation: https://github.com/erew123/alltalk_tts/wiki/Install-%E2%80%90-Standalone-Installation

All the instructions for Version 2, including SillyTavern are in the WIKI: https://github.com/erew123/alltalk_tts/wiki

SillyTavern instructions on Version 2 is specifically here: https://github.com/erew123/alltalk_tts/wiki/SillyTavern-Extension

Thanks

**Comment by phenix60** [comment]
So i tried the standalone installation, following this link you gave me for v2 launching the atsetup.bat using the command prompt this time like the guide say, but at this point on the screenshot everything has stop, and has you can see. from the terminal and my folder.
![image](https://github.com/user-attachments/assets/72037aa5-0ce1-47cd-b1cf-954de07fdadf)
I dont have a files to launch alltalk 
so i try launching script.py in the env using conda but i got this
 ![Capture d’écran 2024-10-22 221801](https://github.com/user-attachments/assets/ce473770-190a-47f4-9e1c-2cf761f3cd16)
but since i did the install whith the atsetup.bat, i could generate this time a diagnostic log this time, hope this help...
[diagnostics.log](https://github.com/user-attachments/files/17481695/diagnostics.log)

**Comment by erew123** [comment]
This appears to be the people whom make faiss (Facebook actually) have updated their code and created a bug in their installer. They released a version 13 hours ago https://anaconda.org/pytorch/faiss-cpu/files (at time of me writing this).

![image](https://github.com/user-attachments/assets/88308379-abf3-45c7-b3d3-4b26f5f2cbf7)

I might be able to force an older version in the installer, but please give me a little time to look at this and I will get back to you.

**Comment by phenix60** [comment]
ok thanks, at least it's not something i did bad haha

**Comment by erew123** [comment]
I assume that Facebook will fix this quite quickly, but I put in place a temp workaround to install an earlier version. 

So at a command prompt, in your `alltalk_tts` folder, run `git pull` which should show atsetup.bat had a change to it, then you can re-run the setup and it should go through.

Thanks

**Comment by phenix60** [comment]
so i did do the git pull saw that he update the atsetup.bat, i then run the atsetup.bat in the command prompt, but wasn't sure if i needed to to the 2> 1,or the 2> 3, i did the 2>1 first and got this
![Capture d’écran 2024-10-22 233305](https://github.com/user-attachments/assets/0a5e59e8-2c03-4050-973a-af6273d7c567)
then seeing that was not working i tried the 2> 3 and got this, like before
![Capture d’écran 2024-10-22 233401](https://github.com/user-attachments/assets/d580f412-b74a-4d4a-82ca-453c461bd38f)

**Comment by erew123** [comment]
Ok, try this:

At a command prompt, in your `alltalk_tts` folder, run `git pull` (again) which should show atsetup.bat had a change to it.

DELETE the `alltalk_environment` folder

![image](https://github.com/user-attachments/assets/6a0b7c03-1dbb-425e-8ed6-c77d9840b67f)

Run `atsetup.bat` as normal, as if you are doing a brand new fresh install.

I have just tested this through in its entirety and it has installed fine.

![image](https://github.com/user-attachments/assets/e5a5862e-d80d-4fc7-8779-0700be5b938d)

So should work for you fine too.

Thanks

**Comment by phenix60** [comment]
yea almost there, so after the last update of the git pull i got the new atsetup.bat which lead me to this screen shot after he finish this time that installation and could launch the start_alltalk.bat, i choose a voice model like you can see on the screenshot, and he reconize the cuda and the deepspeed, which was great directly, but at the end of the screenshot it show it didn't detect the E-speak-ng, which i had installed before doing all this.
![Capture d’écran 2024-10-23 003410](https://github.com/user-attachments/assets/25314589-51cc-48cd-8de6-60385fff98b4)
but, i did like say on the screen close the terminal windows with ctrl+c and rerun le Espeak-ng installer, trying first the repair option as it was already installed, then relaunch " by the cmd prompt windows the start_alltalk.bat, but still the same about the Espeak-ng, i then close the cmd windows again with the ctrl+c, then launch the Espeak installer again choosing uninstall this time, and then again to reinstall it, then cmd windows to start again the Start_alltalk.bat but again the Espeak-nt is not detected, i'm not sure how it can affect alltallk, but that where am i actually

**Comment by erew123** [comment]
Please check the error message here in the WIKI https://github.com/erew123/alltalk_tts/wiki/Error-Messages-List

Espeak for Windows WAS NOT FOUND

Thanks

**Comment by phenix60** [comment]
i don't know why i didn't anything else after ma last post i went to sleep today, i try the first step from the link you gave me about the error message for espeak, with the espeak-ng --version command, and it show me, that he detect the version of Espeak immediately, i then try to launch the start_alltalk.bat, and now everything look perfect ^^

Thank a lot to have taken the time to help me figuring this out :) there the last picture of it finally working correctly .
![Screenshot_1](https://github.com/user-attachments/assets/e786ac29-bfba-48ba-9b9a-c206dcc812cc)
