### ISSUE TITLE
Fine tune, step-1 issue: cudnnCreateTensorDescriptor

### ISSUE THREAD

**Issue by whynotwork** [erew123/alltalk_tts#391]
Successfully loaded cudnn_ops64_9.dll without its dependencies. Successfully loaded zlib independently. Unknown dll missing.
Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor

**Comment by whynotwork** [comment]
It crashes right after this, have used xtts to train models in the past + finetune, just installed alltalk first time today and first time seeing this issue

**Comment by erew123** [comment]
@whynotwork 

It appears to be an update to ctranslate2 thats breaking this. References:

https://github.com/m-bain/whisperX/issues/901

https://github.com/OpenNMT/CTranslate2/issues/1806

In your alltalk_tts folder, run start_environment and then you can `pip install ctranslate2==4.4.0` which should downgrade ctranslate and all should be good again.

Thanks
