### ISSUE TITLE
Note - AMD ROCm 6.2 performance issues

### ISSUE THREAD

**Issue by NinjaPerson24119** [erew123/alltalk_tts#392]
Just a note on poor xttsv2 performance on AMD with ROCm 6.2. Doesn't seem like an issue with AllTalk necessarily.
 - EndeavourOS (Arch)
 - AMD 7900 XTX
 - Beta version
 - Standalone version

Running a simple sentence "Where am I?" takes 3s on my CPU (Intel 12700k), and 5s on the GPU. This is greatly exacerbated on larger inputs.

Downgrading to ROCm 6.0 results in <1s inference time.

Classic AMD.

**Comment by erew123** [comment]
@NinjaPerson24119 Thanks for the note on that as I dont have an AMD card, so cant test these things. Ill add a note linking back here to a couple of places on the site. 

Really appreciated

Thanks
