### ISSUE TITLE
PortAudio library not found

### ISSUE THREAD

**Issue by CodeShadower** [erew123/alltalk_tts#400]
**Describe the bug**
After installing alltalk_tts with its installation script and running it, it notifies me that the PortAudio library was not found.

**To Reproduce**
Steps to reproduce the behaviour: Standalone installation following this site's instructions.

- Ubuntu 24.04.01 LTS
- Python 3.12.3
- git clone https://github.com/erew123/alltalk_tts
- cd alltalk_tts
- ./atsetup.sh > Standalone
- sudo apt install libaio-dev (DeepSpeed prerequisite)
- ./start_environment.sh
- ./atsetup.sh > DeepSpeed

I then installed as suggested: sudo apt-get install portaudio19-dev

But this changed nothing, the PortAudio library is still undetected.

PS: The behaviour is the same with v2.0 Beta version.

**Screenshots**
![2024-11-08_19-02 alltalktts portaudio not found](https://github.com/user-attachments/assets/d367009b-22cf-4f2e-9726-dfe5f792dfe9)

**Text/logs**
[diagnostics.log](https://github.com/user-attachments/files/17682477/diagnostics.log)

**Desktop (please complete the following information):**
AllTalk was updated: 8th November 2024
Custom Python environment: No
Text-generation-webUI was updated: 8th November 2024

**Additional context**
I use alltalk_tts in conjuction with [amica](https://docs.heyamica.com/connecting-speech-options-tts/using-alltalk) and the text is properly recognized and displayed in the terminal window, but not audio file seems to be sent back. Could it be related with this PortAudio library missing?

I already tried the custom alltalk_tts installation from the amica website, link above, but it didn't change anything. Therefore, I deleted everything and re-installed everything according to alltalk_tts site instructions for Linux.

One can see in the above screenshot, that the chat bot is using the API properly as the speech is displayed. However, no audio gets back to the chatbot. Within the chatbot's window there is a message which is below. However, as the same Chatbot works as soon as I switch to another online TTS, I suspect that there is an issue with alltalk_tts.

![2024-11-08_19-33 Chatbot notifying about the error](https://github.com/user-attachments/assets/e7cd041f-c127-4909-b5d6-460da7dc73dd)

Chatbot config for alltalk_tts:

![2024-11-08_19-36 Chatbot config](https://github.com/user-attachments/assets/41ffc319-cb80-432b-8e26-fa2fc30a2d53)

Using the WebUI and converting to TTS works seamlessly:

![2024-11-08_19-39 WebUI working properly](https://github.com/user-attachments/assets/51c9b78e-8bea-48c7-bfbd-2eae54217742)

I tinkered days on a separate installation within the virtual environment, by searching the internet about PortAudio missing, but it always ends messed up.

**Comment by erew123** [comment]
Hi @CodeShadower 

### Amica generally
First off, I didnt know about Amica, but AllTalk v2 would need to have its API setting set to legacy. I quickly knocked up a WIKI page for this https://github.com/erew123/alltalk_tts/wiki/Amica-with-AllTalk-V2 so follow those instructions there.

### Quick Bug fix for updating the API reponse
**HOWEVER** I noticed a bug updating the API settings, so just put an update up on Github. To get the update, go into the `alltalk_tts` folder and `git pull` to get the update. It should update `script.py`

### Fixing Portaudio
I believe this will show if portaudio can be found on your system:

`ls /usr/lib/x86_64-linux-gnu/libportaudio*`

which should show something like

```
/usr/lib/x86_64-linux-gnu/libportaudio.so
/usr/lib/x86_64-linux-gnu/libportaudio.so.2
/usr/lib/x86_64-linux-gnu/libportaudio.so.2.0.0
```

or maybe

`pkg-config --libs portaudio-2.0`

which should show something like:

```
-L/usr/lib/x86_64-linux-gnu -lportaudio
```

You can force a reinstall of portaudio on Ububtu like this:

`sudo apt-get update`
`sudo apt-get remove --purge portaudio19-dev`
`sudo apt-get install portaudio19-dev python3-pyaudio`
`sudo apt-get install libasound2-dev`

This should ensure that portaudio is installed (it may also show up in Synaptic package manager if you use that).

Assuming all that bit is good, then the only other thing standing in the way, would be sounddevice in the Python environment. So you would:

`./start_environment.sh` in the alltalk_tts folder.

You can then:

`pip show sounddevice`

which should show its installed. If its not installed:

`pip install sounddevice`

and that should be all the requirements for the checks to pass.

Thanks

**Comment by erew123** [comment]
@CodeShadower Obviously, if you still have issues, please let me know. Thanks

**Comment by CodeShadower** [comment]
Thank you very much @erew123 for your quick and extensive answer for which I am really grateful. 😃

I'll try that for both versions 1 and 2 beta and give you feedback. Have a great weekend!

**Comment by CodeShadower** [comment]
So, here's my report.

For each of those installations (all deleted an restarted from scratch, as git pull -f didn't work somehow), the [API legacy mode](https://github.com/erew123/alltalk_tts/wiki/Amica-with-AllTalk-V2) was enabled:

![2024-11-09_13-53 alltalk_tts_v2_beta legacy setting](https://github.com/user-attachments/assets/d8198117-d667-449c-833b-6936369c4ff1)

1. Amica's specific installation of alltalk_tts, recives text input from Amica, produces no output sound and the PortAudio library is not recognized:

![2024-11-09_15-09 AMica Specific alltalk_tts conda installation](https://github.com/user-attachments/assets/c43e406d-b699-4fc8-94e8-f1d03a11ca0d)

2. alltalk_tts v1.9c (main) still has the PortAudio library error, receives Amica text inputs, but these are not spoken:

![2024-11-09_15-38 alltalk_tts_v1 Receives input but no output sound](https://github.com/user-attachments/assets/990eb70e-e8f7-4585-abb9-83e21c8222dc)

3. alltalk_tts v2 beta recognizes the installation of PortAudio, receives Amica's text input and speaks it out: :partying_face: :champagne: 

![2024-11-09_13-57 alltalk_tts_v2_beta output](https://github.com/user-attachments/assets/584071f8-d22c-4d1c-a811-5f7cf850fca1)

So, now I leave out 1. and 2. and continue debugging with 3. alltalk_tts v2 beta.

I tinkered a little bit with the API settings to check the result, but nothing changed:

![2024-11-09_15-18 alltalk_tts API Settings tweaks](https://github.com/user-attachments/assets/7b21d9b8-712f-43a0-9475-8c6911685b29)

I think from here on I need to contact Arbius, creator of Amica, and check with them as the TTS output doesn't seem to be processed properly by Amica. I'll keep you posted.

You've been a great help so far @erew123 , thank you very very much! :smiley: 

PS: I really hope your family issues could bes solved. :four_leaf_clover:
