### ISSUE TITLE
DeepSpeed did not install on standard windows standalone install.

### ISSUE THREAD

**Issue by tre4b** [erew123/alltalk_tts#406]
🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

[diagnostics.log](https://github.com/user-attachments/files/17779681/diagnostics.log)

**Describe the bug**
Alltalk is working but seemed slow and I noticed DeepSpeed could not be enabled.  I noted when All talk started I got the following message, one of which is DeepSpeed version not available.  I went into the conda environment and found there was no deepspeed.

I tried to install this but it would not install as it said pytorch was not available, sure enough this was not there in conda list either (nor were either in pip list).

I opened your batch file and went through section by section doing the installs manually.  DeepSpeed installed successfully and was visible in Conda list, however on start of Alltalk I still get the screen below.  

[AllTalk TTS]     _    _ _ _____     _ _       _____ _____ ____
[AllTalk TTS]    / \  | | |_   _|_ _| | | __  |_   _|_   _/ ___|
[AllTalk TTS]   / _ \ | | | | |/ _` | | |/ /    | |   | | \___ \
[AllTalk TTS]  / ___ \| | | | | (_| | |   <     | |   | |  ___) |
[AllTalk TTS] /_/   \_\_|_| |_|\__,_|_|_|\_\    |_|   |_| |____/
[AllTalk TTS]
[AllTalk TTS] Config file update: No Updates required
[AllTalk TTS] Start-up Mode     : Standalone mode
[AllTalk TTS] WAV file deletion : Disabled
[AllTalk TTS] Github updated    : 15th November 2024 at 00:40 Branch: alltalkbeta
[AllTalk ENG] Transcoding       : ffmpeg found
[AllTalk ENG] DeepSpeed version : Not available
[AllTalk ENG] Python Version    : 3.11.10
[AllTalk ENG] PyTorch Version   : 2.2.1
[AllTalk ENG] CUDA Version      : 12.1
[AllTalk ENG]
[AllTalk ENG] Model/Engine : f5tts - f5tts_v1 loading into cuda
[AllTalk ENG] Model/Engine : F5-TTS Ready
[AllTalk ENG] Load time : 4.96 seconds.
[AllTalk TTS]
[AllTalk TTS] API Address : 127.0.0.1:7851
[AllTalk TTS] Gradio Light: http://127.0.0.1:7852
[AllTalk TTS] Gradio Dark : http://127.0.0.1:7852?__theme=dark
[AllTalk TTS]
[AllTalk TTS] AllTalk WIKI: https://github.com/erew123/alltalk_tts/wiki
[AllTalk TTS] Errors Help : https://github.com/erew123/alltalk_tts/wiki/Error-Messages-List

What other steps need to be taken to ensure that DeepSpeed can be recognised by the system?

**Comment by erew123** [comment]
Hi @tre4b 

Please see the engine information for F5-TTS. It is not a DeepSpeed capable TTS engine:

![image](https://github.com/user-attachments/assets/fab322a8-1948-4224-acd8-b42ebcaf23b2)

Thanks
