### ISSUE TITLE
[AllTalk API] Error with API request: output_file_name: output_file_name needs to be the name without any special characters or file extension, e.g., 'filename'.

### ISSUE THREAD

**Issue by spike4379** [erew123/alltalk_tts#407]
I figured it would be easier to start a new support request here.

The special characters problem exists with the standalone install. on other characters in ooba with standard names it works perfectly fine but I have a character called "Victoria-" and my alltalk server console is showing this error.
[AllTalk API] Error with API request: output_file_name: output_file_name needs to be the name without any special characters or file extension, e.g., 'filename'.

I know I installed the server right because for every other usage it works fine, its just when a character has some text characters in the name it bugs out or something

Here's my process to replicate the problem.

Download oobabooga and install.
install alltalk as standalone and verify it generates audio fine using XTTS.
Copy the extension files into a new folder inside oobabooga/extensions/alltalk_tts

Run ooba and enable alltalk_tts, load the default example character and verify it receives audio from alltalk standalone,

Create new character named "Victoria-"
Attempt to load character at which point ooba sends the characters greeting to alltalk API for voice generation but this error starts.

Alternatively switch to a character that has a previous conversation history but also has a special character in the name, hit regenerate and the alltalk_tts standalone console will give the same error.

I appreciate the help. :)

**Comment by erew123** [comment]
@spike4379 

This is the line that is giving you that message:

https://github.com/erew123/alltalk_tts/blob/alltalkbeta/tts_server.py#L1228C5-L1228C187

#### Line 1228
```
output_file_name: str = Field(..., pattern="^[a-zA-Z0-9_]+$", description="output_file_name needs to be the name without any special characters or file extension, e.g., 'filename'.")
```

You can change it if you wish, however, I **believe** it may cause other processing issues here and there:

#### Line 1228 revised
```
output_file_name: str = Field(..., pattern="^[a-zA-Z0-9_-]+$", description="output_file_name needs to be the name without any special characters or file extension, e.g., 'filename'.")
```

Thanks

**Comment by spike4379** [comment]
Thanks, I see what is going on with this. That works for a character with '-' in the name but any with a space, or a '.' still error out.
Is there any way a package of some sort could be use to just translate them into something that isn't processed for the character names? So if there's a space in the name it just switches it to %20 or something?
I don't really know it's just I know a lot of people use characters with a 'special' character in their name. Hopefully in the future this could work somehow

**Comment by erew123** [comment]
@spike4379 I cant recall exactly what it did/didnt do when having special characters in the name e.g. Python goes funny about something, the narrator function fails or something odd on one/more of the TTS engines. It would take a while to re-validate all of that and see if it is possible to change it.

Are you literally putting a special character at the end of the character name? e.g. "mycharacter-". Or are you naming characters with a special character within the name? e.g. "mycharacter-1", "mycharacter-2", "mycharacter-3" etc?

**Comment by erew123** [comment]
Lucky for you I am on with a very large re-write and passed by that code, however this wont be around for at least a few days at best.

![image](https://github.com/user-attachments/assets/66adacc0-3369-4d0d-a5ef-93fe5dd067d9)
