### ISSUE TITLE
error during audio generation

### ISSUE THREAD

**Issue by Jaxlid** [erew123/alltalk_tts#409]
**Describe the bug**
when silly tavern responds and sends data to alltalk alltalk encounters an error and can't open ....\\null.wav system error

**To Reproduce**
just let answer the ia

**Screenshots**
![Capture d'écran 2024-11-17 104651](https://github.com/user-attachments/assets/9c3f3c29-9920-4fb1-be5a-a89d581a69c3)

**Text/logs**
[diagnostics.log](https://github.com/user-attachments/files/17789766/diagnostics.log)

**Desktop (please complete the following information):**
AllTalk was updated: just fresh install by you youtube video

**Comment by erew123** [comment]
Hi @Jaxlid 

I've no idea which alltalk extension you will be using, but please download and replace with this version:

https://github.com/erew123/alltalk_tts/blob/alltalkbeta/system/SillyTavern%20Extension/For%20AllTalk%20V2/alltalk.js

I've made sure the latest/final build is there.

Click the down arrow to save it

![image](https://github.com/user-attachments/assets/2b6cd4e2-c83f-44de-9b11-c10a563889d7)

Place the `alltalk.js` in your `\SillyTavern\public\scripts\extensions\tts\` folder, replacing the existing file.

This is the build that has been sent to StillTavern & approved and will be part of the next ST release.

Please note in the interface on ST you can select the AllTalk server version:

![image](https://github.com/user-attachments/assets/7577d642-3e98-47a5-90f5-1d8a34f9ef3a)

tested/confirmed working, both just now and also by ST.

![image](https://github.com/user-attachments/assets/c7f7f006-82bb-49e2-bf2c-9c98c594d79d)

Thanks

**Comment by Jaxlid** [comment]
hello sorry for the late response, I immediately did the manipulation and it works perfectly. Thanks a lot .Le 17 nov. 2024 13:42, erew123 ***@***.***> a écrit :
Hi @Jaxlid
I've no idea which alltalk extension you will be using, but please download and replace with this version:
https://github.com/erew123/alltalk_tts/blob/alltalkbeta/system/SillyTavern%20Extension/For%20AllTalk%20V2/alltalk.js
I've made sure the latest/final build is there.
Click the down arrow to save it
image.png (view on web)
Place the alltalk.js in your \SillyTavern\public\scripts\extensions\tts\ folder, replacing the existing file.
This is the build that has been sent to StillTavern & approved and will be part of the next ST release.
Please note in the interface on ST you can select the AllTalk server version:
image.png (view on web)
tested/confirmed working, both just now and also by ST.
image.png (view on web)
Thanks
