### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by west61224** [erew123/alltalk_tts#416]
**Is your feature request related to a problem? Please describe.**
I run my SillyTavern server with SSL enabled, this prevents the browser from connecting to the AllTalk API endpoint since it is not running via HTTPS. The browser just refuses to connect to it with the following error:
![Error](https://github.com/user-attachments/assets/3ee18a92-6c14-4eb5-84a7-e7e5b37b3651)

**Describe the solution you'd like**
I would like an option on the config file to provide the server with a cert and key file like SillyTavern does so both the AllTalk WebUI and API can be served via HTTPS.

**Describe alternatives you've considered**
You can enable mixed content [on a per site basis on Chrome](https://stackoverflow.com/questions/18321032/how-to-get-chrome-to-allow-mixed-content) desktop, but this is not an option on mobile.

**Additional context**
I was able to get the Gradio WebUI running on HTTPS by adding the certs to the root of the repo and modifying the following line:
https://github.com/erew123/alltalk_tts/blob/8f871a0601a36287444037b8c5979a895074a110/script.py#L2262
```
app.launch(server_name="0.0.0.0", server_port=params['gradio_port_number'], prevent_thread_lock=True, quiet=True, ssl_certfile="cert.pem", ssl_keyfile="key.pem",ssl_verify=False)
```
Unfortunately I wasn't able to get the API to be served via HTTPS.

**Comment by erew123** [comment]
@west61224 Just to let you know Im not ignoring you, just busy knocking off some bugs with the latest big release. I think I have a solution for what youre asking though, but there will obv be a bit of code work. Will get back to you in a couple of days.

**Comment by erew123** [comment]
@west61224 

I think you've run out of feature requests credits for the year! Well that was an arse of a job! :/

It should work though I cant say I have tested it to the n'th degree!

Documentation is built in, but also on the Wiki (there are some differences between the documentation) https://github.com/erew123/alltalk_tts/wiki/AllTalk-SSL-Proxy-System-%E2%80%90-Technical-Guide

![image](https://github.com/user-attachments/assets/b2693349-9342-40f4-8750-3df7a67dccaa)

Obviously `git pull` and re-install requirements!

Anyway, closing this ticket now. 

Thanks
