### ISSUE TITLE
Issue installing (doesn't finish install after CRYPT_E_NO_REVOCATION_CHECK)

### ISSUE THREAD

**Issue by Scrumpiss** [erew123/alltalk_tts#425]
![image-8](https://github.com/user-attachments/assets/fa020ca3-8036-4b18-8ef7-c2b869d728ed)
![image-9](https://github.com/user-attachments/assets/8709fc94-8f67-4df6-81e3-b03c8fbb2e48)
![image-10](https://github.com/user-attachments/assets/d4f9f57a-824e-4ea2-82d6-af2542c9d259)
When I run the installer, Curl has issues downloading deepspeed (known). I have downloaded the wheels before to install separately but either way it shouldn't REQUIRE them. When I try to re-run it another error appears saying "the system cannot find the batch label specified - RunScript". If I try to Re-Apply and Re-Update the requirements file - I get the same error multiple times and it exits installation.

Steps to reproduce the behaviour:
1. Follow standalone install process for windows
2. When the CRYPT_E_NO_REVOCATION_CHECK error occurs (I've tried to get around it with the suggested ways but it might be a firewall in my actual router rather than local so I'm not sure) select "N".

1. Run atsetup.bat again and select the standalone application.
2. Error - "the system cannot find the batch label specified - RunScript".

1. Run "Re-Apply/Update the requirements file".
2. CRYPT_E_NO_REVOCATION_CHECK when installing Deepspeed. Select "N" when asked to retry.
3.  Exits set up.

AllTalk was updated: 27/11/2024
Custom Python environment: no

**Comment by erew123** [comment]
@Scrumpiss Have you looked at the Wiki Known error messages? https://github.com/erew123/alltalk_tts/wiki/Error-Messages-List#alltalk-installation-issues

![image](https://github.com/user-attachments/assets/91dd1808-ec05-44e3-83f8-26b3943fa516)

**Comment by Spungyo** [comment]
> @Scrumpiss Have you looked at the Wiki Known error messages? https://github.com/erew123/alltalk_tts/wiki/Error-Messages-List#alltalk-installation-issues
> 
> ![image](https://private-user-images.githubusercontent.com/35898566/390403315-91dd1808-ec05-44e3-83f8-26b3943fa516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTAyMjIsIm5iZiI6MTczMjcwOTkyMiwicGF0aCI6Ii8zNTg5ODU2Ni8zOTA0MDMzMTUtOTFkZDE4MDgtZWMwNS00NGUzLTgzZjgtMjZiMzk0M2ZhNTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEyMTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNDUxZjkyYTVkNWQyYWI1NDExZjQ2NjcxYTMwMDZkM2RjOTdkNTBkYTljNGI5ZThjOTAyZDZjYmM2NWY3ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qzSZYvyY16GPzVt5ZPaD6I_PnACcRki73bxW8_8C7Uk)

I did and tried several of the fixes for the CRYPT_E issue. I already have the deepspeed wheels downloaded seperately so I don' t understand why something that's optional caused the setup to have so many issues. I just managed to get around it by doing the manual installation so I can skip the deepspeed part entirely. I managed to get deepspeed to work on the V1 AllTalk after downloading it separately so I'll try doing that here, too.

**Comment by erew123** [comment]
Did you update CURL?

If you wish you can change this line in atsetup.bat https://github.com/erew123/alltalk_tts/blob/alltalkbeta/atsetup.bat#L529 and add  `--ssl-no-revoke` after the -LO option.

The issue is a CURL problem or one with your system/internet. CURL first documented this on their site here https://github.com/curl/curl/blob/master/docs/SSL-PROBLEMS.md

Alternatively you can remove this entire section https://github.com/erew123/alltalk_tts/blob/alltalkbeta/atsetup.bat#L527-L586

One of those routes will resolve it for you.

Thanks

**Comment by Spungyo** [comment]
> Did you update CURL?
> 
> If you wish you can change this line in atsetup.bat https://github.com/erew123/alltalk_tts/blob/alltalkbeta/atsetup.bat#L529 and add `--ssl-no-revoke` after the -LO option.
> 
> The issue is a CURL problem or one with your system/internet. CURL first documented this on their site here https://github.com/curl/curl/blob/master/docs/SSL-PROBLEMS.md
> 
> Alternatively you can remove this entire section https://github.com/erew123/alltalk_tts/blob/alltalkbeta/atsetup.bat#L527-L586
> 
> One of those routes will resolve it for you.
> 
> Thanks

I did update Curl. I got around this problem by manual install and skipping the deepspeed step which I'm assuming is basically the same as removing that section from the set-up. Thanks. I'll keep those suggestions in mind in the future.

**Comment by Spungyo** [comment]
Nevermind, now I have a new issue. The server says it's running and I tried installing deepspeed which it says is working but when I open the ui it only shows the loading symbol.
![image-17](https://github.com/user-attachments/assets/ca7c64aa-cdd8-4761-8d70-9fe1d94a1077)
![image-19](https://github.com/user-attachments/assets/1565bc1c-47cf-44fa-9ac7-fc79fb860a64)

**Comment by Spungyo** [comment]
Can't even uninstall Deepseed lol. 
![image-14](https://github.com/user-attachments/assets/757495bc-19eb-48ab-acdd-f2a983920328)

**Comment by erew123** [comment]
Hey. Sorry to make this like a choose your own adventure but...You have 2 choices:

1) Delete the `alltalk_environment` folder, which is all the Python setup that `atsetup` did and re-run installation

![image](https://github.com/user-attachments/assets/74c30e37-1215-4956-ade1-ebb3a0a039d1)

OR

2) Delete `\alltalk_environment\env\Lib\site-packages\deepspeed` and probably also `D:\testingalltalk\alltalk_tts\alltalk_environment\env\Lib\site-packages\deepspeed-0.14.0+ce78a63.dist-info`

![image](https://github.com/user-attachments/assets/068a78dd-48e6-429b-81cf-d5bb0f0d57b0)

which will remove any remnants of their being a DeepSpeed packag.

Both routes are valid. Route 2 is quickest if its just DeepSpeed thats damaged.

**Comment by erew123** [comment]
Hi @Spungyo Hope your problem was solved. Let me know if not.

Thanks

**Comment by Spungyo** [comment]
> Hi @Spungyo Hope your problem was solved. Let me know if not.
> 
> Thanks

it was not. these are issues I have regardless of ATsetup and deepened it seems. Every time I reinstall it only works for a short amount of time before breaking like this with 0 explanation.
