### ISSUE TITLE
is deepspeed really on?

### ISSUE THREAD

**Issue by RASPIAUDIO** [erew123/alltalk_tts#429]
Hello and thanks for the great work!

I'm just wondering if I have the expected performances with the last xtts for a 14s generation it take 3.8s on an rtx4090, is it what is expected?

As logs show deepspeed but even if I turn it off in gradio it does not show as disabled, so I have no way to compare.

**Comment by erew123** [comment]
Make sure you have loaded your model with XTTS method

![image](https://github.com/user-attachments/assets/0a4fe4a4-4e87-4ed5-8785-3276ba866e5b)

If you have DeepSpeed on, it will show both an initial load of DeepSpeed occurring and then it will also show it after every generation

![image](https://github.com/user-attachments/assets/cd861a27-7c4f-46d9-903b-249c8cd7bb76)

RE "even if I turn it off in gradio it does not show as disabled" it required the mode be re-loaded.

Thanks

**Comment by RASPIAUDIO** [comment]
1-Mine is not showing "customs" just selecting xtts - xttsv2_2.0.3 then I click on "swap" and "load" different model : 
![image](https://github.com/user-attachments/assets/b3332a9e-941c-404d-b0b5-aa14bc15af35)
 
then if I go in TTS engine settings : 

2-![image](https://github.com/user-attachments/assets/9e81d83b-a7f5-4fb7-a6c5-0b0533b8ccac)
Even if I click on diasable and reload as in step 1 I have in the log : 
 
![image](https://github.com/user-attachments/assets/5cfe9022-1586-456b-bb49-c76e4fb5bf55)


Deepspeed true

I generate at x4 is it what is expected with xtts and a 4090?

**Comment by RASPIAUDIO** [comment]
ok I needed to stop start_alltalk and restart, sorry for the confusion!

So I get 4.5x at deepspeed and 2x without
