### ISSUE TITLE
API logs

### ISSUE THREAD

**Issue by RASPIAUDIO** [erew123/alltalk_tts#430]
Is there a way to see the api command that is used when using the gradio interface? This will save much time instead of forging a new command from scratch

thx

**Comment by erew123** [comment]
No there is not. All API  documentation and code samples are here in the Wiki

https://github.com/erew123/alltalk_tts/wiki#-api-documentation

**Comment by erew123** [comment]
e.g. https://github.com/erew123/alltalk_tts/wiki/API-%E2%80%90-Standard-TTS-Generation-API#example-requests

https://github.com/erew123/alltalk_tts/wiki/API-%E2%80%90-Standard-TTS-Generation-API#code-examples

**Comment by erew123** [comment]
Could I recommend you read this https://github.com/erew123/alltalk_tts/wiki/API-%E2%80%90-Best-Practices-AllTalk-API-Integration

**Comment by erew123** [comment]
Check debug options. Variables may be what you want https://github.com/erew123/alltalk_tts/wiki/AllTalk-V2-Debug-Options

Sorry on a mobile phone replying now..hence hard to reply in any length

**Comment by erew123** [comment]
Hi @RASPIAUDIO Hopefully my previous replies helped. Sorry they were short messages.

Let me know if you need further help.

Thanks
