### ISSUE TITLE
[FEATURE REQUEST] Audio Splitting more accurately with an llm

### ISSUE THREAD

**Issue by GoudaCouda** [erew123/alltalk_tts#431]
Would it be possible to implement an llm(even a very small one) to help split the audio files. I think with the transcriptions maybe we can feed it a prompt to determine normal stopping, breath, and change of sentences to aid in the splitting of audio samples. I think implementing a weighting system with this and the standard process could make for some more efficient samples.

**Comment by erew123** [comment]
Audio splitting in what? Finetuning? If so, someone else is doing work on that at the moment https://github.com/erew123/alltalk_tts/pull/419

**Comment by GoudaCouda** [comment]
Yea on the fine tuning

**Comment by erew123** [comment]
Ok, well it currently uses Whisper, which is a LLM in effect https://github.com/openai/whisper?tab=readme-ov-file#whisper and also Silero https://github.com/snakers4/silero-vad?tab=readme-ov-file#silero-vad and someone else is looking at other ways of splitting. I hope that answers the question? 

Thanks
