### ISSUE TITLE
The never working export buttons

### ISSUE THREAD

**Issue by Taluen79** [erew123/alltalk_tts#434]
![export_buttons](https://github.com/user-attachments/assets/42b678ad-6bb9-4afd-a767-72a60d056528)
Hi!

A while back I reported having issues with the "Export to WAV" and "Export to MP3" buttons in the TTS generator of Alltalk (see picture). Yesterday I made another attempt on the V2 beta version and I'm don't see any reaction at all when clicking on these buttons. I have tried on multiple computers, multiple different browsers (Brave, Firefox, Edge, Chrome) on both Linux and Windows.

For the love of god, is anyone else having this same problem? Do those buttons work for you? It seems like something that should have been noticed by many people by now. What mad magic browser are you using? It's driving me nuts.

I get no reaction from the browser when clicking on these button and no reaction from the command line output either. How should these button work?

At first I thought that it might be related to the fact that I'm using ngrok to access the webui. But even when trying using a browser on the local machine where Alltalk is running on, I still get the same behavior (which is no reaction at all).

Appreciate any clue anyone can give.

**Comment by erew123** [comment]
@Taluen79 Very probably a browser cache issue. Try clearing your browser cache OR just try another browser you havnt used the TTS generator in just to prove a point to yourself that its probably browser cache.

That's 99% probably going to be the issue. All code/behaviour for the export process is being run at/on your browser, so it has to be something browser based that would be the issue.

If that solves it, please close the ticket.

Thanks

**Comment by Taluen79** [comment]
I'm kinda out of idea what browser to test with. I have tested all the popular browsers on a few different PC, Windows 10 and Windows 11 and also on Ubuntu 20 and 22. What browser have you tested this on? One would think that at least one of all the combinations should yield some different result. But it is as if the buttons are not connected to any function.

If this is a dead-end and no on else is able to reproduce this, I guess there is no other choice than closing this issue. But it is weird as hell that only I have experienced this.

**Comment by erew123** [comment]
Have you cleared out your cache on you current web browser and tried re-opening the app?

https://its.uiowa.edu/services/general/how-clear-cache-and-cookies-your-web-browser

**Comment by erew123** [comment]
Here is a full list of troubleshooting steps:

1. **Use the Correct Address**:
   - Make sure to always open the app through the following link: `http://127.0.0.1:7851/static/tts_generator/tts_generator.html`. Opening the HTML file directly from the file system won't work correctly.

2. **Use a Compatible Browser**:
   - Please use an updated version of **Google Chrome** or **Mozilla Firefox** to run this app. Other browsers might not support all the features required.

3. **Check for Pop-Up Blockers**:
   - If you have a pop-up blocker installed in your browser, please disable it for `http://127.0.0.1:7851`. The app needs to open download links for exporting files.

4. **Enable JavaScript**:
   - Make sure JavaScript is enabled in your browser. The app depends heavily on JavaScript to generate and export the files.
   - If you don’t know how to enable JavaScript, search for "how to enable JavaScript in [your browser name]" on Google.

5. **Browser Security Settings**:
   - Please make sure your browser security settings allow file downloads and creating Blob URLs. The app uses these capabilities to export WAV or MP3 files.

6. **Check Console for Errors** (if you're comfortable doing this):
   - Right-click anywhere on the page, select **Inspect**, and then click the **Console** tab.
   - If you see any red error messages, please take a screenshot or share it, as it will help in troubleshooting further.

**Comment by erew123** [comment]
@Taluen79 are you opening it via the correct address from the Grado page, so that it opens `http://127.0.0.1:7851/static/tts_generator/tts_generator.html` OR are you browsing down the disk folder structure and clicking on the HTML file so that it opens something like this `"file:///alltalk_tts/system/tts_generator/tts_generator.html"`

You should be opening it from this link, within the Gradio interface:

![image](https://github.com/user-attachments/assets/94066675-d07f-43bc-8f2f-ce53b5f46419)

**Comment by Taluen79** [comment]
![alltalk_screenshot](https://github.com/user-attachments/assets/535f30fb-72da-48fa-a491-caf5af9ad051)

Please see the screenshot that was taken when using the Chrome browser with the address and everything. You can also see the console output when the button was clicked on. Yes, this page was navigated to via the Gradio page. All the settings for the browser was reset to default. After generating one sentence, I clicked on the two export buttons. But really it does not matter how many generations I've done, the behavior of these buttons are the same. However, the Export JSON and SRT seem to work as intended. It's just the WAV and MP3 button that seem to have issue.

**Comment by erew123** [comment]
Hi @Taluen79 

Thanks for the response. I have a copy of AllTalk V2 that I downloaded/setup fresh just 24 hours ago, so have tested with that. Below is a dump of things you can try/my knowledge on the subject. Nothing below is too complicated, but its up to you how far you want to go with this. There's maybe 2-3 minutes of just checking things/typing commands and outside of that it depends on anything you may have like Antivirus/Firewalling/VPN proxy's.

## OS's Tested

I tested on:
- **Windows 11**
    - Google Chrome (fresh install)
    - Brave Browser (my daily browser)
- **Ubuntu 22.04**.
    - Firefox
    - Chromium (fresh install)

All of these worked fine, with no complaints about MIME types. Screenshots down below.

## Testing the AllTalk server's response type

At a command prompt/terminal on the system running AllTalk,  you can type/copy-paste: 

`curl -I http://127.0.0.1:7851/static/tts_generator/crunker.esm.js`

Running this should show you what AllTalk is serving up the page as:

![image](https://github.com/user-attachments/assets/6f3f7c94-8774-4ff9-83b4-1829878d3cd8)

Specifically, it should say that the **`content-type:`** is **`application/javascript`**

## What if it DOESN'T say its **`application/javascript`**

If it doesn't say that it serving **`application/javascript`** then that leaves 2x possibilities:

1) Somehow you have ended up with an old/damaged version of Uvicorn web-server. You can start the AllTalk Python environment with `start_environment` for your OS and then `pip show uvicorn fastapi`

![image](https://github.com/user-attachments/assets/cdd30527-8626-4c7e-8d91-6e1933389220)

From my versions, I have 0.32.1 and 0.112.2. You can force your versions of these to upgrade with the following:

`pip install uvicorn==0.32.1`
`pip install fastapi==0.112.2`

2) Option number 2, if it doesn't show **`application/javascript`** is that something on your system is filtering JavaScript somehow. So think Antivirus, some kind of network hardware like a firewall, some kind of Proxy setup inc VPN software, something like that. You know your system better than I do. There is no way this should NOT respond saying it is **`application/javascript`** unless something on your system is somehow filtering/blocking it.

## What if it DOES say its **`application/javascript`**

If it does say its **`application/javascript`** **AND** your Uvicorn/FastAPI are up to date, yet in your browser console you are still seeing `Failed to load module script: Expected a JavaScript module but the server responded with a MIME type of 'text/plain' then something 100% is filtering the MIME type out, so you are back to Antivirus, Firewall, Proxy (Even some VPN software filters things nowadays). Those are the areas you would have to investigate.

## Test Results on my systems

![image](https://github.com/user-attachments/assets/b6ee7b32-13cd-419a-bdcb-5f28eb4df433)

![image](https://github.com/user-attachments/assets/453a9e28-43f8-4ee9-bace-84fb3f260b31)

![image](https://github.com/user-attachments/assets/74cabbd3-4c8d-4b34-90ad-de7281f8e8bf)

![image](https://github.com/user-attachments/assets/8fd12c8b-906e-465a-9812-7b4d4169b204)

**Comment by Taluen79** [comment]
Hi!

So I temporary shut off all the windows firewall and restarted the Alltalk server. Then I used curl as you suggested to check the mime type of crunker.esm.js and it looks like this:

![crunker mime type](https://github.com/user-attachments/assets/30260553-f1db-4933-94c8-40c5f3b9874e)

I also looked at the uvicorn version and it looks like this:

![uvicorn version](https://github.com/user-attachments/assets/9db2f5b0-fead-44c2-8281-e9390dd2619d)

So it seems that the uvicorn version is not the problem. But something is messing up the mime type. I have no idea what it might be. I'm ready to give up. So if there is nothing else that you can think of that can help debugging this issue, we can close this.

**Comment by erew123** [comment]
@Taluen79 Those versions look fine to me. I know the code in the backend is correct to pass the correct mime type over. The one and only other thing I have is to do a diagnostics compare which will generate a bunch of pip commands and you can just click the "Run PIP commands" button.

https://github.com/erew123/alltalk_tts/wiki/AllTalk-Diagnostics-Tool#generating-a-diagnostics-log

With that, it will compare a known working python environment against yours and version match everything automatically.

Appreciate you have been through a reasonable journey here. I will close the ticket. If you do decide to go ahead with the above you can still reply here.

Thanks

**Comment by Taluen79** [comment]
Hi!

So I used the diagnostic command line to generate a log file for my installation, specifically for the stand-alone version of Alltalk. Then I opened the GUI to compare it with the base diagnostic found in the system/config folder. There were some mismatch:

Different Versions:
aiohappyeyeballs: 2.4.3 (Base) vs 2.4.4 (Compare)
aiohttp: 3.11.7 (Base) vs 3.11.9 (Compare)
asttokens: 2.4.1 (Base) vs 3.0.0 (Compare)
boto3: 1.35.69 (Base) vs 1.35.72 (Compare)
botocore: 1.35.69 (Base) vs 1.35.72 (Compare)
grpcio: 1.68.0 (Base) vs 1.68.1 (Compare)
httpx: 0.27.2 (Base) vs 0.28.0 (Compare)
huggingface-hub: 0.26.2 (Base) vs 0.26.3 (Compare)
ipython: 8.29.0 (Base) vs 8.30.0 (Compare)
matplotlib: 3.9.2 (Base) vs 3.9.3 (Compare)
propcache: 0.2.0 (Base) vs 0.2.1 (Compare)
pydantic: 2.10.1 (Base) vs 2.10.2 (Compare)
pynvml: 11.5.3 (Base) vs 12.0.0 (Compare)
python-multipart: 0.0.17 (Base) vs 0.0.19 (Compare)
rotary-embedding-torch: 0.8.5 (Base) vs 0.8.6 (Compare)
ruff: 0.8.0 (Base) vs 0.8.1 (Compare)
tomli: 2.1.0 (Base) vs 2.2.1 (Compare)
typer: 0.13.1 (Base) vs 0.14.0 (Compare)
x-transformers: 1.42.17 (Base) vs 1.42.22 (Compare)
yarl: 1.18.0 (Base) vs 1.18.3 (Compare)

Additional in Comparison (not in Base):
cryptography: 44.0.0
en-core-web-md: 3.7.1
f5-tts: 0.2.1
loguru: 0.7.2
nvidia-ml-py: 12.560.30
pyopenssl: 24.3.0
win32-setctime: 1.1.0


I then used the "Run Pip Commands" in the GUI to align the versions. After this, I redo the whole process again just to see that every version is aligned. It it was. The second comparison after aligning all the packages only showed these differences:


Additional in Comparison (not in Base):
cryptography: 44.0.0
en-core-web-md: 3.7.1
f5-tts: 0.2.1
loguru: 0.7.2
nvidia-ml-py: 12.560.30
pyopenssl: 24.3.0
win32-setctime: 1.1.0


I then start the server to see anything has changed. But unfortunately, the behavior is the same. It's super weird. I might make another attempt on another PC with a NVidia GPU on a different network this weekend to see if there is any difference. But for now, this is it. Hopefully someone else can use this info for future reference, in case they find themselves in the same rabbit hole.

The reason why a little obsessed over this is because, as far as I know, there is no other open-source tts project that offers this feature to manage the different generations and glue them together into a coherent audio output right at the spot without going thru audacity or other tools. Somehow it feels almost like I'm being targeted by some evil force that just does not want me to use this.

**Comment by CheekyRaymondo** [comment]
This is my very first comment on githb ever, but this problem was driving me absolutely crazy!!!

My solution isn't the most elegant, but I used the solution in here:
https://github.com/janeczku/calibre-web/issues/896

Changed the registry entry for .js files to be application/javascript instead of text/plain !

You could also add a new entry for .esm.js files as I think my approach (just changing .js) might have messed up other projects Iuse, but I'll have to wait and see!

I hope this helps all!

**Comment by Taluen79** [comment]
@CheekyRaymondo Will try this out. Thanks! Good to know I'm not the only crazy one.

**Comment by CheekyRaymondo** [comment]
@Taluen79 no worries! I think this issue is probably a 'case-by-case' so would help if it was added to the known bugs section (if not already). Regardless - this project is amazing!
