### ISSUE TITLE
How can I start the evironment on mac?

### ISSUE THREAD

**Issue by desmeit** [erew123/alltalk_tts#435]
I'm on mac and the manual installation was successful. But how can I start the service? Sorry, but this is not in your docs:

https://github.com/erew123/alltalk_tts/wiki/Install-%E2%80%90-Manual-Installation-Guide

start_alltalk is not working

**Comment by erew123** [comment]
start your python environment and in the alltalk_tts folder, you would run `python script.py`

I cannot say how well it does or doesnt work on mac.

**Comment by desmeit** [comment]
okay I will check, thanks

**Comment by erew123** [comment]
Apologies I may have misconstrued your question. Pls see step 7 https://github.com/erew123/alltalk_tts/wiki/Install-%E2%80%90-Manual-Installation-Guide that should be the command
