### ISSUE TITLE
Potential Alltalk and SillyTavern communication issue

### ISSUE THREAD

**Issue by Olual** [erew123/alltalk_tts#437]
**Describe the bug**
Hello, I've been having a issue with running Alltalkv2 on the latest version of silly tavern. It seems as though from the images i provided below that Alltalk is connecting with Sillytavern, but there seems to be files it's creating that don't fit it's own validation rules? Just wondering if it's a issue on my end, or if Alltalk needs to be updated.

**To Reproduce**
Steps to reproduce the behaviour: Running
   SillyTavern: 1.12.8
   STL: 24.1.5.0
   Node.js: v22.11.0

**Screenshots**
![Screenshot 2024-12-03 172425](https://github.com/user-attachments/assets/4fe7dc9d-1172-4651-98be-550a56996d6e)
Narrator voices cannot be selected for some reason, as it is blank. 

<img width="867" alt="Alltalkv2 error message" src="https://github.com/user-attachments/assets/029d1352-6a64-4866-80af-61ecb0afe04d">
TTS works fine on its own, but doesn't work through SillyTavern

**Text/logs**
[AllTalk Startup]     _    _ _ _____     _ _       _____ _____ ____
[AllTalk Startup]    / \  | | |_   _|_ _| | | __  |_   _|_   _/ ___|
[AllTalk Startup]   / _ \ | | | | |/ _` | | |/ /    | |   | | \___ \
[AllTalk Startup]  / ___ \| | | | | (_| | |   <     | |   | |  ___) |
[AllTalk Startup] /_/   \_\_|_| |_|\__,_|_|_|\_\    |_|   |_| |____/
[AllTalk Startup]
[AllTalk Startup] Config file check      : No Updates required
[AllTalk Startup] AllTalk startup Mode   : Standalone mode
[AllTalk Startup] WAV file deletion      : Disabled
[AllTalk Startup] DeepSpeed version      : 0.14.0+ce78a63
[AllTalk Startup] Model is available     : Checking
[AllTalk Startup] Model is available     : Checked
[AllTalk Startup] Current Python Version : 3.11.10
[AllTalk Startup] Current PyTorch Version: 2.2.2+cu121
[AllTalk Startup] Current CUDA Version   : 12.1
[AllTalk Startup] Current TTS Version    : 0.22.0
[AllTalk Startup] Current TTS Version is : Up to date
[AllTalk Startup] AllTalk Github updated : 27th November 2024 at 19:45
[AllTalk Startup] TTS Subprocess         : Starting up
[AllTalk Startup]
[AllTalk Startup] AllTalk Settings & Documentation: http://xxx.x.x.x:xxxx
[AllTalk Startup]
[AllTalk Model] XTTSv2 Local Loading xttsv2_2.0.2 into cpu
[AllTalk Model] Coqui Public Model License
[AllTalk Model] https://coqui.ai/cpml.txt
[AllTalk Model] Model Loaded in 22.69 seconds.
[AllTalk Model] Ready
[AllTalk API] Error with API request: 1 validation error for JSONInput
narrator_voice_gen
  String should match pattern '^.*\.wav$' [type=string_pattern_mismatch, input_value='Please set a voice', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/string_pattern_mismatch
[AllTalk API] Error with API request: 1 validation error for JSONInput
narrator_voice_gen
  String should match pattern '^.*\.wav$' [type=string_pattern_mismatch, input_value='Please set a voice', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/string_pattern_mismatch
[AllTalk API] Error with API request: 1 validation error for JSONInput
narrator_voice_gen
  String should match pattern '^.*\.wav$' [type=string_pattern_mismatch, input_value='Please set a voice', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/string_pattern_mismatch
[AllTalk API] Error with API request: 1 validation error for JSONInput
narrator_voice_gen
  String should match pattern '^.*\.wav$' [type=string_pattern_mismatch, input_value='Please set a voice', input_type=str]
    For further information visit https://errors.pydantic.dev/2.6/v/string_pattern_mismatch

**Desktop**
AllTalk was updated: 27th November 2024 at 19:45
Custom Python environment: no 
Text-generation-webUI was updated: not used

**Additional context**
I'm not using the web UI, and the selectable voices appear for the user and character.

Thanks to anyone that reads this!

**Comment by erew123** [comment]
Must be because it is a legacy of the old settings vs the new. Please enable the narrator then you should be able to select a voice:

![image](https://github.com/user-attachments/assets/7dacd832-7c3c-45e5-800c-d5ef4c4a63a0)

**Comment by Olual** [comment]
I hid the endpoint, but everything else is the same. It still seems to not pull up anything.

https://github.com/user-attachments/assets/64ccd518-1ff4-4a59-a08d-e99ef76cb656

**Comment by erew123** [comment]
Ok, here is what I would propose then. 

In your `\SillyTavern\data\default-user` folder there is a text file called `settings.json`. **Make a copy of this file just so you have a fallback if needed. This is ALL your SillyTavern settings/setup, so you dont want to damage it**

Open the file in Notepad or whatever you have to open/edit text files.

Search for the word `alltalk` and you should end up at a section called `"tts": {`

![image](https://github.com/user-attachments/assets/ddbc8e28-a515-499c-a4b0-2bf2d0e7b7d7)

You are going to select everything in this section between the opening `{` and the closing `}`

![image](https://github.com/user-attachments/assets/54f96ab0-ac88-46ef-815b-2cad9ace0cca)

Delete that section out until you are left with `"tts": {},`

![image](https://github.com/user-attachments/assets/40710ddf-eaa3-4000-adfd-5ddd6c337e7e)

Close and restart StillyTavern

Go and setup TTS and voices as if you had a brand new copy of SillyTavern/AllTalk

If you accidentally damage the file, use the backup to replace it and try again. 

Please close this ticket if that resolves it.

Thanks

Thanks

**Comment by Sleb0** [comment]
I have the same issue as OP and this proposed fix did not work for me. To be clear, everything works fine for TTS for just the character and the user, but enabling any narrator settings creates the error, and there is never an option to select a narrator voice from the drop down. This is one of the main reasons I selected AllTalk over other options for TTS. Hope there are some alternative fixes!

FWIW, I am running SillyTavern 1.12.11 'staging'.
