### ISSUE TITLE
Restart Button

### ISSUE THREAD

**Issue by GoudaCouda** [erew123/alltalk_tts#439]
When using the API Endpoint im not able to change the models and update settings without shutting down the whole environment and running the bat file again.

It would be nice if there was a button in the UI that could do that

**Comment by erew123** [comment]
Im not quite sure I follow. Do you mean using API calls?

![image](https://github.com/user-attachments/assets/050aa75a-d2b8-40d5-941d-59d92f1ab5d3)

You would need to look at the control endpoints https://github.com/erew123/alltalk_tts/wiki/API-%E2%80%90-Control-and-Configuration-API#2-reload-configuration-endpoint

Specifically reload configuration to get the latest settings https://github.com/erew123/alltalk_tts/wiki/API-%E2%80%90-Control-and-Configuration-API#2-reload-configuration-endpoint

And reload/swap model to change the model https://github.com/erew123/alltalk_tts/wiki/API-%E2%80%90-Control-and-Configuration-API#3-reloadswap-model-endpoint

**Comment by erew123** [comment]
Hi @GoudaCouda 

As I've not yet heard back from you I'm not sure if I answered the question or not. I'm just maybe misunderstanding between talk of the API but also a button which suggests the gradio interface.

As far as reloading a tts engine afresh, with the settings stored on disk go, please see the quick start on Change TTS Engine.

https://github.com/erew123/alltalk_tts/wiki/AllTalk-V2-QuickStart-Guide#4-generate-tts-tab

If one of my two above answers cover your question, please let me know. 

Thanks
