### ISSUE TITLE
Russian language is not working

### ISSUE THREAD

**Issue by Dartvauder** [erew123/alltalk_tts#44]
**Diagnostics**
[diagnostics.log](https://github.com/erew123/alltalk_tts/files/13829368/diagnostics.log)

**Describe the bug**
When I was on version 1.7. Everything worked great. When I updated to 1.8. Russian language stopped working. It reads punctuation marks but not letters. English and other languages work fine.

**To Reproduce**
I have already reinstalled and updated the extension several times. I launched the extension in webui text and as standalone app.
Nothing helps. 

**Screenshots**
![image](https://github.com/erew123/alltalk_tts/assets/140557322/6457c98c-4c30-410a-b06a-72ee24357ec1)

**Text/logs**
In Screenshots

**Desktop (please complete the following information):**
AllTalk was updated: Today (04.01.2024)
Custom Python environment: No.
Text-generation-webUI was updated: Today (04.01.2024)

**Additional context**

**Comment by ke1ne** [comment]
It's because russian is a dead language not necessary in the modern world.

**Comment by erew123** [comment]
@Dartvauder Is this within the Text-Generation-WebUI? or the Demo Page? If you put something in the "Preview Text box" does that work? 

I guess what Im asking is, just guide me so I could re-create the problem. What would I have to do to make the problem occur?

**Comment by erew123** [comment]
@Dartvauder are we talking specifically Cyrillic characters e.g. Рад познакомиться с тобой

**Comment by erew123** [comment]
Ok.. Give me 10-20 minutes and I *should* be able to post an update......Ill just need to make a few changes and test...

**Comment by erew123** [comment]
Ok, one of two things is going to happen here...

1) I've just made a very quick update and its all going to work perfectly and everything will be glorious! 
2) I've just made a very quick update and broken something as I've not done lots of testing.. 😰

Pretty sure all should be good though. If you want to update with a git pull ... give it a test and it would be good it you can confirm that's fixed things for you (including on the Demo page).

Thanks!

![image](https://github.com/erew123/alltalk_tts/assets/35898566/4f6d4944-4e6a-4caf-a177-4c9414a94606)

**Comment by Dartvauder** [comment]
> Ok, one of two things is going to happen here...
> 
> 1. I've just made a very quick update and its all going to work perfectly and everything will be glorious!
> 2. I've just made a very quick update and broken something as I've not done lots of testing.. 😰
> 
> Pretty sure all should be good though. If you want to update with a git pull ... give it a test and it would be good it you can confirm that's fixed things for you (including on the Demo page).
> 
> Thanks!
> 
> ![image](https://private-user-images.githubusercontent.com/35898566/294177050-4f6d4944-4e6a-4caf-a177-4c9414a94606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzExOTEsIm5iZiI6MTcwNDM3MDg5MSwicGF0aCI6Ii8zNTg5ODU2Ni8yOTQxNzcwNTAtNGY2ZDQ5NDQtNGU2YS00Y2FmLWExNzctNGM5NDE0YTk0NjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEyMjEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyOWNmOWJjMDAzYTAzNWY0NjY2ODUzZmM4MDA5MDI2N2QwMWJjMjQ1NjI3M2VlYzhmYmEwYzEwYTQ1MGU1NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UX2m28ZnxpXzbIX5rtliBKe9bJDlXRZHqTmazF8p1_c)

Thank you very much. Everything works as before. The only thing. This message pops up in the terminal after starting generation:

[!] "Warning: The text length exceeds the character limit of 182 for language 'ru', this might cause truncated audio."

But still everything worked out as it should. Thanks again for such quick help!

**Comment by erew123** [comment]
Yeah, it will warn about anything over 250 characters for English. I didn't know Russian was only 182, probably because of the extra data overhead in the character set. You will always get this warning on longer messages though. However, I did implement text splitting before it actually hits the AI model, which **should**...... **should** deal with most issues around that, but you will still get the warning regardless. 

![image](https://github.com/erew123/alltalk_tts/assets/35898566/cf7da7df-88e7-4448-bfe0-a565daa6f38f)

As for generating other longer things outside of Text-gen-webui... thats all in the works!

Glad its fixed though! Thanks for letting me know!
