### ISSUE TITLE
add xtts2 improvement from this https://github.com/astramind-ai/Auralis

### ISSUE THREAD

**Issue by shivshankar11** [erew123/alltalk_tts#442]
**Is your feature request related to a problem? Please describe.**
add xtts2 improvement from this [https://github.com/astramind-ai/Auralis](https://github.com/astramind-ai/Auralis)

**Describe the solution you'd like**
xtts2 improvement

Auralis is a text-to-speech engine that makes voice generation practical for real-world use:

Convert the entire first Harry Potter book to speech in 10 minutes (realtime factor of ≈ 0.02x! )
Automatically enhance the reference quality, you can register them even with a low quality mic!
It can be configured to have a small memory footprint (scheduler_max_concurrency)
Process multiple requests simultaneously
Stream long texts piece by piece

Key Features 🛸
Speed & Efficiency
Processes long texts rapidly using smart batching
Runs on consumer GPUs without memory issues
Handles multiple requests in parallel
Easy Integration
Simple Python API
Streaming support for long texts
Built-in audio enhancement
Automatic language detection
Audio Quality
Voice cloning from short samples
Background noise reduction
Speech clarity enhancement
Volume normalization

**Comment by erew123** [comment]
Hi @shivshankar11 Thanks for the message about this, however I've already looked at this and you will find it mentioned as a possible tts engine here in the feature request list .https://github.com/erew123/alltalk_tts/discussions/74 Whilst it is interesting, the package requirements the developer has set are at the cutting edge extreme end of requirements.... Meaning it will impact lots of other things alltalk does and will take quite a bit of reverification.

I have a lot of other Dev bits going on at the moment so it's something I wouldn't be looking at until next year

Thanks
