### ISSUE TITLE
Add MARS5: A novel speech model for insane prosody

### ISSUE THREAD

**Issue by shivshankar11** [erew123/alltalk_tts#445]
**Is your feature request related to a problem? Please describe.**
Add MARS5 https://github.com/camb-ai/mars5-tts

**Describe the solution you'd like**
MARS5 TTS is more emotional sounding output than F5 TTS and clone voice and emotion from given audio source.

[tts-generation-webui](https://github.com/rsxdalv/tts-generation-webui) already support this.

**Comment by erew123** [comment]
Hi @shivshankar11 this is already in the feature request list. Please see here https://github.com/erew123/alltalk_tts/discussions/74
