### ISSUE TITLE
Really bad inference on newest Alltalk_v2

### ISSUE THREAD

**Issue by RenNagasaki** [erew123/alltalk_tts#450]
Hey,
I tried updating Alltalk from my version (13.07.24) to the current version (07.12.24) and suddenly the trained model sounds totally different and bad.

Did I miss a new important update? (Like Software to be updated or new ones to be installed)
I cloned the repo and used atsetup.bat.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.
Old diagnostics:
[diagnostics.log](https://github.com/user-attachments/files/18049976/diagnostics.log)
New diagnostics:
[diagnostics.log](https://github.com/user-attachments/files/18050369/diagnostics.log)

**Describe the bug**
Same settings, same model. Different (like totally different) sounding voice generation.
[Old working generation example](https://www.file-upload.net/download-15423104/Correct_Output.wav.html)
[New not working generation example](https://www.file-upload.net/download-15423103/Wrong_Output.wav.html)

**Comment by BigBoF** [comment]
Hello, I also have the same problem in English and French since the last update ^^
Each voice is different and even with the original settings and a clean install, the voice is not at all the same.

**Comment by erew123** [comment]
Looks like it's an issue with the latest coqui-tts engine..... I'm typing this reply on a mobile so... Fix incoming but will be a good few minutes https://github.com/idiap/coqui-ai-TTS/issues/198

**Comment by erew123** [comment]
Found the issue to be a problem with the latest Coqui TTS engine (not something Ive done thankully).

Downgrade by running:

- `start_environment.bat` (or .sh if on Linux)
- `pip install --force-reinstall coqui-tts==0.24.3`

All should be working fine again after that. Have set this in the reqirements files for new installations, so future installations shouldnt be an issue.

Thanks

**Comment by RenNagasaki** [comment]
Thank you for the fast reply and fix!

**Comment by eginhard** [comment]
Sorry about this. It should be back to normal now in version 0.25.1

**Comment by erew123** [comment]
@eginhard Thanks so much! I really do appreciate your work on Coqui (as I'm sure everyone above does). All the best.
