### ISSUE TITLE
Sweet bella sample now sound like a granny smoking 10 packs a day.

### ISSUE THREAD

**Issue by ShroomTip** [erew123/alltalk_tts#451]
Installation: webui main install and atsetup.bat upgrade

Diag: would be old/new audio comparison, tried varied temp-rep sets... just awful. 

Describe the bug: The upgrade is the bug? Audio samples seam useless.

Steps to reproduce the behaviour: Use my/available pitch perfect bella sample and hear coqui wreck it.

Screenshots: n/a

Text/logs: n/a

AllTalk was updated: Today 12/07/2024 and same as 'diagnostics'.

Additional context: Downgradable?

**Comment by erew123** [comment]
Found the issue to be a problem with the latest Coqui TTS engine (not something Ive done thankully).

Downgrade by running:

- `start_environment.bat` (or .sh if on Linux)
- `pip install --force-reinstall coqui-tts==0.24.3`

All should be working fine again after that. Have set this in the reqirements files for new installations, so future installations shouldnt be an issue.

Thanks
