### ISSUE TITLE
Portable version + dubbing

### ISSUE THREAD

**Issue by subof** [erew123/alltalk_tts#453]
Hi,
- I have a very slow Internet connection on one computer, and I use a corporate proxy on the other. I am unable to download and install all the numerous components on any of them. I would ask you for a portable version, especially for those who are not an expert in programming, but are engaged in the creative process. It could be updated when significant changes are made. I really hope that you will go to meet the content creators.
- In addition, I would ask you to add a tool for voicing of subtitles and perhaps even for translation using LLM. If this increases the size of the main program too much, then perhaps you could make a separate tool for subtitles.
- And my most incredible wish would be to ask you to release a tool for dubbing of videos in another languages with both original voices from the video and others. But I'm afraid I'm asking too much.
Best Regards

**Comment by erew123** [comment]
Hi @subof 

1) A portable build will be a docker build. Someone else is working on this and will be available in future, progress on that is here: https://github.com/erew123/alltalk_tts/discussions/378. You can also use that on 3rd party systems on the internet e.g. Hire a server. Alternatively you can use the Google Colab build for free https://github.com/erew123/alltalk_tts/wiki/Google-COLAB

2) There is python code here that will generate TTS from a subtitle file (with AllTalk). https://github.com/erew123/alltalk_tts/discussions/412. One day I will integrate this into the main interface, but I am deep in other code currently, so need to get that out the way first. As for translation and something like an LLM, if anything like that ever happened, that would be a long way down the road as that is adding a lot of additional complexity to the code, well out of scope for what the system currently does.

3) Re video dubbing, again, that may be too far out of scope. It would be a whole new area of code to learn and issues to deal with as re-encoding videos gets quite tricky. Ill keep it in the back of my head somewhere, but its not something I would jump on in any immediate way.

Thanks

**Comment by subof** [comment]
Re-encoding videos? I would suggest starting with something simpler, not setting the task of lip syncing, and focusing only on subtitles.
- A clean track with speakers can be obtained through something like UVR.
- Next, this track is used to clone the speakers' voices.
- The track with speakers is voiced in the target language of pre-translated subtitles* by voices that have been cloned or assigned from pre-prepared ones. 
The technology seems to have already reached a level where a small sample of up to 10 seconds is enough to clone a voice. Nevertheless, fine-tuning of the model can be carried out for better cloning.

* Subtitles can be translated via the local LLM API (ollama etc.) or by connecting via Api key services like OpenAI. But in any case, it is often quite a creative process that requires human involvement. Therefore, the connection of a pre-prepared translation is always the best option.
Thank you.
