### ISSUE TITLE
add whisper-large-v3-turbo for F5tts transcription

### ISSUE THREAD

**Issue by lijackcoder** [erew123/alltalk_tts#461]
**Describe the solution you'd like**
Whisper large but super fast, would be really nice to have. its openAI's newest transcription model i believe

**Comment by erew123** [comment]
Pretty sure thats already in there. Is this the model you mean:

![image](https://github.com/user-attachments/assets/b6a4cb84-8184-4ea7-be04-62788aaae134)

**Comment by lijackcoder** [comment]
Ah right thats it I. didnt update. thanks.
