### ISSUE TITLE
Question: it runs fine but on start-up some errors 

### ISSUE THREAD

**Issue by kalle07** [erew123/alltalk_tts#465]
its the stand alone version (on windows10)

**Describe the bug**
on start ...

[AllTalk TTS]     _    _ _ _____     _ _       _____ _____ ____
[AllTalk TTS]    / \  | | |_   _|_ _| | | __  |_   _|_   _/ ___|
[AllTalk TTS]   / _ \ | | | | |/ _` | | |/ /    | |   | | \___ \
[AllTalk TTS]  / ___ \| | | | | (_| | |   <     | |   | |  ___) |
[AllTalk TTS] /_/   \_\_|_| |_|\__,_|_|_|\_\    |_|   |_| |____/
[AllTalk TTS]
[AllTalk TTS] Start-up Mode     : Standalone mode
[AllTalk TTS] WAV file deletion : Disabled
[AllTalk TTS] Github updated    : 20th December 2024 at 21:42 Branch: alltalkbeta
[AllTalk ENG] Transcoding       : ffmpeg found
[AllTalk ENG] DeepSpeed version : 0.14.0+ce78a63
[AllTalk ENG] Python Version    : 3.11.11
[AllTalk ENG] PyTorch Version   : 2.2.1
[AllTalk ENG] CUDA Version      : 12.1
[AllTalk ENG]
[AllTalk ENG] Loading XTTS model xttsv2_2.0.3 on cuda
[AllTalk ENG] Model License : https://coqui.ai/cpml.txt
[AllTalk ENG] Model Loadtime: 11.65 seconds
[AllTalk TTS]
[AllTalk TTS] API Address : 127.0.0.1:7851
[AllTalk TTS] Gradio Light: http://127.0.0.1:7852
[AllTalk TTS] Gradio Dark : http://127.0.0.1:7852?__theme=dark
[AllTalk TTS]
[AllTalk TTS] AllTalk WIKI: https://github.com/erew123/alltalk_tts/wiki
[AllTalk TTS] Errors Help : https://github.com/erew123/alltalk_tts/wiki/Error-Messages-List
[AllTalk TTS]
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.f5tts.f5tts_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.parler.parler_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.piper.piper_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.vits.vits_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.xtts.xtts_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.f5tts.f5tts_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.parler.parler_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.piper.piper_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.vits.vits_settings_page - No module named 'extensions'
[AllTalk TTS] Error Module not found: extensions.alltalk_tts.system.tts_engines.xtts.xtts_settings_page - No module named 'extensions'
[AllTalk TTS] Please use Ctrl+C when exiting AllTalk otherwise a
[AllTalk TTS] subprocess may continue running in the background.
[AllTalk TTS]
[AllTalk TTS] Server Ready

i think all is running 
and the Available Engines: 
Xtts runs fine 

what that errors mean ?

**Comment by erew123** [comment]
Please see my reply on your other post about not installing into the TGWUI Python environment and the correct way to install currently
