### ISSUE TITLE
options for tuning the RVC voice 

### ISSUE THREAD

**Issue by kalle07** [erew123/alltalk_tts#468]
the convertion from a wav file with an trained RVC is very simple okay 

but maybe take a look and copy/paste this options from it makes the voice much better/smoother
RVC-webui

https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI
![grafik](https://github.com/user-attachments/assets/dc58b671-0891-42ec-96f5-fcf00a92c786)

**Comment by erew123** [comment]
You are welcome to set any settings you wish in the RVC settings interface as you wish:

![image](https://github.com/user-attachments/assets/5f01c4e7-a680-477a-969d-ad2935c70851)

The same settings are available there

**Comment by kalle07** [comment]
oh waoow , thx
