### ISSUE TITLE
float16 error in finetune.py

### ISSUE THREAD

**Issue by davidtorcivia** [erew123/alltalk_tts#61]
Attempting to run finetune.py directly (cli in text-gen environment, etc via `python finetune.py`) and it starts fine, but upon running step 1, regardless of Whisper model (v2 or v3, etc), I get the following traceback (entire cli dump):

```bash
Running on local URL:  http://127.0.0.1:7052

To create a public link, set `share=True` in `launch()`.
[FINETUNE] [94mPart of AllTalk[0m https://github.com/erew123/alltalk_tts/
[FINETUNE] [94mCoqui Public Model License[0m
[FINETUNE] [94mhttps://coqui.ai/cpml.txt[0m
[FINETUNE] [94mStarting Step 1[0m - Preparing Audio/Generating the dataset
[FINETUNE] Updated lang.txt with the target language.
[FINETUNE] Loading Whisper Model: large-v2
Traceback (most recent call last):
  File "C:\MODELS\text-generation-webui\extensions\alltalk_tts\finetune.py", line 987, in preprocess_dataset
    train_meta, eval_meta, audio_total_size = format_audio_list(target_language=language, whisper_model=whisper_model ,out_path=out_path, gradio_progress=progress)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MODELS\text-generation-webui\extensions\alltalk_tts\finetune.py", line 112, in format_audio_list
    asr_model = WhisperModel(whisper_model, device=device, compute_type="float16")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MODELS\text-generation-webui\installer_files\env\Lib\site-packages\faster_whisper\transcribe.py", line 130, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
```

This was running a week ago, but now I get this error and I'm not sure why. I've deleted and recreated alltalk_tts via fresh git clone, double checked requirements installed, fully updated text-gen AND then reran alltalk requirements (to replace panda, etc) and the error persists. `nvcc --version` shows `Cuda compilation tools, release 11.8, V11.8.89`. I've removed and redownloaded the faster-whisper models themselves from the huggingface hub cache, etc. Problem persists if I run through text-gen UI as well.

I feel like I'm overlooking something simple but I'm not sure what more to try.

[diagnostics.log](https://github.com/erew123/alltalk_tts/files/13891501/diagnostics.log) is attached.

**Comment by erew123** [comment]
Hiya.. When you ran the diagnostics, you were in the Text-gen-webui `cmd_windows.bat` python environment?

![image](https://github.com/erew123/alltalk_tts/assets/35898566/e703e280-0a3f-4ed2-8828-a358d4487696)

The reason I ask, is its not showing you as having Pytorch with CUDA installed, so it wont find your GPU via CUDA, which is what it needs. 

I don't know if this is something with the Text-gen-webui installation that occurred recently or this is just co-incidence, but your the second person Ive seen in a few days not showing CUDA.

I dont know if you installed text-gen-webui with CUDA 12.1 or 11.8....... you can force a re-install on your text-gen-webui environment by....

`cmd_windows.bat` in the text-gen-webui folder to start then Python environment

`pip cache purge (Clear the current Pip cache)`

`pip uninstall torch torchaudio`

You can now either install the CUDA 11.8 or 12.1 version of Torch and Torchaudio with one of the following

CUDA 11.8 > `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

CUDA 12.1 > `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`

**Comment by erew123** [comment]
This was from the other person a few days ago.. also no cu118 or cu121 (Cuda 11.8 and 12.1 respectively)

![image](https://github.com/erew123/alltalk_tts/assets/35898566/ffa08f44-cf38-41b8-a60c-d8a979ea737a)

**Comment by davidtorcivia** [comment]
This corrected it, I don't know why pip wasn't installing these properly. Everything has been run within the text-gen-webui env (`cmd_windows.bat`).

Just to append your commands in case someone else comes through later looking for a solution, if we're reinstalling torchvision for cu118 (or 121) then we need to run `pip uninstall torch torchaudio torchvision` (uninstall torchvision was missing). The install command is correct.

So the full fix is:

Enter the python environment `cmd_windows.bat`

`pip cache purge` (to rebuild clean)

`pip uninstall torch torchaudio torchvision` (remove old torch without cuda)

`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` (install with cuda 11.8, change this to `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121` for cuda 12.1)

**Comment by realtica** [comment]
> This corrected it, I don't know why pip wasn't installing these properly. Everything has been run within the text-gen-webui env (`cmd_windows.bat`). Might want to update `diagonostic.py` to ensure the cuda accelerated torch versions are present as it currently shows them as "green" in the cli even without `+cu118`, etc.
> 
> Just to append your commands in case someone else comes through later looking for a solution, if we're reinstalling torchvision for cu118 (or 121) then we need to run `pip uninstall torch torchaudio torchvision` (uninstall torchvision was missing). The install command is correct.
> 
> So the full fix is:
> 
> Enter the python environment `cmd_windows.bat`
> 
> `pip cache purge` (to rebuild clean)
> 
> `pip uninstall torch torchaudio torchvision` (remove old torch without cuda)
> 
> `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118` (install with cuda 11.8, change this to `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121` for cuda 12.1)

Same here, thanks for the solution, I have alltalk_tts standalone, is it necessary to install Text-gen-webui?

**Comment by erew123** [comment]
Hi @realtica AllTalk will run fine without text-generation-webui and you can perform finetuning.

Thanks

**Comment by Jack74r** [comment]
Hi, thanks for your post. I've tried to follow your advice but I'm having a problem using the project for finetuning.
The installed version displays 121 so I have uninstalled and reinstalled version 218. But still the problem, and I redo the manipulation it still displays 121 but when I uninstall it displays 218 so I'm a little lost. I don't really know python.
Otherwise, everything else works fine :)

![WindowsTerminal_UxdQSEZ042](https://github.com/erew123/alltalk_tts/assets/25966996/bbb12d2d-ff3d-4178-bf83-88b491e15205)

**Comment by erew123** [comment]
Hi @Jack74r 

Here is a quick explainer of Python environments from the main page in the installation section:

_______________________________________________________________________
**A very quick understanding of Python Environments.**
Different Python applications have different requirements, some of those requirement’s conflict with other Python applications requirements. To work around this problem, you can create different Python environments that remain separated from one another. A simple way of looking at Python environments, is just like how your house has different rooms for specific purposes (Kitchen, Bathroom, Bedroom etc). You can create a Python environment that is built/customised specifically for your current applications needs/purposes and will not interfere with any other Python applications environments/installations.

If you are adept at managing Python environments, have an existing Python environment and know that you won’t cause any conflicts by installing AllTalk's requirements within that Python environment, then load up your Python environment and install the requirements. For everyone else, here is a basic guide on installing AllTalk in its own custom Python environment (there will be small variations between OS's, but the principle is the same).
_______________________________________________________________________

I have to admit, python environments are confusing at first.

So are you running AllTalk in a standalone installation? (I am guessing you are based on your screenshot).

From your screenshot, it doesnt look like you have started the AllTalk python environment first. I am assuming you have run the `atsetup.bat` file to create the custom AllTalk python environment?

Once this has been created, you would then start AllTalk with `start_alltalk.bat` which will load the Python environment and then AllTalk OR **(for finetuning)** you just want to load the Python environment, you would run `start_environment.bat`

When you run `start_environment.bat` you should see the command prompt changes, kind of similar to this (this is an example of a Python environment being loaded and you can see the way the command prompt changes, indicated by the line that the orange arrow points to)

![image](https://github.com/erew123/alltalk_tts/assets/35898566/c5b64241-98b9-460c-bc6d-d5cc276f3e29)

Once you are in the Python environment for AllTalk, its now where you want to install any other requirements with PIP and also if you are finetuning e.g. `pip install -r requirements_finetune.txt`

You would also check that the set environment path is listing `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin` which you can check at the command prompt with the `set` command.

feel free to ask questions if you need. 

Thanks
