### ISSUE TITLE
API returned incorrect path url.

### ISSUE THREAD

**Issue by Dolyfin** [erew123/alltalk_tts#66]
**Describe the bug**
"output_file_path" and "output_file_url" returned incorrect path to the output (without '_combined') wav file when using the API.

![image](https://github.com/erew123/alltalk_tts/assets/55581931/111c0a17-9c4e-46b3-a620-b3d226a68e17)

Returned JSON:
```json
{"status": "generate-success", "output_file_path": "C:\\text-generation-webui-main\\extensions\\alltalk_tts\\outputs\\1110117857783713802_1_combined.wav", "output_file_url": "http://192.168.0.99:7851/audio/1110117857783713802_1.wav", "output_cache_url": "http://192.168.0.99:7851/audiocache/1110117857783713802_1.wav"}
```

Real file on disk
`1110117857783713802_1_combined.wav`
URL links to:
`1110117857783713802_1.wav`

**To Reproduce**
![image](https://github.com/erew123/alltalk_tts/assets/55581931/e081a277-ef4e-4311-922f-aa7052756ab7)

Unsure if this was intended.
I looked into the code here:
![image](https://github.com/erew123/alltalk_tts/assets/55581931/bbf38db1-15cc-4e3a-ab40-117e444c1028)

**Comment by erew123** [comment]
You've got me bang to rights on that one! An honest mistake with that one. I've corrected it in the live code. I'm guessing you've changed it, but if not you're welcome to git pull an update.

Thanks for giving me nice clear detail on the problem. That made it super easy to track and fix!
