### ISSUE TITLE
Training writes to disk as checkpoints frequently. Option to use RAM instead.

### ISSUE THREAD

**Issue by Urammar** [erew123/alltalk_tts#72]
I have a very fast SSD, but has limited writes over its lifespan. I have 64gb of ram barely being used during training, and this number will only grow over time im sure.

Please consider adding an option to store temporary checkpoints or whatnot thats currently being written to disc currently, to RAM instead, so hard disk access is kept to a minimum.

This is an awesome project, btw.

**Comment by erew123** [comment]
**This is an awesome project, btw.** Thanks!

As for being able to limit the amount of writes to disk. Finetuning draws on the wider Python GPT trainer scripts, or to put it another way, scripts I have no direct access to or control of. There's no direct way within Python for me to force those other scripts to behave in a certain way or store their work in memory vs disk.

I can suggest a sort of solution for you though, its a few extra steps mind, but as far as I can think it **should** keep most (possibly all) activity occurring within RAM. This would be to setup a RAM-Disk and run the training from that. Obviously I've not tried this, so I'm giving you a loose hypothetical on how to do it. 

In short a RAM-Disk creates a virtual disk drive, but stored only within your System RAM, meaning if you switch your computer off, that data is gone! Here is some example software (found with a quick Google search) https://www.softperfect.com/products/ramdisk/ I'm sure there are others out there. Microsoft no longer provide a RAM-Disk option as part of the Windows OS (which I believe you use based on your earlier screenshots).

So what you would do is something like this:

- Setup a RAM-Disk (lets say its the **K** drive).
- Start the Python environment you use.
- Copy the AllTalk folder from its actual **C** drive location (or wherever) to your **K** drive RAM-Disk.
- In your command prompt, go to the **K**:\alltalk_tts folder and run `python finetune.py` 
- Go through all your finetuning as normal.
- At the end, when it copies the model and sample wav's to **K**:\alltalk_tts\models\trainedmodel (or whichever one you use) you would need to copy that off the **K**:\ drive and back to the correct location on your **C**:\ drive.
- Close down your RAM-Disk.

I am making an assumption here that the majority of disk activity you are seeing is specifically to do with the model, its training and the training data being accessed and written to. I expect there may be an element of the OS still doing something with temporary files, but you cant avoid everything.

So a few extra steps, but should get you what you want.

Hope that gives you solution!

Thanks
