### ISSUE TITLE
fixed!! TTS Generator doesnt work on standalone ALLTALK in linux

### ISSUE THREAD

**Issue by unifirer** [erew123/alltalk_tts#77]
fixed by changing playback from in browser to no playback 

export to wav is still broken, i reinstalled today on linux, broken on both win and linx.

Please generate a diagnostics report and upload the "diagnostics.log".

[diagnostics.log](https://github.com/erew123/alltalk_tts/files/13986073/diagnostics.log)

when i click generate in the generator, the wheel flashes and it says 3 out of 3 completed but nothing is generated and nothing new is in the console

**To Reproduce**
put any text into the generator tts

**Desktop (please complete the following information):**
AllTalk was updated: newest version 19th jan
Custom Python environment: [default}
Text-generation-webUI was updated: not using, using standalone

**Comment by erew123** [comment]
Hiya!

So I just went and did a full fresh install myself on linux (of the current build of AllTalk):

Did you `git clone` the latest version of did you down load a zip file from https://github.com/erew123/alltalk_tts/releases ?

![image](https://github.com/erew123/alltalk_tts/assets/35898566/c857c37f-7e90-4895-98bb-cece9d5dd625)

After I set it up, I connected to the TTS Generator on http://127.0.0.1:5851/etc.... generated 3x lines of text and hit export. As there are only 3x lines to export, I wouldnt expect to see an export wheel. With only 3 its a blink and you will miss it.

![image](https://github.com/erew123/alltalk_tts/assets/35898566/48f9a726-e8ca-4897-866d-ad0f46c8e673)

Those went to export fine (as above). I checked the diagnostics console (press `F12` and select `console`) and that shows clear:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/62a97f0f-d3ee-4f4e-92ec-15f79128594f)

So here is my proposal/suggestion. 

- In a terminal, go into the `alltalk_tts` folder and type `git pull` then press enter.
- This will ensure you have a 100% up to date, like for like copy of whats on here.
- Once you have done that, start AllTalk and go to the TTS generator on the http://127.0.0.1:7851/..... page.
- Generate some TTS from text and click the export button.
- If it doesnt work, press `F12` and select `console` there should/would be an error message in there if it cant load the bits to export. I need to know what that error message is please.

Thanks

**Comment by unifirer** [comment]
Hello thank you for your reply.
It works the output file was in a different folder.

Thank you
________________________________

**Comment by erew123** [comment]
Glad that's sorted for you! Ill close off the ticket.

Thanks
