### ISSUE TITLE
batch que please?

### ISSUE THREAD

**Issue by unifirer** [erew123/alltalk_tts#8]
with the deepspeed optimisation, we can actually do multiple books in 1 night!

if u have some spare time, a batch que would allow us to do so!

another fantastic reason to do so, somewhere in the process, the max length of wav is <17h. after that the output shows 17 but is 4.5hrs max, maybe its a limit of ffmpeg or something else like a limit of the wav file or the header or something, i couldnt find it tho

thank you very much

**Comment by erew123** [comment]
Well there is a 4GB limitation https://en.wikipedia.org/wiki/WAV#Limitations and it is an old standard, going back to 1991. I cant speak as to how things such as ffmpeg would handle such large files. But that's 6.8 hours at 44100Hz, so maybe closer to 10-12 tops at 22050Hz (with headers/padding overheads). 

An average book, you're looking at generating 70,000-100,000 words, 3000-6000 sentences (or wav files should I say) then trying to combine them into 1x file. Its quite a technical overhead on a system to do that and I'm not sure where the limitations are. It would be a decent amount of testing and coding to make something like that work.

Can I ask what your exact use case is?

**Comment by unifirer** [comment]
Oh that makes sense. it outputs 24k and does 9.5 hours without a problem. So the maximum is somewhere between 10 and 17 hours.

The final combination process was so intensive that my game lagged out and my computer froze  for 2minutes.

Audiobook production. That's my use case.  If you have spare time and energy to make it output multiple files instead in a queue as a batch as a new feature request. That would help a lot.

Like the feature that handbrake has. batch processing.

Please inform me of interesting jobs and opportunities
________________________________

**Comment by unifirer** [comment]
Perhaps instead of queing multiple videos. que multiple text files


________________________________

**Comment by unifirer** [comment]
With text files we can split them into chapters too!
________________________________
