### ISSUE TITLE
Bat Directly closing

### ISSUE THREAD

**Issue by ZEro07Seve** [erew123/alltalk_tts#89]
Please generate a diagnostics report and upload the "diagnostics.log".

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**

G:\Ai\Alltalk\alltalk_tts>start_alltalk.bat
Traceback (most recent call last):
  File "G:\Ai\Alltalk\alltalk_tts\script.py", line 47, in <module>
    from TTS.api import TTS
ModuleNotFoundError: No module named 'TTS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\Ai\Alltalk\alltalk_tts\script.py", line 50, in <module>
    logger.error(
    ^^^^^^
NameError: name 'logger' is not defined

**To Reproduce**
Starting alltalk.bat

**Screenshots**

**Text/logs**

INFO:root:NOTE requirements.txt not found. Skipping version checks.
INFO:root:OS Version: Windows 10.0.19045
INFO:root:Note: Windows 11 will list as build is 10.x.22xxx
INFO:root:Torch Version: 2.1.0+cu121
INFO:root:System RAM: 19.98 GB available out of 31.93 GB total
INFO:root:CUDA_HOME: N/A
INFO:root:Port Status: Port 7851 is available.
INFO:root:Python Version: 3.11.7
INFO:root:Python Version Info: sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)
INFO:root:Python Executable: G:\Ai\AlltalkShit\alltalk_tts\alltalk_environment\env\python.exe
INFO:root:Python Virtual Environment: N/A (Should be N/A when in Text-generation-webui Conda Python environment)
INFO:root:Conda Environment: G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env
INFO:root:
Python Search Path:
INFO:root:  G:\Ai\Alltalk\alltalk_tts
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\python311.zip
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\DLLs
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\Lib
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\Lib\site-packages
INFO:root:
OS PATH Environment Variable:
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\Library\mingw-w64\bin
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\Library\usr\bin
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\Library\bin
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\Scripts
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\env\bin
INFO:root:  G:\Ai\Alltalk\alltalk_tts\alltalk_environment\conda\condabin
INFO:root:  C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
INFO:root:  C:\ProgramData\Oracle\Java\javapath
INFO:root:  C:\Program Files (x86)\Common Files\Oracle\Java\javapath
INFO:root:  C:\WINDOWS\system32
INFO:root:  C:\WINDOWS
INFO:root:  C:\WINDOWS\System32\Wbem
INFO:root:  C:\WINDOWS\System32\WindowsPowerShell\v1.0
INFO:root:  C:\WINDOWS\System32\OpenSSH
INFO:root:  C:\Program Files (x86)\GtkSharp\2.12\bin
INFO:root:  C:\Program Files\Intel\WiFi\bin
INFO:root:  C:\Program Files\Common Files\Intel\WirelessCommon
INFO:root:  C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
INFO:root:  C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
INFO:root:  C:\WINDOWS\system32
INFO:root:  C:\WINDOWS
INFO:root:  C:\WINDOWS\System32\Wbem
INFO:root:  C:\WINDOWS\System32\WindowsPowerShell\v1.0
INFO:root:  C:\WINDOWS\System32\OpenSSH
INFO:root:  C:\Program Files\dotnet
INFO:root:  D:\Node
INFO:root:  G:\Git\cmd
INFO:root:  C:\Users\Agando\AppData\Local\Microsoft\WindowsApps
INFO:root:  C:\Program Files\Intel\WiFi\bin
INFO:root:  C:\Program Files\Common Files\Intel\WirelessCommon
INFO:root:  ÔÇ£C:\ffmpeg\bin
INFO:root:  C:\Users\Agando\AppData\Roaming\npm
INFO:root:  C:\WINDOWS\system32
INFO:root:GPU Information:
Mon Jan 29 21:10:33 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060      WDDM  | 00000000:2B:00.0  On |                  N/A |
|  0%   43C    P0              31W / 160W |   1230MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      6224    C+G   C:\Windows\explorer.exe                   N/A      |
|    0   N/A  N/A      6316    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A     11420    C+G   ...2txyewy\StartMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A     12940    C+G   ...wekyb3d8bbwe\XboxGameBarWidgets.exe    N/A      |
|    0   N/A  N/A     14624    C+G   ....Search_cw5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     15480    C+G   D:\Programme\Steam\steam.exe              N/A      |
|    0   N/A  N/A     15812    C+G   ...ekyb3d8bbwe\PhoneExperienceHost.exe    N/A      |
|    0   N/A  N/A     17004    C+G   ...crosoft\Edge\Application\msedge.exe    N/A      |
|    0   N/A  N/A     17524    C+G   ...oogle\Chrome\Application\chrome.exe    N/A      |
|    0   N/A  N/A     17864    C+G   D:\elgato\StreamDeck\StreamDeck.exe       N/A      |
|    0   N/A  N/A     18160    C+G   ...\cef\cef.win7x64\steamwebhelper.exe    N/A      |
|    0   N/A  N/A     18188    C+G   G:\Corsair\iCUE.exe                       N/A      |
|    0   N/A  N/A     18324    C+G   ...cal\Microsoft\OneDrive\OneDrive.exe    N/A      |
|    0   N/A  N/A     20192    C+G   ...siveControlPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A     21808    C+G   ...12.0_x64__8wekyb3d8bbwe\GameBar.exe    N/A      |
|    0   N/A  N/A     25356    C+G   ...5n1h2txyewy\ShellExperienceHost.exe    N/A      |
+---------------------------------------------------------------------------------------+

INFO:root:Package Versions:
INFO:root:annotated-types>= 0.6.0
INFO:root:anyio>= 3.7.1
INFO:root:certifi>= 2022.12.7
INFO:root:cffi>= 1.16.0
INFO:root:charset-normalizer>= 2.1.1
INFO:root:click>= 8.1.7
INFO:root:colorama>= 0.4.6
INFO:root:cutlet>= 0.3.0
INFO:root:deepspeed>= 0.12.7+d058d4b
INFO:root:fastapi>= 0.104.1
INFO:root:filelock>= 3.9.0
INFO:root:fsspec>= 2023.12.2
INFO:root:fugashi>= 1.3.0
INFO:root:h11>= 0.14.0
INFO:root:hjson>= 3.1.0
INFO:root:huggingface-hub>= 0.20.3
INFO:root:idna>= 3.4
INFO:root:importlib-metadata>= 4.8.1
INFO:root:jaconv>= 0.3.4
INFO:root:Jinja2>= 3.1.2
INFO:root:MarkupSafe>= 2.1.3
INFO:root:mojimoji>= 0.0.13
INFO:root:mpmath>= 1.3.0
INFO:root:networkx>= 3.0
INFO:root:ninja>= 1.11.1.1
INFO:root:numpy>= 1.24.4
INFO:root:packaging>= 23.2
INFO:root:Pillow>= 9.3.0
INFO:root:pip>= 23.3.1
INFO:root:psutil>= 5.9.8
INFO:root:pycparser>= 2.21
INFO:root:pydantic>= 1.10.13
INFO:root:pydantic_core>= 2.16.1
INFO:root:pynvml>= 11.5.0
INFO:root:python-multipart>= 0.0.6
INFO:root:PyYAML>= 6.0.1
INFO:root:py-cpuinfo>= 9.0.0
INFO:root:regex>= 2023.12.25
INFO:root:requests>= 2.31.0
INFO:root:safetensors>= 0.4.2
INFO:root:setuptools>= 68.2.2
INFO:root:sniffio>= 1.3.0
INFO:root:sounddevice>= 0.4.6
INFO:root:soundfile>= 0.12.1
INFO:root:starlette>= 0.27.0
INFO:root:sympy>= 1.12
INFO:root:tokenizers>= 0.15.1
INFO:root:torch>= 2.1.0+cu121
INFO:root:torchaudio>= 2.1.0+cu121
INFO:root:torchvision>= 0.16.0+cu121
INFO:root:tqdm>= 4.66.1
INFO:root:transformers>= 4.36.2
INFO:root:typing_extensions>= 4.8.0
INFO:root:unidic-lite>= 1.0.8
INFO:root:urllib3>= 1.26.13
INFO:root:uvicorn>= 0.24.0.post1
INFO:root:wheel>= 0.41.2
INFO:root:zipp>= 3.17.0

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date]
Custom Python environment: [yes/no give details if yes]
Text-generation-webUI was updated: [approx. date]

**Additional context**

i tried to install it for the 4 time still the same issue, ty in advance keep up the great work ^^

**Comment by erew123** [comment]
Hi @ZEro07Seve Thanks for giving me the diags, that gives me quite a bit to go on. I suspect that your machine doesn't have the Python/PIP compiler requirements. These are something set by Python themselves.

https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-windows--python-requirements-for-compiling-packages

The long story short is some packages have to be compiled/built on a per machine OR per Python environment basis and on Windows, for PIP to be able to compile a package for the machine, you need the Windows C++ compiler tools and the a Windows Software Development Kit.

I suspect if you install the above and run through the install one more time, it should compile the files up for you and all should be good. It can be hard to spot with everything flashing by on screen, but I think currently you will have an error something like this when you currently try to install:

![image](https://github.com/erew123/alltalk_tts/assets/35898566/e85d0978-b368-4cd3-a8be-976c73c8d840)

If you want to check/confirm if you have the bits installed and let me know.

Thanks

**Comment by ZEro07Seve** [comment]
Good sir, Thank you very much. it worked. i had Visual Studio 2017 allready installed and tought maybe that would still work...... again Thank you!!!


Keep up the great work.
