### ISSUE TITLE
how do i enable sharing? is there a --listen or --api for alltalk tts?

### ISSUE THREAD

**Issue by 0xYc0d0ne** [erew123/alltalk_tts#90]
i cant seem to find a way to make alltalk tts avalible over LAN and not just my pc itself since i would like to be able to use alltalk tts on other devices but i dont see this option in the docs

**Comment by erew123** [comment]
Hi @0xYc0d0ne 

As standard AllTalk is on IP 127.0.0.1 which will keep it restricted to the local machine. If you want it to be available across your LAN, change its IP address to the IP address you would use on your machine e.g. if your machine is on 192.168.1.10, then in the settings page, change AllTalk's IP to 192.168.1.10 which will share it on that network cards interface. 

Should you have any other firewalling setup on your machine, you would need to also allow port 7851 through the firewall from your private lan range e.g, 192.168.1.0/24 (or 255.255.255.0 for example)

Thanks

**Comment by erew123** [comment]
Just to be 100% clear, I mean change the IP address set in AllTalks settings web page to match your machine IP address, then restart AllTalk.

Thanks

**Comment by 0xYc0d0ne** [comment]
when i try to connect to settings after putting in my computers ip and connecting to alltalk settings to check if it works my browser says cant connect and sillytavern gives me a 404 error when trying to check if alltalk works and the console says [error] getaddrinfo failed then after 120 seconds of being spammed "tts subprocess not started" all talk just closes, i am on windows btw

**Comment by 0xYc0d0ne** [comment]
ok now that worked but in sillytavern when i type in the i select  alltalk and put in my computers ip like 192.xx.xx:7851  it says "Error: HTTP Error Response: 404 Not Found"
