### ISSUE TITLE
I fine tuned someone voice. Is there any method/trick to make speech faster, happier, sad, excited, scared ?

### ISSUE THREAD

**Issue by djdthomasyyhi8** [erew123/alltalk_tts#92]
Is there no way to control intonation?
for example, I made fine tune of a person being interviewed, I don't have any audio of the person's voice excited, sad, scared, singing

**Comment by erew123** [comment]
Hi @djdthomasyyhi8 

No, there is no direct control over intonation, expression etc. It was planned by Coqui, but they never finished that as I understand.

Thanks

erew123
