### ISSUE TITLE
Hello, is there any way to do the voices laugh? Is any word or character is equivalent to laught?

### ISSUE THREAD

**Issue by eduardoichin** [erew123/alltalk_tts#93]
Hello, is there any way to do the voices laugh? Is any word or character is equivalent to laught?
Maybe with a fine tune model

**Comment by erew123** [comment]
Hi @eduardoichin

There's no way that I know of, though I know it was discussed adding it to the model https://github.com/coqui-ai/TTS/discussions/2644 but I have no information if anything was attempted/implemented. 

In theory it should be possible to fine tune a model to introduce something for laughing, but that's outside of my personal expertise, though there is some discussion on the above link.

Sorry. 

Thanks
