### ISSUE TITLE
Error with Polish characters

### ISSUE THREAD

**Issue by brainhome** [erew123/alltalk_tts#94]
Error with Polish characters

In text-generation-webui, it skips Polish characters when generating text
it's like this:
a, b, c, ć, d, e, f, g, h, i, j, k, l, ł, m, n, ń, o, p, r, s, ś, t, u, w, y, z, ż
[AllTalk TTSGen] a, b, c, , d, e, f, g, h, i, j, k, l, , m, n, , o, p, r, s, , t, u, w, y, z,
However, in Preview mode, the text reads correctly.
Fix request.

**Comment by erew123** [comment]
Hi @brainhome 

Thats strange, they should have been making it through on the range allowed, however Ive added an explicit allowance for those characters. You may want to do a git pull and check all is good now. https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-updating

Thanks

**Comment by erew123** [comment]
Hi @brainhome 

Thanks for confirming and glad its sorted!

Thanks
