### ISSUE TITLE
[feature request] Narration speed as a setting

### ISSUE THREAD

**Issue by benninkcorien** [erew123/alltalk_tts#95]
**Describe the solution you'd like**

Would it be possible to add a setting for speech rate/narration speed (as words per minute, or just an integer)? 

**Describe alternatives you've considered**

Speeding up / slowing down a generated sample in an external player is possible, but it would be nice to have it as a built-in setting. Then you could test a short sample at that speed before you generate and save the full text.

**Comment by erew123** [comment]
Hi @benninkcorien 

The only speed option that would be available for me to add is based on how the AI model generates the voice (and so not performed at time of creating the final wav file). Theres no way to actually control how many words per minute this results in and obviously depending on the length of words, this will always vary how many could be spoken within a period of time.

The speed option available with the AI model basically requests the AI model try to speak the words faster, just like asking a human to speak faster (from the documentation of the XTTS AI model):

`speed: The speed rate of the generated audio. Defaults to 1.0. (can produce artifacts if far from 1.0)`

As it notes, the more you try to move away from the default TTS synthesis, the more artificing results in the final production. I did give this an initial test quite a while back and found it caused more issues than it solved. Ill give it another go and see where that gets to, however you are looking at maybe getting a 1.3x speedup at best vs probably the 2x (or greater) than you are probably hoping for (before it begins to artifact).

I've also double checked around the software that concatenates the files into one file there and there is no option to manipulate the final resulting file. 

I assume you are looking for something that has a 2x speedup?

Thanks

**Comment by benninkcorien** [comment]
I use variable speeds (usually as fast as I can get it without missing words. So it also depends on the complexity of the text. I tend to hover somewhere between 180 and 320 wpm in the Reader app - live reading of txt/epub/docx ).

It sounds like this is not a built-in option you could make an easy front-end setting for. Plus it will result in more artifacts which is not ideal either. So I think using an external player is the best solution.

(VLC on PC or SmartAudiobook player on my phone can both easily increase the speed in increments for audio files. It just takes a few more extra clicks to transfer/open the files).

Thanks for explaining!

**Comment by erew123** [comment]
@benninkcorien Thanks for getting back to me! I will keep it in mind in case something crops up in future where I could manipulate the resulting output file. 

For now ill close off the ticket though.

Thanks
