### ISSUE TITLE
2 Bugs. Can't set output path and can't change server IP in Sillytavern

### ISSUE THREAD

**Issue by Ph0rk0z** [erew123/alltalk_tts#98]
**Describe the bug**

Try as I might, I can't set the output path via either the config file or the settings. My outputs are on a spinning drive and it updates the config, but both ST and the stand alone interface generate everything under outputs. It even made an error when outputs didn't exist. I took to making a symbolic link. Perhaps it's because it's on another drive?

The second bug is in ST itself. The plugin keeps defaulting to localhost no matter what IP I put in there. I went ahead and edited the actual default to my server IP and it finally connected.

**To Reproduce**
#1
Change output path in config or the interface. Try to generate through ST or the stand alone iface.

#2 
Put in a non local IP into the sever box on ST. Switch API method or press "reload". It never connects.

Hope it's not just me.

**Comment by erew123** [comment]
Hi @Ph0rk0z 

Ill cover ST first, This was/is an issue with ST and how it handles saving the change of IP. In short, when it first makes a connection to an IP successfully, it will save the configuration. After that first save, unless it makes a successful connection to a new IP (which it has to save the configuration first, so cant) it wont make the change. This is something Cohee (ST Dev) has being looking into on the next version of ST based on some recent interactions I had with them. Changing the IP manually in the settings file (as you have done) is the way for now, if you already have a settings file created.

With the Outputs folder, there were restrictions with what could be done with the API suite and folder locations. Its mainly a complicated restriction within Python, something I can look at in future and see if its possible to workaround another way. ST uses the generic API suite so would default to looking in the directory where AllTalk is installed and specifically for a folder called `outputs`. Using a symbolic link, as you have, is perfectly fine to do, but I appreciate this could be better documented/explained. Ill make a note to do this and also add folder location to the "to do list" for a next revision.

Thanks

**Comment by Ph0rk0z** [comment]
Makes sense, I think I edited the actual extension not the config. I should probably change it to that. Nothing ever saved so I didn't see an entry.

**Comment by erew123** [comment]
If you have any problems with ST:

In your SillyTavern Public folder `/sillytavern/public/` there is a file called `settings.json`. In there, if you search for `AllTalk` you should find `"provider_endpoint"` and you can manually change `localhost` to `192.168.1.64` (as below)

![image](https://github.com/SillyTavern/SillyTavern/assets/35898566/144e4ac4-87dc-4a2b-8a73-39314abed1ca)
